### ISSUE TITLE
GM_registerMenuCommand problem

### ISSUE THREAD

**Issue by Romzik85** [Tampermonkey/tampermonkey#838] opened 2019-12-13 09:50 UTC
if the plugin uses `GM_registerMenuCommand`, then when you enable or disable the plugin, it is put very bad

## Specifications

- Google Chrome: 78.0.3904.108
- TM: v4.9
- OS: Windows 10

# Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @noframes
// @name         test
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include      *
// @grant        GM_registerMenuCommand
// ==/UserScript==

(function() {
	'use strict';
	GM_registerMenuCommand('menu item', ()=>{alert('it work')});
})();
```

![ava](https://user-images.githubusercontent.com/15080586/70790897-3fbef300-1d96-11ea-8468-e36cbb657fb4.gif)

**Comment by derjanb** [comment] 2019-12-13 21:21
Duplicate of #801

**Closed by derjanb** 2019-12-13 21:21 UTC
