### ISSUE TITLE
script not running inside iframe

### ISSUE THREAD

**Issue by bobleger** [Tampermonkey/tampermonkey#602] opened 2018-09-18 05:19 UTC
https://www.aol.com/video/view/meet-dancing-with-the-stars-season-27-cast/5b99ad4d943c3c182a4d774c/

the video on that page runs inside an iframe. tampermonkey doesn't run scripts inside the iframe.

// ==UserScript==
// @include    *
// ==/UserScript==

**Comment by tophf** [comment] 2018-09-18 05:46
Indeed, TM doesn't run userscripts in any `about:blank` iframes as witnessed in devtools console: only 4 iframes that have an explicit URL in their src attribute are listed out of 8 total on the page.

```js
// ==UserScript==
// @name    test
// @include *
// ==/UserScript==
if (window !== top) {
  console.log(location.href, document.body);
}
```

I also don't see `"match_about_blank": true` in TM's manifest.json.

**Comment by tophf** [comment] 2018-09-18 06:05
As a workaround you can manually process that iframe:

```js
// ==UserScript==
// @name    test
// @match   https://www.aol.com/video/view/*
// ==/UserScript==

setTimeout(function poll() {
  const iframe = document.querySelector('iframe[allowfullscreen]');
  const doc = iframe && iframe.contentDocument;
  const video = doc && doc.querySelector('video[src]');
  if (!video) {
    setTimeout(poll, 100);
    return;
  }

  console.log(video);
  // do something with video here

});
```

**Comment by derjanb** [comment] 2022-06-22 18:09
Duplicate of #312

**Closed as completed by derjanb** 2022-06-22 18:09 UTC
