### ISSUE TITLE
Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!

### ISSUE THREAD

**Issue by FalkaoDk** [Tampermonkey/tampermonkey#680] opened 2019-04-11 09:43 UTC
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

// ==UserScript==
// @name         Krunker.io 2019 Aimbot (Hacks,Mods,Cheats) | NO DISCONNECT ISSUE | KRUNKERIO.ORG
// @version      6.5
// @description  Aimbot, Unlimited Ammo, Auto Heal, ESP, Wall Hack, Unlimited Ammo... -2019 krunkerio hack- ADBLOCK
// @author       MR.Coder
// @namespace MR.Coder
// @match        *://*.youtube.com/*
// @match        *://diservers.org/*
// @match        *://moomoo.io/*
// @match        *://krunker.io/*
// @match        http://dev.moomoo.io/*
// @match        *sandbox.moomoo.io/*
// @include      /^(https?:\/\/)?(www\.)?(.+)krunker\.io(|\/|\/\?(server|party)=.+)$/
// @grant        GM_xmlhttpRequest
// @require https://greasyfork.org/scripts/368273-msgpack/code/msgpack.js?version=598723
// @require http://code.jquery.com/jquery-3.3.1.min.js
// @require https://code.jquery.com/ui/1.12.0/jquery-ui.min.js
// @require https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js
// @run-at       document-start
// ==/UserScript==

...```

**Comment by derjanb** [comment] 2019-04-11 12:02
Duplicate of #640

**Closed by derjanb** 2019-04-11 12:02 UTC
