### ISSUE TITLE
please add scrollview for [tampermonkey for safari] to show tweaks content like it shows in chrome

### ISSUE THREAD

**Issue by wangliangliang2** [Tampermonkey/tampermonkey#1364] opened 2021-11-03 07:23 UTC
(Please fill out the issue template with your details)
it seems not use scrollview to present tweaks content in safari ,so could you use scrollview to show developer's tweaks? 

## Expected Behavior
<img width="433" alt="image" src="https://user-images.githubusercontent.com/20638550/140021874-67bbd388-f812-435e-8d0d-9be804b37db3.png">

## Actual Behavior
tampermonkey in safari maybe not use scrollview to show tweaks content, so it can't show tweak's all content.
![image](https://user-images.githubusercontent.com/20638550/140021677-e4fdafe6-97dd-4041-9677-d154a58bb26a.png)

## Specifications

- Safari: (Version 15.1 (17612.2.9.1.20))
- OS: (MacOS 12.0.1 (21A559))

## Script
https://greasyfork.org/en/scripts/419081-知乎增强
https://greasyfork.org/en/scripts/412212-知乎美化

Test Site: https://www.zhihu.com/question/22210090

PS: You may not use tweaks in zhihu.com, if you want to do that. you should use vpn to delete https CSP header.

But the problem should come out when use too much tweak in one website.

**Comment by derjanb** [comment] 2024-06-06 07:12
Duplicate of #1872

**Closed by derjanb** 2024-06-06 07:12 UTC
Labels: safari
