### ISSUE TITLE
Eslint error on Opera GX

### ISSUE THREAD

**Issue by lilcsz** [Tampermonkey/tampermonkey#1099] opened 2020-12-15 20:26 UTC
- Opera GX 71.0.3770.456
- OS: Windows 10

My code is not working on Opera GX but it's working on chrome.

## Script

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==

async function generateKey(passphrase, salt){
    // Import password as CryptoKey object
    let enc = new TextEncoder()
    let masterkey = await window.crypto.subtle.importKey(
        "raw",
        enc.encode(passphrase),
        {name: "PBKDF2"},
        false,
        ["deriveBits", "deriveKey"]
    )


```

**Comment by derjanb** [comment] 2021-01-03 19:52
A more complete test script logs a `CryptoKey` instance. Not sure what the problem is. Please add details.

```JS
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match https://example.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==

(async () => {
    async function generateKey(passphrase, salt){
        // Import password as CryptoKey object
        let enc = new TextEncoder()
        let masterkey = await window.crypto.subtle.importKey(
            "raw",
            enc.encode(passphrase),
            {name: "PBKDF2"},
            false,
            ["deriveBits", "deriveKey"]
        )
        return masterkey
    }

    console.log(await generateKey('123', '456'));
})();
```

**Comment by derjanb** [comment] 2021-01-03 19:53
OK, I got it... 🙈

Duplicate of #1112

**Closed by derjanb** 2021-01-03 19:53 UTC
Labels: feedback needed, opera
