### ISSUE TITLE
[safari macOS] ALL scripts do not work always

### ISSUE THREAD

**Issue by pilgrim112** [Tampermonkey/tampermonkey#812] opened 2019-11-17 07:11 UTC
(Please fill out the issue template with your details)
Thank you. I have received your e-mail
       "What script does not work? Please post a report here:   https://github.com/Tampermonkey/tampermonkey/issues"
This needs to be stressed that all scripts do not work always.
工具栏中的图标有红点显示，告知我 脚本正在运行。但是，我的 safari 浏览器并没有发生任何变化。
我尝试过多次。在偶尔的情况下，我重启电脑或者多次重启浏览器 才能正常运行。
我怀疑不是脚本的原因，而是Tampermonkey的 safari 版本本身的 bug。

Many comments show

## Specifications
·macOS Catalina
·Safari浏览器  版本13.0.3 (15608.3.10.1.4)

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment] 2019-11-17 13:02
Duplicate of #806

**Closed by derjanb** 2019-11-17 13:02 UTC
