### ISSUE TITLE
[feature request] User profiles

### ISSUE THREAD

**Issue by Parvares** [Tampermonkey/tampermonkey#2091] opened 2024-06-14 20:15 UTC
It would be great if you could integrate support for distinct **user profiles** or **folders**, allowing users to activate just one at a time. Using just one profile would alleviate the inconvenience of having to manually disable multiple conflicting scripts each time, or using different userscript managers.
Thanks very much!

**Comment by derjanb** [comment] 2024-07-21 18:53
Duplicate of #267

**Closed by derjanb** 2024-07-21 18:53 UTC
