### ISSUE TITLE
Allow tampermonkey access to file URLs?

### ISSUE THREAD

**Issue by pizzzzzzzza** [Tampermonkey/tampermonkey#1403] opened 2022-01-19 22:54 UTC
I am trying to add an extension on to tampermonkey, but to install it, tampermonkey would have to have access to file URLs, On Chrome, it is very easy to do that, but on Firefox there is no option. Is there a way to fix this?
## Expected Behavior
Settings > Extensions > Permissions > Allow access to file URLs

## Actual Behavior
Settings > Extensions > Permissions    No way to change the permissions and make it so that tampermonkey can file URls

**Comment by 7nik** [comment] 2022-01-20 07:38
There is still no way to read files in FF: https://github.com/Tampermonkey/tampermonkey/issues/347#issuecomment-269039234

**Comment by derjanb** [comment] 2022-01-20 07:48
Duplicate of #1399 

Tampermonkey 4.15+ will allow at least userscript installation via drag and drop. Besides this @7nik is right. I don't know any other way to access local files in FF.

**Closed by derjanb** 2022-01-20 07:48 UTC

**Comment by derjanb** [comment] 2022-01-20 07:51
> I don't know any other way to access local files in FF.

Well, that's not entirely true. For userscript installation you can also open Tampermonkey's options page, open the new script tab, clear the editor and drag and drop the *.user.js to the editor. It should not be filled with the content of the userscript.

**Comment by Coldblackice** [comment] 2022-08-14 08:37
> _Well, that's not entirely true.

That's not Tampermonkey accessing file URLs. That's "copying and pasting" text into Tampermonkey, and obviously not what he's looking for.
