### ISSUE TITLE
Scripts not work when Safari quit one time.

### ISSUE THREAD

**Issue by ArsenicX** [Tampermonkey/tampermonkey#1029] opened 2020-09-13 03:15 UTC
## Expected Behavior
Scripts work every time.

## Actual Behavior
When i quit Safari, then open it again, all the scripts will not work. Even they appear they are working normally
In order to make Tampermonkey works again, I have to goto Safari setting-extension, then repeat turning on Tampermonkey , turning off Tampermonkey and quitting Safari. It will works after trying some times.

## Specifications
- Safari: Version 13.1 (15609.1.20.111.8)
- TM: 4.11.6117 on AppStore
- OS: MacOS 10.15.4

 
I asked some friends and they said they have same problem.
Hope you can repair this problem, thx!!
Sorry for my poor English.

**Comment by derjanb** [comment] 2021-07-01 12:32
I've updated Tampermonkey to version 4.13.6140. There were internal and system lib updates and I couldn't reproduce the issue. So can you please check whether the new version fixes the issue? Thanks.

**Comment by ArsenicX** [comment] 2021-07-02 01:55
> I've updated Tampermonkey to version 4.13.6140. There were internal and system lib updates and I couldn't reproduce the issue. So can you please check whether the new version fixes the issue? Thanks.

Afraid not. I just updated the Tampermonkey to version 4.13.6140, the issue is still there: some of scripts can't work.
And there is one more issue: the Utilities - Cloud - Show Backups could not work. The Onedrive option works, but the Google Drive option not.

**Comment by derjanb** [comment] 2023-08-01 07:17
Should be fixed at 4.20.6184 which is currently rolled out. Thanks for reporting.

**Closed by derjanb** 2023-08-01 07:17 UTC
Labels: feedback needed, safari
