### ISSUE TITLE
Tampermonkey on Firefox needs lots of re-login to Google Drive?

### ISSUE THREAD

**Issue by shelbyKiraM** [Tampermonkey/tampermonkey#1450] opened 2022-03-18 19:18 UTC
## Expected Behavior
Logging into Google Drive sync should almost never ask to reauth...

## Actual Behavior
It seems like it needs me to re-login almost every day. Firefox super often reopens this url: [https://accounts.google.com/o/oauth2/v2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata&access_type=offline&include_granted_scopes=true&redirect_uri=https%3A%2F%2Fauth.tampermonkey.net%2Foauth.php&response_type=code&client_id=408438522028-3cgn3t3jas3fak7isbnfod1q4h15g2fv.apps.googleusercontent.com&state=!!drive-a9e96c53-6aeb-4d16-9640-0568171cc0d0](https://accounts.google.com/o/oauth2/v2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata&access_type=offline&include_granted_scopes=true&redirect_uri=https%3A%2F%2Fauth.tampermonkey.net%2Foauth.php&response_type=code&client_id=408438522028-3cgn3t3jas3fak7isbnfod1q4h15g2fv.apps.googleusercontent.com&state=!!drive-a9e96c53-6aeb-4d16-9640-0568171cc0d0)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- Firefox: 98.0.1
- TM: 4.15.6154
- OS: Windows 10, Windows 11, macOS wtv the latest is lol

## Script

I would LOVE to be able to script auto-selecting a userrrr!! Everything I tried didn't work. I'ma comment out the part below...

I couldn't find a Firefox version in quick searches to submit issues on... link if I should move this there?

**Comment by derjanb** [comment] 2022-03-18 19:24
Duplicate of #904 

Please see https://github.com/Tampermonkey/tampermonkey/issues/904#issuecomment-630848291 for a userscript based solution.

**Closed by derjanb** 2022-03-18 19:24 UTC
