### ISSUE TITLE
icon isn't displayed properly in the top bar

### ISSUE THREAD

**Issue by P0sce3fa** [Tampermonkey/tampermonkey#1513] opened 2022-05-23 07:58 UTC
(Please fill out the issue template with your details)

## Expected Behavior
Tampermonkey will show icons in top bar

## Actual Behavior
Icon is blank (transparent)
![SCR-20220523-m61](https://user-images.githubusercontent.com/17513790/169771663-a95548c1-6ad6-4c5b-95c3-3f1c8b9afc22.png)

## Specifications

- Safari: 版本15.4 (17613.1.17.1.13)
- macOS: 12.3.1 (21E258)(arm m1)

**Comment by P0sce3fa** [comment] 2022-05-23 08:00
![SCR-20220523-m8k](https://user-images.githubusercontent.com/17513790/169772137-06dc570a-dd69-4ce2-a2f9-1c4dfd90b882.png)

**Comment by derjanb** [comment] 2022-05-23 18:04
Duplicate of #1420

**Closed by derjanb** 2022-05-23 18:04 UTC
