### ISSUE TITLE
不能编辑脚本（在firefox52上）

### ISSUE THREAD

**Issue by xiaopangju** [Tampermonkey/tampermonkey#851] opened 2020-01-04 08:27 UTC
(Please fill out the issue template with your details)

## Expected Behavior
Can edit.

## Actual Behavior
CAN't edit.Display blank.

![搜狗截图20200104162005.jpg](https://i.loli.net/2020/01/04/gtTPZvkE6b2ARmS.jpg)

## Specifications

firefox52.9.0 (32bit)
Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0
## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment] 2020-01-04 08:39
Duplicate of #833

**Closed by derjanb** 2020-01-04 08:39 UTC
