### ISSUE TITLE
Tampermonkey + at least one more extension can make Safari forget that an iframe-based top level navigation was triggered by a user gesture

### ISSUE THREAD

**Issue by dimdom69** [Tampermonkey/tampermonkey#1836] opened 2023-08-15 02:26 UTC
I am on 4.20.6184 and I am still having the exact same issue as described in issue #1536

![Untitled](https://github.com/Tampermonkey/tampermonkey/assets/5253663/c24b1488-dc61-4414-9b54-e4706ecea88e)

**Safari:** Version 16.6 (18615.3.12.11.2)
**TM:** 4.20.6184
**OS:** MacOS Ventura 13.5 (22G74)

_Originally posted by @lehrian in https://github.com/Tampermonkey/tampermonkey/issues/1536#issuecomment-1678018547_

**Comment by isokaze04** [comment] 2023-08-19 10:31
same issue here.

**Comment by dewey** [comment] 2023-09-01 23:01
I have the exact same configuration as @viliam-husar and I'm also running into the issue. Took me a while to narrow down where this issue was coming from.

**Comment by derjanb** [comment] 2023-10-17 16:04
Duplicate of #1840

I guess you all have 1Password installed?

**Comment by dimdom69** [comment] 2023-10-17 16:16
Excuse me? No I do not have 1Password installed. Maybe wait a few minutes before closing the issue to get a response to your question.

**Comment by derjanb** [comment] 2023-10-17 18:51
I can't reproduce.

Tested at 
* Sonoma + Safari 17.0 + Tampermonkey 4.20.6184
* Big Sur + Safari 16.6.1 + Tampermonkey 4.20.6184

Please add more details. What else extension do you have installed?

**Comment by derjanb** [comment] 2023-10-17 19:40
Google search navigates the top frame from a iframe. Not sure why this is necessary, but this triggers a Safari bug that makes the browser forget that the whole action was triggered by a user gesture.
And it looks like that it forgets about that depending on the amount of time or work that passed since the click. That's why two extensions are necessary to trigger the issue. At the moment there is nothing I can do to fix the issue.

I'll look into writing a userscript that directly navigates to the search entries instead of creating an iframe to start the tab navigation later.

https://html.spec.whatwg.org/multipage/browsers.html#sandboxed-top-level-navigation-with-user-activation-browsing-context-flag

**Comment by derjanb** [comment] 2023-10-26 22:12
Please try this userscript. It fixes the issue here. If you still see issues, then please open the "Web Inspector" and check whether the selector used at `document.querySelectorAll` matches the anchor tag (<a>) you've clicked. Thanks.

https://gist.github.com/derjanb/d4506acc43ae8692c4ceddb0e387ccca/raw/Fix%2520Google%2520Navigation.user.js

**Closed by derjanb** 2023-10-26 22:12 UTC
Labels: bug, external, safari

**Comment by dewey** [comment] 2023-10-27 16:31
Thank you, this seems to fix the issue for me and I can use Tampermonkey again!

**Comment by jpmontez** [comment] 2023-10-30 02:51
It works for most links on a results page. However, if you try and click Wikipedia links on the sidebar or YouTube videos or anything not a general search result, it clicks don't work.

**Comment by derjanb** [comment] 2023-10-30 19:04
@jpmontez It's workgin fine here with these links too.

Can you please open the Web Inspector, click the crosshair symbol (red) and select a link (red) that is not working.
Then search the next outer `<a` tag (green) and check whether it has a `data-ved` attribute (green). How does the element look for you?

![image](https://github.com/Tampermonkey/tampermonkey/assets/767504/13d4f643-f1e6-4078-9d78-c9a1c985a5df)

**Comment by jpmontez** [comment] 2023-10-30 20:11
It looks like this. I disabled all other extensions except for 1Password and Tampermonkey.

<img width="1440" alt="Screenshot 2023-10-30 at 4 08 01 PM" src="https://github.com/Tampermonkey/tampermonkey/assets/5495/8714a8c5-bccd-430e-835e-271e2883ecc9">

**Comment by jpmontez** [comment] 2023-10-30 20:14
Deleted a previous comment to show a Wikipedia link on the sidebar instead. Included is the screenshot showing the `a` tag. I've also disabled all other extensions except for 1Password and Tampermonkey.

<img width="1440" alt="Screenshot 2023-10-30 at 4 13 21 PM" src="https://github.com/Tampermonkey/tampermonkey/assets/5495/16b291cc-e2ac-4f13-aad3-1782e7f4624e">

**Comment by jpmontez** [comment] 2023-10-30 20:17
I just found the problem. There was a blacklist on the page that was preventing the script from loading. I removed it and now the links work. Thanks for looking into this, though!
