### ISSUE TITLE
TM opens google auth page in a new tab at random times

### ISSUE THREAD

**Issue by Benur21** [Tampermonkey/tampermonkey#1496] opened 2022-04-26 22:35 UTC
I changed config mode to Beginner then in "Userscript Sync" I enabled the checkbox and chose "Google Drive". It asked me to authenticate in google, all OK. But later, while I am using the browser for something else, it starts asking me to authenticate again. If I close the tab, sometimes it stubbornly reopens again immediately.

Sometimes it opens the tab right when starting the browser.

## Expected Behavior
Not ask me for authentication more times than needed (which is 1).

## Actual Behavior
At random times it sends me to a new tab asking for google authentication (where it asks me to choose which account [PS: It only asks me which account to use: I have 3; it doesn't ask me for password]).

## Specifications

- Google Chrome: 100.0.4896.127 
- TM: 4.16
- OS: Windows 10; also happened on Linux Ubuntu

**Comment by Willy-JL** [comment] 2022-05-23 20:26
+1, also happens to me on Arch Linux using both Firefox and Waterfox. From what I have seen so far it only happens to me when opening the browser. In normal windows this is not too much of a problem since I'm already authenticated, but it is still annoying that i have to wait 2-3 seconds for it to authenticate each time i open the browser... for incognito / private windows this is just awful, because it doesnt go through by itself, and closing the tab it reopens up to 5 times in a row...

**Comment by derjanb** [comment] 2022-05-30 08:35
Duplicate of #904

**Closed by derjanb** 2022-05-30 08:35 UTC
