### ISSUE TITLE
Google Drive Sync on Chromium Edge

### ISSUE THREAD

**Issue by SmartManoj** [Tampermonkey/tampermonkey#729] opened 2019-06-28 04:49 UTC
## Expected Behavior
No re sign-in for sync

## Actual Behavior
Popup sign-in every time the browser open

## Specifications

- MS Chromium Edge
- TM: (i.e. 4.8.41)
- OS: Win 10

**Comment by derjanb** [comment] 2019-07-26 08:17
Duplicate of #597

**Closed by derjanb** 2019-07-26 08:17 UTC
