### ISSUE TITLE
Ability to create folders

### ISSUE THREAD

**Issue by Eikosa** [Tampermonkey/tampermonkey#1669] opened 2022-12-07 16:30 UTC
I have a lot of scripts and have trouble organizing them, it would be really nice if folders could be added to my scripts

**Comment by Notme112** [comment] 2023-01-04 07:01
Very good idea. I was just about to suggest this feature and then saw that it already exists here as a suggestion.

**Comment by derjanb** [comment] 2023-01-25 13:23
Duplicate of #267

**Closed by derjanb** 2023-01-25 13:23 UTC
