### ISSUE TITLE
Miserable html ui on android kiwi+lemur browser specially editor. (optimise html for mobile pages). With desktop mode even more miserable ui

### ISSUE THREAD

**Issue by tathastu871** [Tampermonkey/tampermonkey#2190] opened 2024-10-04 21:49 UTC
With mobile mode:
![Screenshot_2024-10-05_031624.jpg](https://github.com/user-attachments/assets/f9b691c3-e4a3-4fa7-a7ef-440836fb0cdd)

Partially visible editor no way to resize, forced to  use desktop mode

Miserble editor in desktop mode:

https://github.com/user-attachments/assets/1646dc23-48a8-4425-9553-cea89e032073

**Comment by derjanb** [comment] 2024-10-05 17:53
Duplicate of #2048

**Closed by derjanb** 2024-10-05 17:53 UTC
