### ISSUE TITLE
(Firefox) Overflow menu is very large

### ISSUE THREAD

**Issue by sdavidg** [Tampermonkey/tampermonkey#1211] opened 2021-04-07 11:36 UTC
Goto TM icon and select "Pin to overflow menu"
![image](https://user-images.githubusercontent.com/4955944/113859979-caa2d880-97a5-11eb-90d9-42343185ff81.png)
Goto TM icon and click

## Expected Behavior
![image](https://user-images.githubusercontent.com/4955944/113860152-fcb43a80-97a5-11eb-9b3b-3bc93dd4e22b.png)

## Actual Behavior
Overflow menu is very large
![imagen](https://user-images.githubusercontent.com/4955944/113859466-39cbfd00-97a5-11eb-8dc6-b77de8ef8afc.png)

## Specifications

- Firefox 87.0 
- TM: 4.12.6132
- OS: W10

**Comment by derjanb** [comment] 2021-04-07 11:40
Duplicate of #1181 and please see https://github.com/Tampermonkey/tampermonkey/issues/1181#issuecomment-801691889 for a workaround. It is also fixed at the [latest BETA version](https://www.tampermonkey.net/?browser=firefox).

**Closed by derjanb** 2021-04-07 11:40 UTC
