### ISSUE TITLE
Wrong number of scripts

### ISSUE THREAD

**Issue by matocool** [Tampermonkey/tampermonkey#1736] opened 2023-03-14 01:17 UTC
As shown, there are only a dozen plug-ins running. But it shows dozens.

Version 4.18.1

![image](https://user-images.githubusercontent.com/83129369/224867270-355752dc-0bc0-4ae9-a53f-5e581231821f.png)

![image](https://user-images.githubusercontent.com/83129369/224867586-4a26d86b-1303-4d3e-ae19-4051a5d5c586.png)

**Comment by derjanb** [comment] 2023-03-21 08:59
Please see https://github.com/Tampermonkey/tampermonkey/issues/1071#issuecomment-737308077

Duplicate of #163

**Closed by derjanb** 2023-03-21 08:59 UTC
