### ISSUE TITLE
Save button is not working which beneath of Blacklisted Pages textarea in Settings page

### ISSUE THREAD

**Issue by ndaesik** [Tampermonkey/tampermonkey#1472] opened 2022-04-06 10:33 UTC
## Expected Behavior
Add a line of URL on 'Blacklisted Pages' textarea in setting pages and saves the value by hitting it's "save" button.

## Actual Behavior
play.google.com/books page is not loaded when a global code is running even the code doesn't change any.
So I tried blacklist the site mannually by adding a line "*play.google.com/books*" in blacklist field on setting page but the save button is not work.
`✔️ Operation completed successfully ` message is not appear when I hit the save button after modified the value of blacklist textarea.

## Specifications

- Edge: 100.0.1185.29
- TM:  4.15
- OS: Win11

**Comment by derjanb** [comment] 2022-04-06 10:34
Duplicate of #1438

**Closed by derjanb** 2022-04-06 10:34 UTC
