### ISSUE TITLE
New donation channel?

### ISSUE THREAD

**Issue by Jerrywang959** [Tampermonkey/tampermonkey#945] opened 2020-05-28 03:50 UTC
I am an ordinary Chinese and have been using tampermonkey for several months. Today I saw  the donation page but I don't have credit card or PayPal. Tampermonkey works great and I'd like to support you. Would you like to add new donation methods such as WeChat pay  and Alipay? Once added, more Chinese people is easiler to support you.

**Comment by derjanb** [comment] 2020-06-03 07:25
Duplicate of #674

**Closed by derjanb** 2020-06-03 07:25 UTC
