### ISSUE TITLE
I cant use a WebSocket to send an authentication token

### ISSUE THREAD

**Issue by Julianty123** [Tampermonkey/tampermonkey#1556] opened 2022-07-19 07:14 UTC
Hello, I am trying to open a connection with WebSocket to send my email, my password and the generated token when i complete the captcha for log in Habbo (I still don't know how to do it), but the connection always fails, I appreciate if you can help me since its my first time using Tampermonkey. https://www.habbo.es/api/public/captcha

## Expected Behavior
Open the connection

## Actual Behavior
WebSocket connection to 'ws://127.0.0.1:8090/' failed:

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. Windows 10)

## Script
```js
// ==UserScript==
// @name         Get Token
// @namespace    token
// @version      0.0.1
// @description  try to take over the world!
// @author       Julianty
// @match        https://www.habbo.es/api/public/captcha*
// @require      http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    const urlParams = new URLSearchParams(window.location.search);
    console.log(urlParams.get("token"));
    var socket = new WebSocket("ws://127.0.0.1:8090");
    socket.onopen = () =>{
        if(urlParams.has("token") && urlParams.get("token") !== ""){
            socket.send(urlParams.get("token"));
        }
    }
})();
```

**Comment by derjanb** [comment] 2022-10-12 08:32
Duplicate of #1483

**Closed by derjanb** 2022-10-12 08:32 UTC
