### ISSUE TITLE
[Safari] GM_xmlhttpRequest does not use browser cookie?

### ISSUE THREAD

**Issue by robbielj** [Tampermonkey/tampermonkey#786] opened 2019-10-19 07:11 UTC
## Specifications

- Safari: 13.0.2
- TM: 4.9.6055
- OS: mac os 10.15

I have observed that tampermonkey has a separated process (Tampermonkey (Safari)) for sending out requests. User agents differ from Safari as well. This is the reason why requests do not embed browser cookie anymore like before. 

I tried setting headers for `GM_xmlhttpRequest` to include cookie however request cannot even be sent.  Not sure whether this is fixable or there is some workaround.

**Comment by derjanb** [comment] 2019-12-12 22:57
4.10.6103 should fix setting headers of GM_xmlhttpRequest

**Comment by machsix** [comment] 2019-12-18 06:21
Firefox has similar issue. Hope it can be fixed in the next release.

**Comment by ivysrono** [comment] 2020-01-20 13:22
> 
> 
> Firefox has similar issue. Hope it can be fixed in the next release.

+1

**Comment by derjanb** [comment] 2020-01-20 13:33
@ivysrono @machsix This is issue is in no way related to Firefox, because there are major architectural differences.
If you can reproduce your issue at Tampermonkey Firefox BETA (#816) then please create a new issue and attach a script to reproduce the issue. Thanks.

**Comment by qsniyg** [comment] 2020-04-16 06:12
@derjanb I can still replicate the issue with the current beta (4.10.6112). If needed, I'll try to create an example test case (I'll have to find a test website that'll properly work with cookies), but the issue is that cookies aren't sent for websites that need them (in my case, Instagram), with GM_xmlhttpRequest.

**Comment by derjanb** [comment] 2020-04-16 06:15
@qsniyg This issue is special to Safari (which has no version 4.10.6112). So please create a new issue. A example test case would be great. Thanks.

**Comment by alexolog** [comment] 2020-06-05 17:37
> 4.10.6103 should fix setting headers of GM_xmlhttpRequest

Is it fixed?

**Comment by isokaze04** [comment] 2020-12-06 05:16
Not fixed?
`GM_xmlhttpRequest` does not attach cookie still.

**Comment by amorphobia** [comment] 2023-03-03 06:11
The issue still exists.

- Safari: 15.6.1
- TM: 4.17.6162

**Comment by derjanb** [comment] 2024-12-01 19:38
Unfortunately this can't be fixed using Safari's App technology. However, there now is a [new extension that uses Web Extension technology](https://github.com/Tampermonkey/tampermonkey/issues/1258#issuecomment-2485870092).

You can upgrade your extension [by getting the Tampermonkey bundle](https://github.com/Tampermonkey/tampermonkey/issues/1258#issuecomment-2495388545).

**Closed by derjanb** 2024-12-01 19:38 UTC
Labels: bug, safariapp
