### ISSUE TITLE
Safari's Action Menu cannot scroll

### ISSUE THREAD

**Issue by PP88PP** [Tampermonkey/tampermonkey#1940] opened 2023-12-14 12:54 UTC
(Please fill out the issue template with your details)

## Expected Behavior
Scroll the scripts in Action Menu from the top to the bottom.

## Actual Behavior
Can't scroll. Only show the bottom.

## Specifications

- Safari: 17.1.2
- TM: 4.20.6188
- OS: macOS 13.6.3

## Script

(Please give an example of the script if applicable.)

**Comment by PP88PP** [comment] 2023-12-14 12:58
![截屏2023-12-14 20 38 47](https://github.com/Tampermonkey/tampermonkey/assets/56310347/a1f9b0b1-625b-4f1f-8da0-33e39da66f42)
This is how it like. Scroll up or down both not work.

**Comment by derjanb** [comment] 2023-12-14 14:14
Duplicate of #1872

**Closed by derjanb** 2023-12-14 14:14 UTC
