### ISSUE TITLE
[MS Edge]install JS Bug on Win10 Edge browser

### ISSUE THREAD

**Issue by catcat520** [Tampermonkey/tampermonkey#358] opened 2017-02-17 05:14 UTC
win10 14393 : Edge **14**+adblock/adblock plus = Reproduce bug

fix : disable adblock/adblock plus

and win10 15031 Edge **15** the bug fixed

**Comment by derjanb** [comment] 2017-05-04 14:53
Thanks for the investigation. Settings this to dupe of #329. Updating to the Creators Update will fix the issue.

**Closed by derjanb** 2017-05-04 14:53 UTC
