### ISSUE TITLE
New QR code spam banner too big + re-appears when previously dismissed

### ISSUE THREAD

**Issue by adamlui** [Tampermonkey/tampermonkey#2242] opened 2024-11-13 05:45 UTC
![image](https://github.com/user-attachments/assets/1f32f239-36ec-4cce-912c-d7569cc5e299)

## Expected Behavior

QR spam to be porportional to menu items and not re-appear post-dismissal

## Actual Behavior

It is bulky and awkward, last re-appearance was today on TM auto-update (2024-10-29 ver)

## Specifications

- Firefox: 132.0.1
- TM: 5.3.2
- OS: Win10

Also most mobile browsers don't support Chrome extensions so if QR code leads to CWS listing, the Install button will be disabled most of the time (instead, if you must spam, link to a page of supported browsers, that's the biggest obstacle users must overcome, then they will search for TM already so QR code is not useful)

**Comment by adamlui** [comment] 2024-11-13 05:47
Also I recall testing mobile browsers that simply don't like TM even with Dev Mode on (but work with other managers) so your priority should be build a list of friendly browsers for the recommendation page

**Comment by adamlui** [comment] 2024-11-13 05:56
The ones that were confirmed working last I tested were:

- [Mozilla Firefox](https://www.mozilla.org/firefox/browsers/mobile/android/) (using [AMO](https://addons.mozilla.org/firefox/addon/tampermonkey/) ver)
- [Waterfox](https://play.google.com/store/apps/details?id=net.waterfox.android.release) (using [AMO](https://addons.mozilla.org/firefox/addon/tampermonkey/) ver)
- [Mask Browser](https://play.google.com/store/apps/details?id=net.maskbrowser.browser) (using [EWS](https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd) ver)

**Comment by derjanb** [comment] 2024-11-26 22:07
> QR spam to be proportional to menu items and not re-appear post-dismissal

Will be fixed...

> so if QR code leads to CWS listing, the Install button will be disabled most of the time (instead, if you must spam, link to a page of supported browsers, that's the biggest obstacle users must overcome, then they will search for TM already so QR code is not useful)

Scanning the QR code (with FF icon) should lead you to Firefox's play store entry or Tampermonkey if the link is opened in Firefox Android.

**Comment by derjanb** [comment] 2024-11-26 22:10
> Also I recall testing mobile browsers that simply don't like TM (e.g. popular Kiwi) even with Dev Mode on

#2055

**Comment by derjanb** [comment] 2024-11-26 23:11
> not re-appear post-dismissal

It should not re-appear unless your browser profile is broken and can't save new data. You can test this by modifying a script and then restart FF. If the changes don't persist, then TM can't save any change anymore.

**Comment by adamlui** [comment] 2024-11-27 10:48
> Scanning the QR code (with FF icon) should lead you to Firefox's play store entry or Tampermonkey (at AMO) if the link is opened in Firefox Android.

I'm saying Chrome users if led to CWS listing will not find it useful since it will not enable Install

> https://github.com/Tampermonkey/tampermonkey/issues/2055

I don't recall ever getting MV3 TM to work in a mobile browser that supported Chrome extensions w/ Dev Mode on but other managers worked, so to prevent losing mobile market share you should try to work around the issue like your competition

> It should not re-appear unless your browser profile is broken and can't save new data. You can test this by modifying a script and then restart FF. If the changes don't persist, then TM can't save any change anymore.

Script mods are honored but next time if it happens I'll show a screenshot

**Comment by derjanb** [comment] 2024-11-27 15:30
> I'm saying Chrome users if led to CWS listing will not find it useful since it will not enable Install

They will be forwarded to MS Edge at the play store. I worked with Microsoft and when installing Edge via this link, then Tampermonkey will be pre-installed.


> next time if it happens I'll show a screenshot

Please check then the output of this command as well. 

```js
chrome.storage.local.get(['#misc_configglobal_hints.items'], e => console.log(e))
```

**Comment by derjanb** [comment] 2024-11-27 20:08
Should be fixed at 5.3.6221 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

**Comment by adamlui** [comment] 2024-11-28 02:46
> They will be forwarded to MS Edge at the play store. I worked with Microsoft and when installing Edge via this link, then Tampermonkey will be pre-installed.

I just opened Edge it doesn't work though (tapping script install link on GF leads to native download prompt instead, then visiting matched site shows nothing is affected)

My scripts have hundreds of thousands of users and I recommend other managers for Android use because of this. 

Again, you should just copy how they work around the Chrome issues if you want a piece of their growing Android mobile market share (also when streaming text response from AI, TM crashes a lot of my users' browsers vs. your competition like VM and SC don't)

> Please check then the output of this command as well.
> 
> ```js
> chrome.storage.local.get(['#misc_configglobal_hints.items'], e => console.log(e))
> ```

`chrome` APIs don't work in console and `storage` is sandboxed to the extension calling it so I would have to edit your extension's source code to successfully log this key unfortunately, but I recommend hide the spam until you get Android working right

**Comment by adamlui** [comment] 2024-11-28 02:54
I may seem like a pesky annoyance but I have nothing against you, I simply raise issues as I experience them as they affect my many users too, also the fact your competitors who aren't even commercialized like yours rarely give my users any problems is why I recommend TM less and less these days (even as my first manager over 10 years ago)

**Comment by adamlui** [comment] 2024-11-28 02:57
Also a co-advisor of Mozilla's Community Advisory Board I'm on (we select FF add-ons that gain Recommended badge) just nominated your competitor VM, specifically citing its superiority to TM... so you should reflect why users are preferring other managers over yours even though yours is so old so should be most stable, then maybe follow my advice about copy them back (after fixing the bugs & issues)

**Comment by derjanb** [comment] 2024-12-15 20:01
> chrome APIs don't work from console + storage keys are sandboxed to the extension calling it

Of course, you have to execute this at the [background page/service worker](https://tmnk.net/faq#Q600). Sorry, I thought you were familiar with how to do this.

> tapping script install link on GF leads to native download prompt instead, then visiting matched site shows nothing is affected

You found #2268 a little earlier, but I was unable to reproduce it back then. However, it's fixed now.

> I simply raise issues as I experience them

Thanks! Keep up reporting issues.

Version 5.3.3 (FF version is in review) allows the QR code text to wrap. So the popup menu's width is not increased by the text anymore.
Besides this I'd like to keep it as is for now, even though the next BETA version makes the QR code a little bit smaller.

So closing this for now. Please re-open it, if you can reproduce the QR code re-appearing after being dismissed.

**Closed by derjanb** 2024-12-15 20:01 UTC
Labels: enhancement, fixed at beta

**Comment by adamlui** [comment] 2024-12-15 20:11
> Of course, you have to execute this at the [background page/service worker](https://tmnk.net/faq#Q600). Sorry, I thought you were familiar with how to do this.

What are you talking about. This issue does not pertain to my Chrome extensions. Why are you asking me to edit a Chrome extension's service worker

> You found https://github.com/Tampermonkey/tampermonkey/issues/2268 a little earlier, but I was unable to reproduce it back then. However, it's fixed now.

IDK what you mean I found anything...

> So closing this for now. Please re-open it, if you can reproduce the QR code re-appearing after being dismissed.

The people you close issues on cannot re-open them so you are making very strange comments

![image](https://github.com/user-attachments/assets/bd6266f0-d4ec-4c7e-b76a-4e053f4705e2)

**Comment by adamlui** [comment] 2024-12-15 20:12
Are u mad?

**Comment by derjanb** [comment] 2024-12-15 20:29
> What are you talking about. 

In case you see the QR code after dismissing it, execute the given snippet at Tampermonkey's background page/service worker. It will output the internal state that remembers the dismissal. 

```JS
chrome.storage.local.get(['#misc_configglobal_hints.items'], e => console.log(e))
```

> cannot actually re-open them

Just comment here and I'll re-open the issue if you can reproduce the QR code re-appear post-dismissal. Thanks.

> Are u mad?

Not sure what you mean by that and how it relates the issue.

**Comment by adamlui** [comment] 2024-12-15 20:34
> In case you see the QR code after dismissing it, execute the given snippet at Tampermonkey's background page/service worker. It will output the internal state that remembers the dismissal.

Why are you asking an unpaid victim of your bug to edit your extension's source code, this is such a bizarre interaction

> Just comment here and I'll re-open the issue if you can reproduce the QR code re-appear post-dismissal. Thanks.

I literally commented the issue has not been confirmed resolved, why are you thanking me

> Not sure what you mean by that and how it relates the issue.

Well you are trying to play off your awkward instruction to log a `chrome` method's output (and doubling down now) suggesting you meant I should edit your extension's source code (highly unbelievable, have you ever asked a victim of your bug to edit your own extension, let alone assume userscript authors are extension authors capable of navigating crx), leading me to believe I embarassed you for exposing you didn't know such a basic fact userscripts typically cannot log chrome.storage so you pivoted to your strange story

**Comment by adamlui** [comment] 2024-12-15 20:36
How it relates is emotions like anger cloud your judgment leading to abrupt closures of unresolved issues (timing was near-simultaneous to https://github.com/Tampermonkey/tampermonkey/issues/2298 further fueling my belief u are mad)

**Comment by derjanb** [comment] 2024-12-15 20:57
> you meant I should edit your extension's source code

You can execute code in the extension context when Developer Tools are open. The link to the FAQ explains how to get there. I'm sorry again. Since you're a userscript developer, I thought you know what I mean.
I just wanted some help in debugging the issue you've encountered. No need to edit anything. 
So if you see the issue again, please open the Developer Tools, select the "Console" tab and paste the JavaScript snippet at the bottom (right of the two arrows pointing to the right) and press enter. Thanks.

![image](https://github.com/user-attachments/assets/3489dea7-8c06-4809-9f9e-bb50bc22408c)

**Comment by adamlui** [comment] 2024-12-15 21:00
I absolutely know how to do this, I'm saying your statements like:

> Since you're a userscript developer, I thought you know what I mean

... reveal you are awkwardly changing your story out of embarassment because they get weirder and weirder (why would a userscript dev "know what you mean", I only know because I'm a Chrome extension dev which has service workers)

**Comment by adamlui** [comment] 2024-12-15 21:01
So I made u mad because I embarassed you into looking like an incompetent programmer in your mind

**Comment by adamlui** [comment] 2024-12-15 21:03
Also it's very unbelievable given how many (true) things I exposeed about you, and the timing of your abrupt closures of unresolved issues, also the strange way you utter "thanks" as if to mask an opposite emotion even after victim already revealed they are complaining about unpaid labor so why would a thank be genuine if you even understood they don't want to work for you, like you instinctually say it to get ppl to work for you free

**Comment by 7nik** [comment] 2024-12-15 21:38
The only thing I see, is that @adamlui seems unable to comprehend this:

> > next time if it happens I'll show a screenshot
> 
> Please check then the output of this command as well.
> 
> ```js
> chrome.storage.local.get(['#misc_configglobal_hints.items'], e => console.log(e))
> ```

(Which makes me wonder whether he really _can read_ JavaScript and even English)

Then does a bunch of false assumptions out of blue and flatulently insults @derjanb mostly for nothing.
Shame on you, @adamlui 

----

> when streaming text response from AI, TM crashes a lot of my users' browsers

As with any problem, you should open a new issue, desirably along with a reproduction script or to-do-steps.

**Comment by adamlui** [comment] 2024-12-16 07:08
@7nik I don't think you understsand the cmd he pasted _does not work from userscripts_. When I pointed this out, he got mad because it made him (in his mind) look oblivious to how his own extension even works (which is actually quite true, e.g. in [this comment](https://github.com/Tampermonkey/tampermonkey/issues/2298#issuecomment-2543331126) he didn't even know TM pops open new tabs for auto-updates)

i.e. he is lying he meant do it in extension env, because in the past, he made this comment:

> The crx is already signed by the Chrome Webstore, but the version must be reviewed by their team before release.

Source: https://github.com/Tampermonkey/tampermonkey/issues/2116#issuecomment-2227440839

Yet in current thread we're in he is trying to sell the story claiming "Sorry, I thought you were familiar with how to do this" re: CRX service worker.

So why would someone who (correctly) assumes most TM users aren't familiar with crx suddenly think "I thought you were familiar"? That makes no sense, so obviously he lied (just like other lies he made like he didn't steal my code/idea for reading storage by passing array that are blatantly unbelievable due to timing or previous comments made)

**Comment by adamlui** [comment] 2024-12-16 07:09
@7nik it's obvious he didn't know I'm a prolific crx author by his comment "the version must be reviewed by their team before release" so why would he now claim he thought I was familiar unless he were lying? (Then, think about why he lied, you will begin to understand)

**Comment by adamlui** [comment] 2024-12-16 07:12
Hint: it's because to support receiving continued free labor he must appear superior in at least technological prowess which if the lie is not sold, suggests is untrue due to he thought `chrome` method outputs work from userscript

**Comment by adamlui** [comment] 2024-12-16 07:18
@7nik how come you work for him free? Do you look up to his technical knowledge perhaps?

**Comment by 7nik** [comment] 2024-12-16 08:29
> the cmd he pasted _does not work from userscripts_

and where did he tell to execute the command in the userscript context? For me, it's obvious that the command will work only in an extension context (console). And, if you are indeed on Mozilla's Community Advisory Board as you [claim](https://github.com/Tampermonkey/tampermonkey/issues/2242#issuecomment-2505170396), you must be familiar with at least the basics of extensions and thus the right context is _obvious to you_ as well.

------

> So why would someone who (correctly) assumes most TM users aren't familiar with crx architecture suddenly think "I thought you were familiar"?

You aren't a regular TM (or any other userscript manager) user knowing nothing about coding, you are an experienced userscript developer and "Community Advisory Board Member", so the chance you know the "crx architecture" quite high. Or you aren't familiar with the "crx architecture"?

----

> @7nik how come you work for him free?

What the heck is this nonsense? What did you smoke to make up all this bs? Though, no, I don't want to know it anyway.

P.S. Don't bother to reply to me because I won't reply anyway. This issue is about problems with the QR code banner, which derjanb seems to fixed, so anything else should be discussed either in other issues or not on GitHub at all.

----

@derjanb I advise locking this conversation as already completely offtopic.

**Comment by adamlui** [comment] 2024-12-16 08:34
> and where did he tell to execute the command in the userscript context?

He didn't say anywhere originally...

> For me, it's obvious that the command will work only in an extension context (console)

For me too, why are you telling me this? You are suggesting most userscript users understand extension context like me and you (let alone are even developers)? If so, how come?

> And, if you are indeed on Mozilla's Community Advisory Board as you https://github.com/Tampermonkey/tampermonkey/issues/2242#issuecomment-2505170396, you must be familiar with at least the basics of extensions and thus the right context is obvious to you as well.

He made his reply **before** replying to that comment, also nice try trying to slander me as the liar, you really do work for him free without realizing it

![image](https://github.com/user-attachments/assets/0611a181-126c-447b-b108-46f8238bbeee)

**Comment by adamlui** [comment] 2024-12-16 08:44
> You aren't a regular TM (or any other userscript manager) user knowing nothing about coding, you are an experienced userscript developer and "Community Advisory Board Member", so the chance you know the "crx architecture" quite high. Or you aren't familiar with the "crx architecture"?

Of course I am, but he already tried to mansplain it to me so obviously thought I was a noob, I don't get why this is so hard to get (he only switched up when I accidentally made him look dumb for thinking chrome is exposed in userscript)

**Comment by adamlui** [comment] 2024-12-16 08:48
> I advise locking this conversation as already completely offtopic.

@7nik you are his unpaid advisor now lol? Also you realize you tagged me to argue he is not a liar (despite obviously so for switching from talking to a noob to sudden CRX expert) i.e. you are extending any off-topicness then advising an advisee to take action based on your own action...?
