### ISSUE TITLE
If we define the id of the body element, document-start does not work properly.

### ISSUE THREAD

**Issue by alpgul** [Tampermonkey/tampermonkey#941] opened 2020-05-22 06:15 UTC
When I assign "document-start" value to "run at" value, if the id value of the body element is defined, the script at the beginning of the document.body element runs. But if the body id value is not defined, the body element does not work first.You can test it on a site with an id value and on a site that does not. As a workaround, I disabled the run-at setting by making Inject Mode instant.
Chrome Version 81.0.4044.138 
Tampermonkey Version 4.10

`// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include        *
// @grant        none
// @run-at document-start
// ==/UserScript==

(function() {
    'use strict';
debugger;
    // Your code here...
})();`

**Comment by derjanb** [comment] 2020-05-25 18:18
Duplicate of #211

**Closed by derjanb** 2020-05-25 18:18 UTC
