### ISSUE TITLE
Accessibility of tampermonkey   

### ISSUE THREAD

**Issue by veg-xiaobo** [Tampermonkey/tampermonkey#537] opened 2018-05-03 10:22 UTC
Hi，developer to tampermonkey .  
I am a blind,In the use of this extension.  
Load some js script to improve web accessibility.  
 tampermonkey  version 4.5，There is a serious problem of keyboard accessibility.  
Update log  
「 UI:  
General layout refresh  
Replace stale icons by Font Awesome icons」  
First,After UI update  
element name of the can not be read aloud by the screen reader.  
Secondly  
Interactive element cannot be focused and click by the keyboard.  
Expectation can be repaired,Thank.

**Comment by derjanb** [comment] 2018-05-03 10:31
@veg-xiaobo Was this working on 4.4?

**Comment by veg-xiaobo** [comment] 2018-05-03 10:42
It's the version 4.5

**Comment by jsl303** [comment] 2018-12-20 06:40
I just found that If I disable enhanced editor, I can edit inside Tampermonkey editor!

**Comment by derjanb** [comment] 2021-03-18 22:33
Duplicate of #1185

**Closed by derjanb** 2021-03-18 22:33 UTC
