### ISSUE TITLE
Safari 17.0 and Tampermonkey... not loading

### ISSUE THREAD

**Issue by 101Dude** [Tampermonkey/tampermonkey#1862] opened 2023-10-02 22:56 UTC
(Please fill out the issue template with your details)

## Expected Behavior
I can access Tampermonkey settings page

## Actual Behavior
I can not access Tampermonkey settings page

## Specifications

- Safari: Version 17.0 (18616.1.27.111.22, 18616)
- Tampermonkey:
  Version:	4.20.6184
  Obtained from:	App Store
  Last Modified:	10/2/23, 5:41 PM
  Kind:	Universal
  Signed by:	Apple Mac OS Application Signing, Apple Worldwide Developer Relations Certification Authority, Apple Root CA
  Location:	/Applications/Tampermonkey.app

- OS: (i.e. MacOS 10.13.6)

I tried a complete reinstall and no dice

**Comment by beely** [comment] 2023-10-03 13:12
Are you sure this is not just this issue?:
https://github.com/Tampermonkey/tampermonkey/issues/1856

(Disable, then re-enable the extension - if it works now, then it's the above issue.)

**Comment by 101Dude** [comment] 2023-10-03 15:03
Hi,

I saw that issue before creating my issue...

In my case it never loads whereas in their issue it stops after 30 minutes, and I am using Ventura not Sonoma.

I have switched it on and off and eventually uninstalled and reinstalled, it still does not load.

￼

This is what I see, from the minute Safari starts.

The one thing the issues have in common is Safari 17. That is most likely the underlying and common factor.

**Comment by wnettoAIX** [comment] 2023-10-04 02:36
If I leave the App bundle open and then toggle the extension on and off it generally comes back to life for me; though it eventually reverts to not-working.

**Comment by pfahlstrom** [comment] 2023-10-05 15:58
I'm having the same issue on Sonoma, with the same solution. If I turn the extension off and on every time it stops working, it starts working again. It happens several times a day.

**Comment by SolarTorch** [comment] 2023-10-08 15:24
same here

**Comment by Emerelle** [comment] 2023-10-11 07:48
Not sure if it is the same or a related Problem. But since Upgrading to Mac OS Sonoma including Safari 17.0, Tampermonkey keeps crashing and needs to quit (command+q) and restarted Safari to work again. First it happened once a day, now it's multiple Times a day. Not sure if or how I can provide further information.

**Comment by derjanb** [comment] 2023-10-11 09:21
Can't update to Safari 17 at my old MacBook Pro. A new MacBook Air is on the way and should arrive within the next two days. Sorry for any inconvenience...

**Comment by LoneFireBlossom** [comment] 2023-10-13 07:59
same issue, tampermonkey always not responding

<img width="896" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/50087596/c2287158-12a5-4306-8f6e-7c371843ba7b">

**Comment by 101Dude** [comment] 2023-10-14 18:49
Can anyone verify that "Allow unsigned extensions" setting in **Safari -> Developer**` is NOT the issue?


<img width="836" alt="Screenshot 2023-10-14 at 1 45 07 PM" src="https://github.com/Tampermonkey/tampermonkey/assets/142523670/232f5a41-2f27-44e2-9063-c890f5489994">

**Comment by derjanb** [comment] 2023-10-16 17:19
I got my new MacBook Air and now was able to reproduce the issue. Should be fixed at the next version.

**Comment by derjanb** [comment] 2023-10-18 18:54
The App is "Waiting for Review" now. Forgot to click the button to move it to this state, because "Ready for review" sounded quite good... 🙈

I hope that it will fix the "Not Responding" issue. I was able to reproduce this with 6184, but sometimes it took a long time to make it happen and then it happened multiple times within some minutes. I've never seen it with 6188 (the next version) so I hope it'll be fixed.

**Comment by derjanb** [comment] 2023-10-19 17:17
The submission was accepted. Please update to 4.20.6188 and the issue hopefully is gone. Thanks.

**Closed by derjanb** 2023-10-19 17:17 UTC
Labels: bug, safari
