### ISSUE TITLE
ESLint config no longer working

### ISSUE THREAD

**Issue by svArtist** [Tampermonkey/tampermonkey#1417] opened 2022-02-15 21:09 UTC
## Expected Behavior
Configs set in Settings->Custom Linter Config are honored

## Actual Behavior
Linter seems unaffected

## Specifications

- Chromium: 98.0.4758.82 (Official Build) (64-bit)
- TM: 4.14
- OS: MS Windows 10 x64

The contents of the settings field, which used to work in previous versions:
```
{
    "env": {
        "browser": true,
        "es2020": true,
        "es6": true,
        "greasemonkey": true,
        "jquery": true
    },
    "extends": "eslint:recommended",
    "globals": {
        "trustedTypes": false
    },
    "parserOptions": {
        "ecmaFeatures": {
            "globalReturn ": true,
            "impliedStrict": true
        },
        "ecmaVersion": 11,
        "sourceType": "script"
    },
    "rules": {
        "curly": "off",
        "no-redeclare": "off",
        "no-unreachable": "off",
        "no-unused-vars": "off",
        "no-implicit-globals": "off"
    }
}```

**Comment by bo33b** [comment] 2022-02-20 07:59
Same here, since the last update. Very frustrating.
It would seem that the only property value having any effect whatsoever is `"parserOptions": {"ecmaVersion": <number>}` as omitting that does default to 5, meaning eslint quits parsing at the first `const`, `let`, `for...of` etc.

**Comment by derjanb** [comment] 2022-02-27 19:35
Should be fixed at 4.15.6153 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_15_6153.crx))

**Comment by bo33b** [comment] 2022-03-18 23:44
Confirmed fixed in 4.15, thank you.

**Closed** 2022-04-04 08:02 UTC
Labels: bug, fixed at beta
