### ISSUE TITLE
Tempermonkey error message: "No Script is Running". Using Chrome

### ISSUE THREAD

**Issue by thomkat56** [Tampermonkey/tampermonkey#1530] opened 2022-06-15 23:02 UTC
(Please fill out the issue template with your details)

## Expected Behavior
Yesterday and all years pervious when I open www.planets.nu and open a game my mods and add-on scripts would automatically run. 

## Actual Behavior
As of today, 06152022, I see message in Tempermonkey saying "No script is running", even though all needed scripts are enabled. I had no recent updates on my windows PC or Chrome.  Was there a recent update to Tempermonkey that may be affecting scripts?

## Specifications

Windows 11 Home
Chrome Version 102.0.5005.115 (Official Build) (64-bit)
Issue at www.planets.nu, scripts suddenly won't run

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

Example script

Planets.nu - Planetary Management Plugin v2

// ==UserScript==
// @name          Planets.nu - Planetary Management Plugin v2
// @description   Planetary Management Plugin v2
// @version       3.0
// @copyright	  2014, Dotman
// @license		  CC BY-NC-ND 4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
// @author        Dotman
// @contributor	  Jim Clark
// @include       http://planets.nu/#/*
// @include       http://planets.nu/*
// @include       http://play.planets.nu/*
// @include       http://test.planets.nu/*
// @history       0.2    Initial release [2013-07-28]
// @history       0.5    Major Beta Add - Method Construction, Versioning
// @history		  1.01	 Main Release

**Comment by derjanb** [comment] 2022-06-20 07:12
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/1525

**Closed by derjanb** 2022-06-20 07:12 UTC
