### ISSUE TITLE
Unable to disable/remove/clean user scripts from Firefox.

### ISSUE THREAD

**Issue by Pysis868** [Tampermonkey/tampermonkey#1407] opened 2022-01-24 19:05 UTC
## Expected Behavior
Able to revert to default page behavior.

## Actual Behavior
User scripts are still installed and running.

You can observe the effects of at least one of the linked scripts, ultra efficient, when issuing a search and watch the page reloads with additional url query parameters.  Applies to [aliexpress.com](aliexpress.com).

I can see them loaded in dev tools debugger section under the source heading `user-script:[//]`, and displays similarly when copying source URI.

## Specifications
- Firefox: (i.e. 96.0 (64-bit), fedora - 1.0)
- TM: (i.e. 4.13.6136)
- OS: (i.e. Linux Fedora 35 5.15.14-200)

## Scripts
https://greasyfork.org/en/scripts/26559-aliexpress-url-cleaner
https://greasyfork.org/en/scripts/27093-aliexpress-ultra-efficient

**Comment by Pysis868** [comment] 2022-02-07 19:59
It actually reloads, the page becomes blank, and elements are redrawn.  Either way, the script is still active, and I can view its source when convenient, when it should very not be.

**Comment by derjanb** [comment] 2022-06-09 18:42
Duplicate of #1504

**Closed by derjanb** 2022-06-09 18:42 UTC
