### ISSUE TITLE
Menu Tab Display Issue in Tampermonkey Dashboard (Darker Mode)

### ISSUE THREAD

**Issue by saymonn37** [Tampermonkey/tampermonkey#1937] opened 2023-12-12 19:51 UTC
## Expected Behavior
Correct display of menu tabs in tampermonkey dashboard on all "apperance" modes
![image](https://github.com/Tampermonkey/tampermonkey/assets/117588046/cc59e50e-306e-466c-9855-bf3294e8c7dc)

## Actual Behavior
Incorrect display of menu tabs in tampermonkey dashboard in apperance -> layout mode "Default - Darker". Tab buttons are cropped, unnecessary scrollbars are visible.
![image](https://github.com/Tampermonkey/tampermonkey/assets/117588046/17ae0608-d26c-4d6b-9906-05d71244ba0a)

## Specifications

- Chromium: Version 119.0.6045.199 (Official Build) (64-bit)
- TM: v5.0.0
- OS: Ubuntu 22.04.3 LTS

**Comment by derjanb** [comment] 2023-12-12 19:53
Duplicate of #1922

Thanks for reporting anyway. :-)

**Closed by derjanb** 2023-12-12 19:53 UTC

**Comment by saymonn37** [comment] 2023-12-12 19:55
Oh, sorry, didn't see. Thanks!:)
