### ISSUE TITLE
"Restart Tampermonkey or Factory Reset" causes an internal error in Tampermonkey on Firefox

### ISSUE THREAD

**Issue by uBlock-user** [Tampermonkey/tampermonkey#321] opened 2016-09-16 17:05 UTC
Steps to reproduce

1) Click on TM icon,followed by dashboard, then activate Advanced mode if you haven't.

2) Scroll down to the bottom where Restart Tampermonkey and Factory Reset option will be available, click on either of them and click Yes.

3) As restart/reset begins, it will crash in the middle with a white screen, followed by this dialog - http://i.imgur.com/3U4b0qh.jpg

After this, you won't be able to open settings menu or access tampermonkey options page at all and if you have a website tab running, then the badge numbers on the TM icon will blow up at a rapidfire rate.

Workaround - Open the addons page and DISABLE the extension, then ENABLE it back.

PS - This only occurs in Firefox.

FF version - 48.0.2
TM Beta version- 4.2.5291

**Comment by rjkpa** [comment] 2016-09-25 05:50
@derjanb Can you look into this ?

**Comment by uBlock-user** [comment] 2016-10-04 19:48
@derjanb will you acknowledge this or not ?

**Comment by derjanb** [comment] 2016-10-04 20:45
I can reproduce this, but it looks like reloading extensions is not supported yet. Also ```location.reload()``` is not working. So the only fix I can do at the moment is to remove the buttons.

https://bugzilla.mozilla.org/show_bug.cgi?id=1213473
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/reload

**Comment by uBlock-user** [comment] 2016-10-05 09:44
So this is a Firefox bug I take it ?

Also by removing the buttons you mean removal of Restart TM and Factory Reset options ?

PS - I dont think that firefox bug will be patched anytime soon, is there any other option besides removing those buttons ?

**Comment by derjanb** [comment] 2016-10-05 09:52
It looks like chrome.runtime.reload was fixed in Firefox 51 [1]. I'll try and come back to you. If it works then the buttons can stay there, especially since there is a workaround.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1279012

**Comment by uBlock-user** [comment] 2016-10-05 12:49
But instead of using that workaround I posted, why don't you try to fix it ? I will prefer a solution rather than a workaround, thanks.

**Comment by derjanb** [comment] 2016-10-05 13:01
If the issue from above is solved, then I'll fix TM to work with FF 51+, but that's all I can do. 

Fixing it for other versions requires either a heavy re-work of the Tampermonkey code or to port the fix from the Firefox-51-branch to other branches, but I'm not the right person to do or decide this.

**Comment by uBlock-user** [comment] 2016-10-05 14:03
No need to fix for other versions, just fix it for FF 51 and above, the latest version is FF 49, so FF will be updating to FF 51 soon.

**Closed** 2016-11-19 19:20 UTC
Labels: external
