### ISSUE TITLE
console.time doesn't appear in console.

### ISSUE THREAD

**Issue by BlackAsLight** [Tampermonkey/tampermonkey#1458] opened 2022-03-25 06:38 UTC
## Expected Behavior
See time taken between console.time and console.timeEnd when console.timeEnd gets executed.

## Actual Behavior
No time is printed into the console, but everything before, between and after said code runs as expected.

## Specifications

- Firefox: 98.0.2 (64-bit)
- TM: v4.15.6154
- OS: MacOS 12.3

## Script

```js
// ==UserScript==
// @name         Example
// @namespace    https://github.com/BlackAsLight
// @version      0.1
// @description  try to take over the world!
// @author       BlackAsLight
// @match        https://*
// @icon         https://avatars.githubusercontent.com/u/44320105
// @grant        none
// ==/UserScript==

'use strict';
function Sleep(ms) {
    return new Promise(a => setTimeout(() => a(true), ms))
}

console.time('Calc')
console.log(1)
Sleep(1000).then(() => {
    console.log(2)
    console.timeEnd('Calc')
    console.log(3)
})
```

**Comment by derjanb** [comment] 2022-03-25 15:34
Duplicate of #1451

**Closed** 2022-03-25 15:35 UTC
