### ISSUE TITLE
a new bug

### ISSUE THREAD

**Issue by xguoguo-wg** [Tampermonkey/tampermonkey#2279] opened 2024-12-06 13:43 UTC
![image](https://github.com/user-attachments/assets/9f6658c1-4a4e-4be9-9f5c-7899a783ef8b)

**Comment by xguoguo-wg** [comment] 2024-12-06 13:44
I don't know why this error happened, it's so frustrating.

**Comment by derjanb** [comment] 2024-12-06 14:37
Unfortunately I can't  read Chinese. When I get text, then I can translate it. So more information would be nice?

What is happening when?
What Tampermonkey, OS and Browser version is involved?

**Comment by jb222** [comment] 2024-12-07 09:59
Google Translate Images can help (but not much)
![7d0f74ee-0139-46c8-9f0f-00c584ef66c0](https://github.com/user-attachments/assets/365963a4-80c1-423a-8984-3666dc90720b)

**Comment by xguoguo-wg** [comment] 2024-12-07 10:08
I am using Tampermonkey version 5.3.2, the operating system is Windows 10 Home Chinese Edition, and the browser is Google Chrome version 131.0.6778.109 stable release.

________________________________
发件人: Jan Biniok ***@***.***>
发送时间: 2024年12月6日 22:38
收件人: Tampermonkey/tampermonkey ***@***.***>
抄送: xguoguo-wg ***@***.***>; Author ***@***.***>
主题: Re: [Tampermonkey/tampermonkey] a new bug (Issue #2279)


Unfortunately I can't read Chinese. When I get text, then I can translate it. So more information would be nice?

What is happening when?
What Tampermonkey, OS and Browser version is involved?

―

**Comment by derjanb** [comment] 2024-12-09 14:43
@jb222 Thanks!

@xguoguo-wg Please open the background context's console page and check it for errors -> https://tmnk.net/faq#Q600

**Comment by xguoguo-wg** [comment] 2024-12-10 10:47
thank you
________________________________
发件人: Jan Biniok ***@***.***>
发送时间: 2024年12月9日 22:44
收件人: Tampermonkey/tampermonkey ***@***.***>
抄送: xguoguo-wg ***@***.***>; Mention ***@***.***>
主题: Re: [Tampermonkey/tampermonkey] a new bug (Issue #2279)


@jb222<https://github.com/jb222> Thanks!

@xguoguo-wg<https://github.com/xguoguo-wg> Please open the background context's console page and check it for errors -> https://tmnk.net/faq#Q600

―

**Comment by derjanb** [comment] 2024-12-18 18:06
Duplicate of #2305

**Closed** 2024-12-19 09:17 UTC
Labels: feedback needed
