### ISSUE TITLE
After update Firefox and Tampermonkey addon all scripts GONE

### ISSUE THREAD

**Issue by hellresistor** [Tampermonkey/tampermonkey#2038] opened 2024-04-22 17:57 UTC
## Expected Behavior
All scripts gone after tampermonkey update.

## Actual Behavior
Have zero scripts
How Can I get that back?

## Specifications
- Firefox: (125.0.2 (64-bit))
- TM: (v5.1.0)
- OS: (Win 10 X64 )

**Comment by derjanb** [comment] 2024-04-22 18:22
I'm sorry. Duplicate of #1954

> All scripts gone after tampermonkey update.

Do you have a backup of Firefox's profile folder?

**Closed by derjanb** 2024-04-22 18:22 UTC
