### ISSUE TITLE
Problem with instant mode and latest chrome canary v62(mac os)

### ISSUE THREAD

**Issue by ale82to** [Tampermonkey/tampermonkey#431] opened 2017-08-10 23:16 UTC
enabling instant mode in tampemonkey(beta) with latest chrome canary 62.0.3181.0(macmos) causes lots of trouble,page wont load,all i get is a blank page with 
"script[object MutationEvent][object MutationEvent]style[object MutationEvent][object MutationEvent]sty|e[object MutationEvent][object
dutationEvent]script"

**Comment by tophf** [comment] 2017-08-11 06:56
Judging by https://crbug.com/754474 sounds like the issue is caused by another extension, which probably deletes the cookies that Tampermonkey uses to implement its `Instant mode`.

**Comment by derjanb** [comment] 2017-08-11 09:01
I'm unable to reproduce this (neither at Windows 10, nor at MacOS), but there is a difference in the canary version which I'm able to download and install.

I'm using 62.0.318**2**.0 instead of 62.0.318**1**.0. Can you please double-check your version and update if possible. Maybe the issues is already fixed by the Chromium team. 🤔

**Comment by ale82to** [comment] 2017-08-11 10:36
yes in that version problem is fixed thanks


In data 11 agosto 2017 11:01:15 AM Jan Biniok <notifications@github.com> ha 
scritto:

**Comment by derjanb** [comment] 2017-08-11 10:38
Great news. Thanks. 😅

**Closed by derjanb** 2017-08-11 10:38 UTC
