### ISSUE TITLE
Defer loading of script storage when @run-at is set

### ISSUE THREAD

**Issue by jonnytest1** [Tampermonkey/tampermonkey#1814] opened 2023-07-05 22:36 UTC
The script I'm currently developing has the potential to store rather big amounts of data in the script storage (few megabytes) but the thing is that the script execution ,which was supposed to @run-at document-start, ( even before any call to GM_getValue) is so delayed that the script runs after the browser page has completed loading ( in this specific case I need to set a variable before a certain script runs)
So the idea would be that if @run-at is that (maybe behind a second flag) to run the script even if the storage loading hasnt finished (though this might require some api changed/addons) I think the most optimal in terms of backwards compatibility would be to have a method that returns if the storage has already completed loading 🤔

**Comment by derjanb** [comment] 2023-07-06 08:20
Please use [instant injection mode](https://github.com/Tampermonkey/tampermonkey/issues/211#issuecomment-317116595).

Duplicate of #211

**Closed by derjanb** 2023-07-06 08:20 UTC
