### ISSUE TITLE
Conflicts in Firefox with  `Always use private browsing mode` 

### ISSUE THREAD

**Issue by suiboli314** [Tampermonkey/tampermonkey#1945] opened 2023-12-17 07:24 UTC
## Expected Behavior

After Install, Enable the Tampermonkey `Run in Private Windows`, while browser has `Always use private browsing mode` Enabled, a greeting of successful install should prompt out and the browser can access any website. Click on Tampermonkey icon, a drop-down menu should display. In the extension settings of tampermonkey, click on option, the browser should load option page. moz-extension://$(Tampermonkey-UUID)/options.html

## Actual Behavior

If browser has `Always use private mode` Enabled, it has no access to any website (keeps loading). The drop-down menu always keeps loading. The option page (moz-extension://$(Tampermonkey-UUID)/options.html) keeps loading as well. 

Disabled Extension, the browser runs properly. 

Happens in both Mac and Windows. Previous version runs without issue in the same environment.

## Specifications

- TM: 5.0.0 (latest)
- Firefox: 120.0.1 (latest)
- Windows 11: 22631.2861 (latest)
- MacOS: 14.2 (latest) (Both Intel and M Chip)

## Script

no userscript enabled.

**Comment by derjanb** [comment] 2023-12-17 18:32
Duplicate of #1921 

A new beta version with the fix is already in review since 2023-12-14. If everything looks good I'll release a new stable version.

**Closed by derjanb** 2023-12-17 18:32 UTC
