### ISSUE TITLE
Google Drive Sign-in Page Keeps Showing

### ISSUE THREAD

**Issue by Xiper-Starchild** [Tampermonkey/tampermonkey#1435] opened 2022-03-09 07:17 UTC
Tampermonkey opens a sign-in page for Google Drive every few times I open Chrome. I don't want to have to sign in every time and would like to disable this; I believe it's related to the cloud backup feature. I've already revoked the access token but that did nothing. Help or pointers would be appreciated.

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

**Comment by joeytwiddle** [comment] 2022-03-16 07:07
It's a long standing issue. Until it is fixed, there is a workaround here: https://github.com/Tampermonkey/tampermonkey/issues/904#issuecomment-630848291 Not ideal, but better than nothing.

**Comment by derjanb** [comment] 2022-03-18 19:21
Duplicate of #1435

**Closed by derjanb** 2022-03-18 19:21 UTC
