### ISSUE TITLE
点击插件面板卡顿，运行时候网络卡顿（更新脚本之前运行正常）

### ISSUE THREAD

**Issue by TonyStark5** [Tampermonkey/tampermonkey#800] opened 2019-11-03 12:03 UTC
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```
点击插件面板卡顿，运行时候网络卡顿（更新脚本之前运行正常）

**Comment by derjanb** [comment] 2019-11-03 12:10
Can you please explain the issue a little bit more in detail? Maybe add a screenshot or a screencast?

**Comment by derjanb** [comment] 2019-12-04 23:38
Duplicate of #801

**Closed by derjanb** 2019-12-04 23:38 UTC
Labels: feedback needed
