### ISSUE TITLE
Tampermonkey Edge can't install a script

### ISSUE THREAD

**Issue by lychichem** [Tampermonkey/tampermonkey#314] opened 2016-09-02 03:16 UTC
Here is the script:[yet another weibo filter](https://greasyfork.org/zh-CN/scripts/3249-yet-another-weibo-filter/code)
It can be installed, but after exit and restart edge this script will disappear. In the worst situation it causes all scripts I installed disappear.
In chrome or Firefox this issue will not happen, I wonder whether this issue is related to Tampermonkey Edge's unsupported API.
Tampermonkey edition: v4.2.5284, Edge edition: Microsoft Edge 38.14393.0.0 (Running on a laptop with Windows 10 14393.105 x64 Pro edition)

**Comment by lychichem** [comment] 2016-09-02 03:38
The author of this script said it may relates to Edge's limition to extension's saved data size, which is smaller than the script's need. So maybe I should post this issue to MS feedback.

**Comment by lychichem** [comment] 2016-09-02 06:28
And when running scripts with attribute "run at document-start", the whole page usually take significantly longer time to load, and sometime even fail to load and the title bar shows "ms-browser-extension://"

**Comment by tophf** [comment] 2016-09-02 06:53
The script uses an extremely slow code in its MutationObserver handler: array filtering with function callback. Plain `for` loops should be used. There are other tricks to speed up observing.

**Comment by tiansh** [comment] 2016-09-02 07:22
Hi @tophf , thank you for your suggestion. Can you explain more detailed about which part cause performance issue? Thank you.

```javascript
  var callbacks = [/* many functions here */];
  var actived = null;
  /* is this part? */
  var act = function () {
    callbacks.forEach(function (c) { c.wrap(); });
  };
  var active = util.func.catched(function (mutation) {
    /* or you mean this `every` function call */
    if (mutation && Array.from(mutation).every(function isDate(x) {
      var target = x.target;
      return target.hasAttribute('date') || target.hasAttribute('yawf-date');
    })) return;

    /* or these code? */
    if (actived === false) actived = true;
    if (actived !== null) return;
    act(); actived = false;
    setTimeout(function () {
      if (actived === true) act(); actived = null;
    }, 100);
  });
  var observe = function () {
    active(); // initial
    (new MutationObserver(active))
      .observe(document.body, { 'childList': true, 'subtree': true });
  };
  if (!('MutationObserver' in window)) observe = function () {
    // for lagency browsers
    document.body.addEventListener("DOMNodeInserted", function (e) { active(); }, false);
    document.body.addEventListener("DOMNodeRemoved", function (e) { active(); }, false);
  };
```

**Comment by derjanb** [comment] 2016-09-02 07:26
> The author of this script said it may relates to Edge's limition to extension's saved data size, which is smaller than the script's need. So maybe I should post this issue to MS feedback.

@lychichem Tampermonkey is already spanning large data over multiple storage keys to workaround the [1MB limit](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/api-support/supported-apis/#storage). So this shouldn't be an root cause. I'll check that.

**Comment by tophf** [comment] 2016-09-02 12:09
>/* or you mean this `every` function call */

Not only this. There's hell of a lot of function calls on each mutation in that code. Some sites may generate thousands of mutations while loading. Function call in JavaScript is an EXTREMELY slow operation compared to a plain code like `if` checks or `for`-loop <sup>[[1]](#note1)</sup>. And `bind`-produced functions are even slower than that. And `try/catch` blocks are even slower (and if you move it out into a new function: hello, function call overhead!). This userscript showcases the slowest methods. 

Mutation Observer that can receive thousands of calls per second should be written almost like C-code or Assembly using plain loops, preemptive checks to cancel further processing, avoid *any* calls to user functions. If done correctly, it should not consume more than 1% of page loading time. However it may require a lot of workarounds and compromises in the code. For example, if the content is outside of visible portion of the window you can postpone observing via `setTimeout(..., 0)` that will be executed when page parsing initial burst of CPU-intensive processing finishes (could take even 1 second). There are many possible tricks one could use.

---

<sup><a name="note1">[1]</a></sup> Well, of course, if the function call is simple (for example it's inside a benchmark-like primitive loop) it's detected by the js engine and optimized but it takes time and it happens too rarely in the real code to rely on it.

**Comment by derjanb** [comment] 2016-09-03 00:30
This should be fixed at [4.2.5294 or higher](http://tampermonkey.net/changelog.php?version=4.2.5294&ext=gz80)

**Comment by tiansh** [comment] 2016-09-03 12:06
> Mutation Observer callback that can receive thousands of calls per second 
So I had limited min delay between two observer callback to 100ms. So there will be no more than 10 calls per second.

> Function call in JavaScript is an EXTREMELY slow operation compared to a plain code 

> And `try/catch` blocks are even slower 

The callbacks are come from many functions while it's almost impossible to inline all these logical to the `act` function. `try/catch` was used in wrap function so that other callbacks still work if some functions failed (maybe due to the changes by the website). I'm not sure if this may be removed.

**Comment by Royalgamer06** [comment] 2016-09-05 13:04
This may be related: https://github.com/Tampermonkey/tampermonkey/issues/317

**Closed** 2016-09-14 06:59 UTC
Labels: bug
