### ISSUE TITLE
Doesn't work with Safari at zhihu.com

### ISSUE THREAD

**Issue by Theoda** [Tampermonkey/tampermonkey#901] opened 2020-04-07 12:22 UTC
Tampermonkey works fine for every website except zhihu.com, for example:
https://www.zhihu.com/search?type=content&q=test
https://www.zhihu.com/question/33573424

No script will work. And I find an error in Console:

```
Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.
```

## Specifications

- Safari: 13.1 (15609.1.20.111.8)
- TM: 4.10.6108
- OS: macOS 10.15.4

## Script

Tested with a very simple script:

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.zhihu.com/search*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    alert("It works!");
})();
```

**Comment by derjanb** [comment] 2020-04-07 13:35
Duplicate of #876 and possibly #296 :-(

**Closed by derjanb** 2020-04-07 13:35 UTC
