### ISSUE TITLE
Please add donation channels for Chinese people

### ISSUE THREAD

**Issue by DFLMJ** [Tampermonkey/tampermonkey#718] opened 2019-05-31 01:53 UTC

**Comment by joeytwiddle** [comment] 2019-05-31 06:59
In #674 the author tried using Alipay but it didn't work out.

@DFLMJ Do you have any recommendations? What channels have you seen other projects using?

**Comment by Robin2233** [comment] 2019-06-05 00:53
@joeytwiddle WeChat Pay

**Comment by DFLMJ** [comment] 2019-06-13 01:02
@joeytwiddle Alipay pay or WeChat pay

**Comment by derjanb** [comment] 2019-07-26 07:49
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/674#issuecomment-479386464

**Closed by derjanb** 2019-07-26 07:49 UTC
