### ISSUE TITLE
[Suggestion] Add folders for userscripts

### ISSUE THREAD

**Issue by bl-dev** [Tampermonkey/tampermonkey#937] opened 2020-05-17 02:08 UTC
This is not an issue, but a suggestion of some sorts.
It would be really nice if you could add folders to manage our userscripts for efficiently.
I have created a lot of scripts, and it would be nice to sort them into different folders.

**Comment by derjanb** [comment] 2020-05-18 18:04
Duplicate of #267 

Please also see my comment for a workaround.

**Closed by derjanb** 2020-05-18 18:04 UTC
