### ISSUE TITLE
Remove header to provide larger text editing area

### ISSUE THREAD

**Issue by Aphexus** [Tampermonkey/tampermonkey#1594] opened 2022-09-12 10:13 UTC
There is a large amount of wasted spaced that is taken up by both the top great header and then the script name. This might not seem like a big deal but when one has a small window or debugging tools open this can take up a significant amount of room unnecessarily. Enable minimizing/removing them, say, with an option as there is no need for them(they serve no real purpose and take up room all the time when almost never used. The tabs for open scripts and options and all that is all that is needed. Alternatively have them removed after, say, 10 seconds after the editor is opened. The script name that is shown that takes up significant info could be removed and the open script name(which is also shown in the tab) could be put next to the "Editor/Settings/Storage" tab with smaller font and icon.

**Comment by derjanb** [comment] 2022-09-19 06:22
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/495#issuecomment-361388615

**Closed by derjanb** 2022-09-19 06:22 UTC
