### ISSUE TITLE
Add a script grouping feature

### ISSUE THREAD

**Issue by mapomatic** [Tampermonkey/tampermonkey#1858] opened 2023-09-27 21:33 UTC
It would be helpful if scripts could be assigned to one or more groups and enabled/disabled en masse.

- Add a list of groups to the TM extension's quick access panel, a method to add/delete them, and a method to assign scripts to a group.

Similar to other group/list UI's:
- If all scripts in a group are enabled, the group's checkbox is checked
- If none of the scripts in a group are enabled, the group's checkbox is unchecked.
- If some of the scripts in a group are enabled, the group's checkbox is a filled in square.
- Clicking the group toggles between all selected / none selected.

**Comment by derjanb** [comment] 2023-11-16 19:32
Duplicate of #267

**Closed by derjanb** 2023-11-16 19:31 UTC
