### ISSUE TITLE
Scripts doesn't work with Firefox since last update (4.16)

### ISSUE THREAD

**Issue by zerah54** [Tampermonkey/tampermonkey#1474] opened 2022-04-08 07:38 UTC
I use two scripts, one is mine and one is made by someone else.
Both doesn't work with Firefox since 4.16.6160, but work well with Chrome with 4.15

## Expected Behavior

I should see some logs in console, and some changes in webpage

## Actual Behavior

Nothing happens. 
Sometimes, the number displayed on Tampermonkey icon becomes crazy (see capture below, I have two scripts but 8 shown on the icon)

## Specifications

- Firefox 99.0

![image](https://user-images.githubusercontent.com/7262531/162387841-5b4c3731-9fbb-4f20-9cd9-c7addab405cd.png)

**Comment by derjanb** [comment] 2022-04-08 07:45
Just to be sure, it doesn't work in version 4.16.6160, right?

**Comment by zerah54** [comment] 2022-04-08 07:46
Yes, sorry, with 4.16.6160

**Comment by zerah54** [comment] 2022-04-08 07:48
Scripts are here: 
https://github.com/zerah54/MyHordesOptimizer/raw/main/Scripts/Tampermonkey/my_hordes_optimizer.user.js
https://d2ne.datw.tf/beta.mhe.user.js

**Comment by derjanb** [comment] 2022-04-08 07:48
OK. Thanks. Can you maybe add a link to the scripts? Does the page console show errors?

**Comment by zerah54** [comment] 2022-04-08 07:56
No, console is empty :(

**Comment by CennoxX** [comment] 2022-04-14 06:29
>  Sometimes, the number displayed on Tampermonkey icon becomes crazy (see capture below, I have two scripts but 8 shown on the icon)

You probably show active script instances. At "Settings" > "Action Menu" set "Icon batch info" to "Unique running scripts" instead of "Running script instances".

**Comment by zerah54** [comment] 2022-04-18 11:38
Thanks for this, the numbers seems to be good now, bug the main issue is still here.

I tried to find solutions, and found that the "extension console" (?) had many errors, which seems to be "too much recursion" so the problem may be the same as here https://github.com/Tampermonkey/tampermonkey/issues/1473 ?

**Comment by derjanb** [comment] 2022-04-19 19:36
> I tried to find solutions, and found that the "extension console" (?) had many errors, which seems to be "too much recursion" so the problem may be the same as here https://github.com/Tampermonkey/tampermonkey/issues/1473 ?

Yes, duplicate of #1473

**Closed by derjanb** 2022-04-19 19:36 UTC
Labels: feedback needed, firefox
