### ISSUE TITLE
feature:foleder functionality request

### ISSUE THREAD

**Issue by AelepantB** [Tampermonkey/tampermonkey#1742] opened 2023-03-20 06:42 UTC
(Please fill out the issue template with your details)

A folder functionality can be added to the installed scripts interface in the admin panel. I now have more than forty scripts, and they are growing at a rate visible to the naked eye. It is too troublesome to sort them out.

Thank you very much!

**Comment by derjanb** [comment] 2023-03-21 08:56
Duplicate of #267

**Closed by derjanb** 2023-03-21 08:56 UTC
