### ISSUE TITLE
I want to pay

### ISSUE THREAD

**Issue by xiaodiao1212** [Tampermonkey/tampermonkey#840] opened 2019-12-18 03:45 UTC
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by xiaodiao1212** [comment] 2019-12-18 03:48
@derjanb I want to pay for it，but you do not have the way for the Chinese. so you know what I mean?

**Comment by derjanb** [comment] 2019-12-18 18:39
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/674#issuecomment-479386464

I'm open to any suggestions how to receive donations from Chinese people with a European bank account.

**Closed by derjanb** 2019-12-18 18:39 UTC
