### ISSUE TITLE
[Firefox] Twitter videos issue

### ISSUE THREAD

**Issue by nydhegg** [Tampermonkey/tampermonkey#352] opened 2017-02-01 15:51 UTC
Almost all videos on Twitter don't playing with Tampermonkey, giving a playback errors and the infinite load. Issue is gone when addon is disabled. Tried refresh browser profile and tampermonkey settings, didn't help  at all.

**Comment by tophf** [comment] 2017-02-01 16:06
Sounds like you have a userscript that does something to the twitter videos.

**Comment by nydhegg** [comment] 2017-02-01 16:11
I've tried to disable scripts or deleting them. Still doesn't help.

**Comment by derjanb** [comment] 2017-02-03 20:22
Will be fixed at the [next Firefox release](http://tampermonkey.net/changelog.php?version=4.3.5393&ext=fire) which already is at the review queue.

**Comment by derjanb** [comment] 2017-02-03 20:23
@nydhegg disabling all (page related) scripts should help. Are you sure, that the issue occurs if all scripts are disabled?

**Comment by nydhegg** [comment] 2017-02-04 13:35
Issue appears even with no scripts installed. Wanted to show how it works for me on the latest firefox with new profile and tampermonkey with no installed scripts.  With enabled tampermonkey - http://i.imgur.com/GsUmSSR.gif. With disabled tampermonkey - http://i.imgur.com/W40ZmnY.gif. 
Hoping for a future addon releases. Sorry for the delayed response and bad englando.

**Comment by derjanb** [comment] 2017-02-04 17:44
@nydhegg OK, I found the issue. Thanks for your help.

**Comment by derjanb** [comment] 2017-02-12 19:37
Queue Position: 81 of 186 :-/

**Comment by nydhegg** [comment] 2017-02-12 20:17
Can you upload new build somewhere?  Dropbox maybe?

**Comment by derjanb** [comment] 2017-02-13 18:23
Queue Position: 64 of 179

I think uploading the new version wouldn't help much. Only the developer version can install it permanently. All other version would disable it at every restart.

**Comment by derjanb** [comment] 2017-02-15 19:19
Queue Position: 54 of 174

I think it time for some advertisement: Folks, please join the [Add-on Reviewer Team](https://wiki.mozilla.org/Add-ons/Reviewers)... 😊

**Comment by derjanb** [comment] 2017-02-17 11:55
Queue Position: 51 of 197

**Comment by derjanb** [comment] 2017-02-18 18:58
Queue Position: 39 of 202

**Comment by derjanb** [comment] 2017-02-21 08:09
Queue Position: 39 of 189 😔

**Comment by derjanb** [comment] 2017-02-26 19:25
12 of 188

**Comment by derjanb** [comment] 2017-03-01 20:15
Queue Position: 7 of 191

**Comment by derjanb** [comment] 2017-03-07 15:48
Queue Position: 5 of 207

**Comment by derjanb** [comment] 2017-03-09 12:57
Queue Position: 5 of 212 😭

**Comment by derjanb** [comment] 2017-03-09 19:33
@Noitidart I've uploaded the current Tampermonkey version more than one moth ago. Do you know what the problem is? Is the AMO review team overloaded or are there only a few people that are able to review extensions like TM? Thanks. 😊

**Comment by Noitidart** [comment] 2017-03-09 20:10
Hi there @derjanb  - very unique way to communicate with the reviewers! Very cool!  <3 Github!

Your addon is actually out of my hands, and into the hands of a senior reviewer. They are nervous about the execution of scripts. I'll get a status update from him.

**Comment by derjanb** [comment] 2017-03-09 21:52
@Noitidart Thanks for looking into this.

@ Nightly/developer version users: you can get an unofficial, but fixed version from here: https://tampermonkey.net/xpi/46544b6d654f61/firefox-5410beta.xpi

**Comment by FatOrangutan** [comment] 2017-03-24 18:21
>I'll get a status update from him.

Gentle poke to @Noitidart :)

**Comment by Noitidart** [comment] 2017-03-24 21:47
Hey @FatOrangutan - the senior reviewer has not taken a look yet and has not given an estimate :( Their plates are real full :( I really apologize for the delay.

**Comment by derjanb** [comment] 2017-04-04 21:36
There now also is a development channel with more recent TM versions. Just visit: https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/
and scroll down to "Development Channel".

**Comment by derjanb** [comment] 2017-04-11 19:54
4.3.5393 was released 🎉 😆

**Closed by derjanb** 2017-04-11 19:54 UTC
Labels: bug, fixed at beta
