### ISSUE TITLE
Userscript fails to use login cookie

### ISSUE THREAD

**Issue by pinkunicorn** [Tampermonkey/tampermonkey#886] opened 2020-03-15 15:50 UTC
## Expected Behavior

Script should use cookie to access logged-in content.

## Actual Behavior

Script claims to not be logged in (the browser is, but the script fails to realize).

## Specifications

- Safari: 13.0.5 (15608.5.11)
- TM: 4.10.6108
- OS: MacOS 10.15.3

## Script

The script I'm using is https://greasyfork.org/en/scripts/9713-geocaching-com-project-gc. The script as such has installed OK and runs, since page modifications are done, but the modifications that require logged-on access to project-gc.com fail. Everything works fine in Chrome, but not in Safari.

**Comment by derjanb** [comment] 2020-03-28 19:28
Duplicate of #786

**Closed by derjanb** 2020-03-28 19:28 UTC
