### ISSUE TITLE
I can't disable some settings

### ISSUE THREAD

**Issue by cleuton4k** [Tampermonkey/tampermonkey#2194] opened 2024-10-08 15:52 UTC
I can't disable some settings like "Hide disabled scripts" and "Enable Userscript Sync" in version 5.3.0, in version 5.3.6213 this doesn't happen.
Vivaldi: 6.9.3447.51
w10

https://github.com/user-attachments/assets/52f6532d-67aa-47df-b942-c6266f835061

**Comment by derjanb** [comment] 2024-10-08 18:25
Duplicate of #2189

A new stable release will be created soon.

**Closed by derjanb** 2024-10-08 18:25 UTC
