### ISSUE TITLE
window.close() does not work on the last tab.

### ISSUE THREAD

**Issue by highspeeder** [Tampermonkey/tampermonkey#1069] opened 2020-11-11 07:25 UTC
(Please fill out the issue template with your details)

## Expected Behavior

Even if there is only one tab, I want to close that tab.

## Actual Behavior

1. open new window
2. go to https://www.google.com/
3. console log shows 'refused to close last tab!'
4. open a new tab (a 2nd tab)
5. go to https://www.google.com/
6. window is closed 

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match https://www.google.com
// @grant window.close
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
    setTimeout(window.close, 4000);
})();
```

**Comment by derjanb** [comment] 2020-11-11 07:29
Duplicate of #919

**Closed by derjanb** 2020-11-11 07:29 UTC
