### ISSUE TITLE
GM_xmlhttpRequest didn't carry cookie

### ISSUE THREAD

**Issue by shenchanran** [Tampermonkey/tampermonkey#2096] opened 2024-06-17 09:38 UTC
Beta version5.2.6198
When GM_xmlhttpRequest request a same-domain URL, the first request carries cookie, but after the server returns a 302 code, it redirects to another URL in the same domain, the cookie becomes empty.
![image](https://github.com/Tampermonkey/tampermonkey/assets/139027913/bc8e1191-d52d-4856-9b92-199a462aa2ae)
![image](https://github.com/Tampermonkey/tampermonkey/assets/139027913/d311ea4f-1bae-411a-8df1-3823aa91957f)

is this a new feature or bug?

**Comment by derjanb** [comment] 2024-06-17 11:30
Thanks for reporting. Duplicate of #2094

**Closed** 2024-06-17 11:31 UTC
