### ISSUE TITLE
TM 5.x regression issues

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#1946] opened 2023-12-18 09:36 UTC
(Please fill out the issue template with your details)

## Expected Behavior / Actual Behavior

v5.0 brings some new issues and keeps some of closed old issues not fixed:

* The editor UI glitch with bookmarks not resolved (bm set by mouse highlighed on line number bar but not jumpable to, bm set by keyboard/menu jumpable to but not visible)
* When saving the source in visual editor, sometimes a new tab is opened asking for confirmation (modify/cancel); it's analogical situation when the same script is externally modified from different tab/different browser + tesla sync; the extra window appears more or less randomly without external interferences to stored code
* Randomly opening new blank tab (https://github.com/Tampermonkey/tampermonkey/issues/1935)

## Specifications

- FF 120.0.1
- TM: 5.0
- OS: Win11/x64

## Script

not related to specific code

**Comment by derjanb** [comment] 2023-12-18 09:40
Duplicate of other issues.

> The editor UI glitch with bookmarks not resolved

See #1654

> When saving the source in visual editor, sometimes a new tab is opened asking for confirmation

See #1932

**Closed by derjanb** 2023-12-18 09:40 UTC
