### ISSUE TITLE
TM is identified as a malicious extension in Opera 95.0.4635.46

### ISSUE THREAD

**Issue by F9y4ng** [Tampermonkey/tampermonkey#1710] opened 2023-02-18 11:16 UTC
TM4.18.1 installed in Chrome Web Store is blacklisted by Opera for extensions.😕 But, why?

![opera](https://user-images.githubusercontent.com/15855068/219857056-8c98bc70-09ca-4e9d-a741-0752a957fb28.png)

**Comment by derjanb** [comment] 2023-02-18 19:06
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/635#issuecomment-452057171 🤷

**Closed by derjanb** 2023-02-18 19:06 UTC
