### ISSUE TITLE
Userscript Sync not working, Safari, DropBox

### ISSUE THREAD

**Issue by marc-guenther** [Tampermonkey/tampermonkey#1784] opened 2023-06-01 20:57 UTC
I use _Userscript Sync_ with _DropBox_. I have two user accounts on my Mac, and on one account it works fine, on the other it simply does not work, whatever I try.

Now I got a new laptop with just one account. There it worked for a while, but then I noticed that it had stopped working (scripts were still there, but not updated anymore). And now I cannot get it to work anymore at all.

**Behaviour**: It just doesn't do anything. No errors, no output, no nothing. When I click on _Run now_ in Settings, it shows the _Please Wait_ animation forever. Same when I click _Reset_.

When I _Restart Tampermonkey_, it shows the blue _Sync is running_ title bar, which stays around for quite a while, and vanishes some time later.

I then did a _Factory Reset_, which was a big mistake, as now **all my scripts are gone**, and still nothing works.

I am also unable to find any information about where to look for **log** files or where the **debug** output is stored. JavaScript Console is completely **empty**. The FAQ describes two more methods, none of these work for Safari on Mac.

I then searched for every file that contains the string "tampermonkey" in my `~/Library` folder, and removed it, restarted everything, enabled Sync again, and still nothing works. At least this time it prompted me for my DropBox credentials, but after successful **login** and granting it **access**, it still didn't do anything.

Searching the internet also did not uncover any useful information.

After spending almost half a day on this problem, I am now completely out of ideas.

----
Safari: Version 16.3 (17614.4.6.11.4, 17614)
MacOS Monterey: 12.6.3 (21G419)
TamperMonkey: v4.17.6162 (would be nice if this version info could be copy/pasted, so I wouldn't have to type it by hand)

**Comment by marc-guenther** [comment] 2023-06-20 10:23
Does someone know, where i could find **log/debug output**? At the moment, it just doesn't work, with no output whatsoever.

**Comment by derjanb** [comment] 2023-06-22 07:34
Please check ~/Library/Containers/net.tampermonkey.SafariApp.Extension/Data/Documents/log.txt.

https://github.com/Tampermonkey/tampermonkey/issues/558#issuecomment-542235500

**Comment by derjanb** [comment] 2023-06-22 07:48
> How do I check logs on Windows? Exact same bug.

http://tmnk.net/faq#Q600 ;)

**Comment by derjanb** [comment] 2023-07-28 15:56
Duplicate of #1391

**Closed by derjanb** 2023-07-28 15:56 UTC
Labels: bug, safari
