### ISSUE TITLE
Tampermonkey print error "TypeError: Cannot read property 'bind' of undefined" on repl.it

### ISSUE THREAD

**Issue by XCanG** [Tampermonkey/tampermonkey#1052] opened 2020-10-10 07:44 UTC
On this page https://repl.it/talk/share/Patatap-Clone/55084 there is HTML console, which print any console output and Tampermonkey throwing error and printed in this console:
```
Tampermonkey sandbox preparation (internal.c_d) failed. This usually is caused by a third-party extension. TypeError: Cannot read property 'bind' of undefined
    at Object.c_d (<anonymous>:5:499)
    at <anonymous>:8:216
    at Array.forEach (<anonymous>)
    at <anonymous>:8:182
    at <anonymous>:10:152
    at <anonymous>:13:47
```
Well this issue need to be fixed and not print in this console.

## Expected Behavior
No error.

## Actual Behavior
Throwing error and printed in console, where it shouldn't be.

## Specifications

- Chromium: 85.0.4183.121
- TM: 4.11
- OS: Windows 10 x64 10.0.18363

**Comment by derjanb** [comment] 2020-10-20 23:05
Please re-try with a new temporary profile. Do you still see the error? 

-> https://www.chromium.org/developers/creating-and-using-profiles

**Comment by XCanG** [comment] 2020-10-22 17:50
Ok, so:
1. I create fresh new profile
2. Install Tampermonkey
3. Import userscript, which work for me on all pages
4. Go to https://repl.it/talk/share/Patatap-Clone/55084
5. Start repl
6. See same error

Additionally I check and disable my global userscript and still see this error.
Important note, that I see it when I click start button ▶️

**Comment by raszpl** [comment] 2020-11-15 05:30
uBo installed and running? usually this ends up being one of uBo scriptlets loading first and stubbing global js functions out

**Comment by XCanG** [comment] 2020-11-16 20:31
@raszpl uBlockOrigin is used as well, yes. However it wasn't used on clear profile. I install only Tampermonkey there. So it confirm that Tampermonkey have problem on it's own and it have nothing to do with uBlockOrigin.

**Comment by raszpl** [comment] 2020-11-16 23:48
cant reproduce, also looked into most common ubo lists and this site is not in them so that wouldnt be it

**Comment by XCanG** [comment] 2020-11-26 11:30
@raszpl do you have any global script, that work everywhere in Tampermonkey? If not, try open with it.

**Comment by raszpl** [comment] 2020-11-26 15:31
I do, but that shouldnt matter.

    Tampermonkey sandbox preparation failed.

is triggered in page.js. Afaik this file is injected before tampermonkey even started checking if any scripts are eligible for execution.

**Comment by derjanb** [comment] 2020-11-26 15:45
> > Important note, that I see it when I click start button arrow_forward
> 
> wait, I didnt even see play button on my normal install (captchas, blocked scripts etc).

That was the "missing" hint... 😅 Thanks for poining it out (again). I can reproduce the problem. Will be fixed at the next beta release.

**Comment by raszpl** [comment] 2020-11-26 16:01
webpack:///./src/shared/console.js

what in the world is that thing? :0 how does it work?
I have most of the stupid shi^functions blocked in my daily driver browser, so wasnt seeing any of it.

**Comment by derjanb** [comment] 2020-12-03 10:50
> ```
> webpack:///./src/shared/console.js
> ```
> 
> what in the world is that thing? :0 how does it work?
> I have most of the stupid shi^functions blocked in my daily driver browser, so wasnt seeing any of it.

They have a source map link somewhere, that's why the debugger tools show an imaginary orginal file.

**Comment by NullDev** [comment] 2021-02-18 20:08
I'm getting the very same problem on repl.it:

```
Tampermonkey sandbox preparation (internal.c_d) failed. This usually is caused by a third-party extension. TypeError: Cannot read property 'bind' of undefined
    at Object.c_d (<anonymous>:5:499)
    at <anonymous>:8:216
    at Array.forEach (<anonymous>)
    at <anonymous>:8:182
    at <anonymous>:10:152
    at <anonymous>:13:47
```

![image](https://user-images.githubusercontent.com/22935000/108415061-487a4700-722d-11eb-9ef1-ec341205b2b4.png)

Also, this is line 64 of `breadcrumbs.js`:

```js
// this fails for some browsers. :(
if (originalConsoleLevel) {
    Function.prototype.apply.call(originalConsoleLevel, global.console, args);
}
```

**Closed** 2021-03-24 19:15 UTC
Labels: bug, fixed at beta

**Comment by UnevenCoder** [comment] 2021-03-25 17:34
Error coming again , what to do ?
