### ISSUE TITLE
Firefox no pages are loading under "Always use private mode" setting. Full browser malfunction.

### ISSUE THREAD

**Issue by halt9k** [Tampermonkey/tampermonkey#1963] opened 2024-01-07 05:40 UTC
Removing  "Always use private mode" fixes the page load issue. 
Disabling Tampermonkey fixes the issue.
The problem is valid even if no userscripts are enabled at all. 
Valid for any sites; for example, www.google.com

## Specifications

- Firefox: 121.0 64-bit
- TM: 5.0.0
- OS: Windows 10

## Script
Any

**Comment by derjanb** [comment] 2024-01-07 18:31
Duplicate of #1921

A new release is already in review...

**Closed by derjanb** 2024-01-07 18:31 UTC
