### ISSUE TITLE
 想不通为什么 作者捐赠方式怎么不添加 微信 或者支付宝

### ISSUE THREAD

**Issue by yangye9398** [Tampermonkey/tampermonkey#746] opened 2019-07-26 07:34 UTC
(Please fill out the issue template with your details)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment] 2019-07-26 07:49
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/674#issuecomment-479386464

**Closed by derjanb** 2019-07-26 07:49 UTC
