### ISSUE TITLE
Tampermonkey + 1Password extensions break Google search in Safari (Sonoma)

### ISSUE THREAD

**Issue by GarthSnyder** [Tampermonkey/tampermonkey#1840] opened 2023-08-19 23:04 UTC
This problem relates to Tampermonkey in Safari specifically.

The problem started today (8/19/2023) after I updated both the 1Password for Safari and Tampermonkey shell apps. I can't point a finger at either app specifically since they both work fine without the other. Both apps are at their current release versions as of today.

The problem is that in Google search result pages, left clicks on search result headings no longer take the browser to those pages. Right clicking and Open in New Tab still works fine, as does Command-clicking.

## Expected Behavior

You can click on any Google search result and be taken to the matching page.

## Actual Behavior

Left clicks on search results do nothing.

## Specifications

- Tampermonkey 4.20.6184 installed from Mac app store
- macOS Sonoma beta 14.0 (23A5312d)
- Safari Version 17.0 (19616.1.26.11.3)
- 1Password for Safari 2.14.0 

The problem is 100% consistent and reproducible, but to reproduce, both the 1Password and Tampermonkey extensions must be enabled in Safari. It is NOT necessary to reload the Google results page after enabling or disabling either extension - the issue seems to relate to the click processing and not the actual page HTML.

It is NOT necessary that any actual Tampermonkey script be running on the Google results page. Just the fact that Tampermonkey is enabled is sufficient to trigger the bug.

Note that Sonoma is a beta version of macOS. I do not know if the problem occurs under the released version of macOS.

**Comment by renssies** [comment] 2023-08-21 22:17
It occurs Ventura as well. Denying 1Password access to Google.com fixed the issue for now... But it of course means I can't use password fill on Google.com.

**Comment by dewey** [comment] 2023-09-02 09:57
Is this related to https://github.com/Tampermonkey/tampermonkey/issues/1836? It seems similar and I just realized I also have 1Password installed.

**Comment by jpmontez** [comment] 2023-09-02 10:34
> Is this related to #1836?

Yes, I receive the same error message in that issue’s screenshot when both 1Password and Tampermonkey are enabled.

**Comment by irandamay** [comment] 2023-09-22 13:59
Just to update some version data, it still also happens with the latest release versions of the following (so it's not something that was resolved by newer versions):
- macOS Ventura 13.6
- Safari 16.6
- 1Password 2.15.1

**Comment by derjanb** [comment] 2023-10-17 19:36
Duplicate of #1836

**Closed by derjanb** 2023-10-17 19:36 UTC
Labels: safari
