### ISSUE TITLE
GM_addStyle breaks XML viewer in Firefox

### ISSUE THREAD

**Issue by eight04** [Tampermonkey/tampermonkey#639] opened 2019-01-22 01:13 UTC
Probably related to https://github.com/Tampermonkey/tampermonkey/issues/452. That thread seems not to be particular to `GM_addStyle` so I opened a new issue.

If you create a script that runs on XML pages and the script uses `GM_addStyle` to inject CSS code, the style element will break XML viewer.

For example:
https://www.w3schools.com/xml/note.xml

[Stylus ended up using browser API to inject CSS code in this situation](https://github.com/openstyles/stylus/issues/232).

## Specifications

- Firefox Dev 65.0b12
- TM: 4.8.5847
- OS: Windows 7

## Script

Any script that uses `GM_addStyle`.

**Comment by derjanb** [comment] 2022-04-22 14:06
Duplicate of #452

**Closed by derjanb** 2022-04-22 14:06 UTC
Labels: firefox
