### ISSUE TITLE
Hope to support query and modify http only cookies.

### ISSUE THREAD

**Issue by monkeyWie** [Tampermonkey/tampermonkey#611] opened 2018-10-10 01:58 UTC
`document.cookie` can't get http only cookie,but using chrome extension API can do.
The doc from:[https://developer.chrome.com/extensions/cookies](https://developer.chrome.com/extensions/cookies),other browsers should also have the same API, I think can add `@grant GM_cookie` API to query and modify cookies.
So what do you think?

**Comment by derjanb** [comment] 2018-10-10 07:03
Duplicate of #465

**Closed by derjanb** 2018-10-10 07:03 UTC

**Comment by monkeyWie** [comment] 2018-10-11 09:51
Thank for your reply, I saw this question,but there is no solution.
