### ISSUE TITLE
Required resources blocked by Trusted-Types CSP

### ISSUE THREAD

**Issue by svArtist** [Tampermonkey/tampermonkey#1334] opened 2021-09-24 23:06 UTC
(Please fill out the issue template with your details)

## Expected Behavior
TM manages to inject required resources

## Actual Behavior
On websites using a strict `Content-Security-Policy: require-trusted-types-for 'script';` / `trusted-types`, injection fails with the unhandled errors:
> This document requires 'TrustedScript' assignment.
> This document requires 'TrustedHTML' assignment.  

(Full log attached)

Test the behavior here: https://benjamin-philipp.com/test-trusted-types.php?defaultPolicy=true

## Specifications

- Chromium: 93.0.4577.82 (Official Build) (64-bit)
- TM: 4.13
- OS: Windows 10

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name		tmp
// @version		1.0.0
// @namespace	bp
// @match		https://benjamin-philipp.com/test-trusted-types.php*
// @require 	http://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js
// @require 	https://benjamin-philipp.com/js/gm/funcs.js?a=b
// @run-at		document-body
// @noframes
// @grant		none
// ==/UserScript==

console.log("With strict TrustedTypes implementation, this UserScript will fail while attempting to load the @requite scripts");
// $("#myElement").html("<p>toast</p>");
```
[benjamin-philipp.com-1632523189216.log](https://github.com/Tampermonkey/tampermonkey/files/7228691/benjamin-philipp.com-1632523189216.log)

**Comment by dev4min** [comment] 2021-09-26 10:18
Same here!

@svArtist if you want a quick fix, this line of code fixed the problem for me:

`window.trustedTypes.createPolicy('default', {createHTML: (string, sink) => string})`

based on the down-voted answer in: [https://stackoverflow.com/questions/61964265/getting-error-this-document-requires-trustedhtml-assignment-in-chrome](https://stackoverflow.com/questions/61964265/getting-error-this-document-requires-trustedhtml-assignment-in-chrome)

**Comment by svArtist** [comment] 2021-09-26 13:18
> @svArtist if you want a quick fix, this line of code fixed the problem for me:
> 
> `window.trustedTypes.createPolicy('default', {createHTML: (string, sink) => string})`

Hi!
That's certainly a good work-around for where it's applicable, but for people looking at this: there are some caveats
- in the case of `@require`s breaking the script, any attempt to do this in the script itself would fail, since TM will already have broken down before it could execute the above. You would have to create a second script (without `@require`s, of course) for this, and make sure it gets executed first.
- This requires that the CSP allows creation of a default policy
  - and that none has been set before
 
Let's hope the masterminds in the TM community can find robust ways of smoothing out the `Trusted-Types` experience.
It would be lovely if they could find a way to leverage browser APIs to circumvent the whole thing if need be. Power to the user! :)

**Comment by svArtist** [comment] 2021-09-27 16:25
For anyone looking for a bandaid-fix in the meantime: I wrote a TT helper.   
https://greasyfork.org/en/scripts/433051-trusted-types-helper

It does its best to enable reckless DOM modification again, and **IF** 

- you make sure to  run it before your other scripts
- the site allows setting a default policy, **and** 
  - either our script gets executed before theirs,
  - or doesn't get overwritten, 

Things should be like before the dreaded TT restrictions.

If we can't set a default policy, we're out of luck for this issue of dependencies breaking TM, but for general DOM manipulation from within scripts that _do_ work, we can try to set a custom policy, it'll be assigned to the variable `TTM`.  
Instead of using things like
`someDomElement.innerHTML += "<div class='myClass'><p>some <b>content</b></p></div>";`
use this approach
```
var e = document.createElement("div");
e.className = "myClass";
e.innerHTML = TTP.createHTML("<p>some <b>content</b></p>");
someDomElement.appendChild(e);
```
(Because it seems that Chrome stable at the moment doesn't even allow appending like `someDomElement.innerHTML += actuallyTrustedHTML`, which is a PITA)

**Comment by derjanb** [comment] 2021-09-27 17:45
Should be fixed at 4.14.6144 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_4_14_6144.crx))

**Comment by 7nik** [comment] 2021-09-27 19:44
> doesn't even allow appending like `someDomElement.innerHTML += actuallyTrustedHTML`

I believe, it unfolds to
```js
someDomElement.innerHTML = someDomElement.innerHTML + actuallyTrustedHTML;
// or, to be more detailed
someDomElement.innerHTML = someDomElement.innerHTML.concat(actuallyTrustedHTML.toString()); 
// that obviously returns a regular "untrusted" string
```

**Comment by svArtist** [comment] 2021-09-27 19:54
> I believe, it unfolds to
> 
> ```js
> someDomElement.innerHTML = someDomElement.innerHTML + actuallyTrustedHTML;
> // or, to be more detailed
> someDomElement.innerHTML = someDomElement.innerHTML.concat(actuallyTrustedHTML.toString()); 
> // that obviously returns a regular "untrusted" string
> ```
Oh, thank you for the insight.
Is that happening in a pre-compiler?
If it's the actual browser engine doing this, it should, IMO, refactor that to acknowledge appending trusted types to trusted contents. I'd hate having to manually create all properties/attributes of each outer element I'd like to add, which I'd have to create separately. Or writing a parser to do that for me o.o

**Comment by 7nik** [comment] 2021-09-27 20:06
`+=` and other assignment shortenings are done in JS. You can check it in the docs: https://262.ecma-international.org/12.0/#sec-assignment-operators-runtime-semantics-evaluation

Also, you shouldn't use `.innerHTML += mycode` because it re-adds all existing HTML as well and it leads to removing all the listeners attached to the re-added elements and breaking all the links to these elements. 
It's better to use [insertAdjacentHTML](https://developer.mozilla.org/ru/docs/Web/API/Element/insertAdjacentHTML):
```js
someDomElement.insertAdjacentHTML("beforeend", mycode);
```

**Comment by svArtist** [comment] 2021-09-27 20:16
Oh yes!! Thank you for reminding me!
I have been spoiled by jQuery and its `.append` for so long, being suddenly thrown back to vanilla JS and the common APIs, I feel a bit like a fish out of water and have to get back in touch with the basics 😅
Thank you so much for your helpful tips 👍

**Closed** 2022-01-28 07:47 UTC
Labels: bug, fixed at beta

**Comment by jshwek** [comment] 2024-06-23 04:48
To elaborate on @dev4min , the additions below allow you to do things like `eval`. As stated by @Black-Platypus , **make sure it's the first `// @require` or it won't work**.

`(function(){
    window.trustedTypes.createPolicy('default', {
        createHTML: (s, sink) => s,
        createScriptURL: (s, type, sink) => s,
        createScript: (s, type, sink) => s,
        emptyScript: (sink) => sink,
    });
})();`

**Comment by raszpl** [comment] 2024-08-07 22:38
Yesterday injected scripts worked fine on youtube.com, today was getting this error on innerHTMLs and evals. Found same stack thread as dev4min, applied same workaround.

**Comment by cyber-sec0** [comment] 2024-08-08 05:12
This solution works only if I don't require any JQuery version. As soon as I remove `// @require            https://code.jquery.com/jquery-3.7.1.js` it works perfectly.

Does anyone have a solution that allows me to require JQuery?

`
// ==UserScript==
// @name               trust test
// @namespace          test
// @description        test
// @version            1
// @author             me
// @include            *
// @icon               https://i.imgur.com/.png
// @resource           test https://i.imgur.com/.gif
// @resource           test2 https://i.imgur.com/.gif
// @grant              GM_registerMenuCommand
// @grant              GM_getResourceText
// @grant              GM.xmlHttpRequest
// @grant              GM_getResourceURL
// @grant              GM_deleteValue
// @grant              GM_openInTab
// @grant              window.close
// @run-at             document-end
// @grant              GM_setValue
// @grant              GM_getValue
// @connect            google.com
// @connect            generativelanguage.googleapis.com
// @require            https://cdnjs.cloudflare.com/ajax/libs/marked/13.0.2/marked.min.js
// @require            https://code.jquery.com/jquery-3.7.1.js
// ==/UserScript==

const BypassTT = window.trustedTypes?.createPolicy('BypassTT', { createHTML: HTML => HTML });
document.body.innerHTML = BypassTT.createHTML('<p>Content added via Trusted Types</p>');
`

**Comment by Black-Platypus** [comment] 2024-08-27 16:12
@derjanb How come we're seeing this issue again? What changed since it was addressed in 4.14?

**Comment by derjanb** [comment] 2024-10-28 19:03
If you need this to relaxed before any `@require` just put this `@require` before all others:

```js
// @require      data:text/plain;base64,d2luZG93LnRydXN0ZWRUeXBlcy5jcmVhdGVQb2xpY3koJ2RlZmF1bHQnLCB7IGNyZWF0ZUhUTUw6IHN0ciA9PiBzdHIsIGNyZWF0ZVNjcmlwdFVSTDogc3RyPT4gc3RyLCBjcmVhdGVTY3JpcHQ6IHN0cj0+IHN0ciB9KTs=
```

**Comment by arminanton** [comment] 2024-12-20 08:17
This one worked best for me, as sometimes the trusted object was not ready yet.
Now it works fine!
```
// @require      data:text/plain;base64,d2luZG93LnRlc3RUcnVzdGVkID0gZnVuY3Rpb24oKSB7CmlmICh0eXBlb2Ygd2luZG93LnRydXN0ZWRUeXBlcyAhPSAidW5kZWZpbmVkIiAmJgogICAoJ3RydXN0ZWRUeXBlcycgaW4gd2luZG93KSAmJgogICAoJ2NyZWF0ZVBvbGljeScgaW4gd2luZG93LnRydXN0ZWRUeXBlcykgJiYKICAgKHR5cGVvZiB3aW5kb3cudHJ1c3RlZFR5cGVzLmNyZWF0ZVBvbGljeSA9PSAiZnVuY3Rpb24iKSkgewoJd2luZG93LnRydXN0ZWRUeXBlcy5jcmVhdGVQb2xpY3koJ2RlZmF1bHQnLCB7Y3JlYXRlU2NyaXB0VVJMOiBzID0+IHMsIGNyZWF0ZVNjcmlwdDogcyA9PiBzLCBjcmVhdGVIVE1MOiBzID0+IHN9KQp9IGVsc2UgewoJc2V0VGltZW91dCh3aW5kb3cudGVzdFRydXN0ZWQsIDEwMDApOwp9Cn0Kd2luZG93LnRlc3RUcnVzdGVkKCk7
```

that is the same as:
```
window.testTrusted = function() {
if (typeof window.trustedTypes != "undefined" &&
   ('trustedTypes' in window) &&
   ('createPolicy' in window.trustedTypes) &&
   (typeof window.trustedTypes.createPolicy == "function")) {
	window.trustedTypes.createPolicy('default', {createScriptURL: s => s, createScript: s => s, createHTML: s => s})
} else {
	setTimeout(window.testTrusted, 1000);
}
}
window.testTrusted();
```

You want to add this as the first require, before your jquery require or other libs.

**Comment by cyber-sec0** [comment] 2025-03-29 07:38
Running into the same issue again!

Last time, I was able to fix it by coding my own solution, which included using innerHTML to add elements, but now I'm trying to use .match, so my previous solution no longer works.

Again, I've tried everything on this page, and nothing worked besides adding the whole content of https://greasyfork.org/en/scripts/433051-trusted-types-helper inside my script, which makes it look terrible since TTH is a long, complex looking script.
I also know another dev that does/did the same thing.

Can't TM just solve this issue, pls?

* Test on https://www.google.com/search?q=A+Brothers+Bond+2024 with https://greasyfork.org/en/scripts/495214 installed

`
// ==UserScript==
// @name         Youtubes
// @namespace    s
// @version      1
// @description  Auto enable the subs.
// @author       s
// @match        https://*.youtube.com/embed/*
// @match        https://www.youtube.com/watch?v=*
// @icon         https://www.youtube.com/s/desktop/03f86491/img/favicon.ico
// @require      https://unpkg.com/tesseract.js/dist/tesseract.min.js
// @run-at       document-end
// @grant        none
// ==/UserScript==

const overwrite_default = false; // If a default policy already exists, it might be best not to overwrite it, but to try and set a custom policy and use it to manually generate trusted types. Try at your own risk
const prefix = GM_info.script.name;
var passThroughFunc = function(string, sink){
	return string; // Anything passing through this function will be returned without change
}
var TTPName = "passthrough";
var TTP_default, TTP = {createHTML: passThroughFunc, createScript: passThroughFunc, createScriptURL: passThroughFunc}; // We can use TTP.createHTML for all our assignments even if we don't need or even have Trusted Types; this should make fallbacks and polyfills easy
var needsTrustedHTML = false;
function doit(){
	try{
		if(typeof window.isSecureContext !== 'undefined' && window.isSecureContext){
			if (window.trustedTypes && window.trustedTypes.createPolicy){
				needsTrustedHTML = true;
				if(trustedTypes.defaultPolicy){
					log("TT Default Policy exists");
					if(overwrite_default)
						TTP = window.trustedTypes.createPolicy("default", TTP);
					else
						TTP = window.trustedTypes.createPolicy(TTPName, TTP); // Is the default policy permissive enough? If it already exists, best not to overwrite it
					TTP_default = trustedTypes.defaultPolicy;
					
					log("Created custom passthrough policy, in case the default policy is too restrictive: Use Policy '" + TTPName + "' in var 'TTP':", TTP);
				}
				else{
					TTP_default = TTP = window.trustedTypes.createPolicy("default", TTP);
				}
				log("Trusted-Type Policies: TTP:", TTP, "TTP_default:", TTP_default);
			}
		}
	}catch(e){
		log(e);
	}
}

function log(...args){
	if("undefined" != typeof(prefix) && !!prefix)
		args = [prefix + ":", ...args];
	if("undefined" != typeof(debugging) && !!debugging)
		args = [...args, new Error().stack.replace(/^\s*(Error|Stack trace):?\n/gi, "").replace(/^([^\n]*\n)/, "\n")];
	console.log(...args);
}

doit();

setTimeout(async function() {
  'use strict';
  var video = document.querySelector('video'); // Select the video element on the page

  video.addEventListener('playing', () => { // When the video is played
    document.querySelector(".ytp-subtitles-button.ytp-button").innerHTML.match('unavailable') === null && document.querySelector(".ytp-subtitles-button.ytp-button").ariaPressed === 'false' ? document.querySelector(".ytp-subtitles-button.ytp-button").click() : ''; // Auto enable the subtitles if available and they are disabled
  }, { once: true }); // Finishes the timeupdate event listener


}(), 1000);
`

**Comment by cyfung1031** [comment] 2025-04-06 23:58
> Again, I've tried everything on this page, and nothing worked besides adding the whole content of https://greasyfork.org/en/scripts/433051-trusted-types-helper inside my script, which makes it look terrible since TTH is a long, complex looking script. I also know another dev that does/did the same thing.


https://greasyfork.org/scripts/522884-default-trusted-types-policy-for-all-pages

this is shorter

**Comment by cyber-sec0** [comment] 2025-04-07 07:17
@cyfung1031 

I can't reproduce the bug with `document.querySelector(".ytp-subtitles-button.ytp-button").innerHTML.match('unavailable') === null` anymore... So I can't test your code, but sometimes the error I'm getting now is `Uncaught (in promise) Uncaught TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': This document requires 'TrustedScriptURL' assignment.`

Maybe I'll test your code later to see if it fixes the `importScripts` error, but even if it doesn't, TM should fix this globally for all devs since not all devs know about this or know how to fix it.

Also, I may be wrong, but I'm starting to think that's related to the CDN server I chose to use or the library itself... I wish I could find out if either of these two is the problem or not, and what specifically besides TT is causing this problem.

**Comment by cyber-sec0** [comment] 2025-04-18 16:51
That worked, but I still wish I didn't have to add "random unnecessary code" to some of my scripts.

The issue is that the library doesn't handle TT, so it breaks on line 1056, `return target.apply(thisArg, args);`

Any solution @derjanb ?
