### ISSUE TITLE
Not working on Safari (App Store version)

### ISSUE THREAD

**Issue by der035** [Tampermonkey/tampermonkey#806] opened 2019-11-13 04:10 UTC
(Please fill out the issue template with your details)

## Expected Behavior
All the scripts should show on and work on the page. 

## Actual Behavior
All the scripts did not show and work but the number of scripts working still  shows on the side of icon. 
![image](https://user-images.githubusercontent.com/42846823/68732493-b8ac1d00-0627-11ea-8ee9-205693900391.png)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment] 2019-11-13 04:58
I need a little bit more details:

* What is your Safari and macOS version?

* Do you see errors at the page's JavaScript console? (Can be opened after [enabling](https://support.apple.com/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac) via Develop>Show JavaScript Console)

* Is it possible to open the options page? If so please enable "anonymous statistics" so that error reports (if any) are sent to me.

* Also, can you please close Safari, backup 
`~/Library/Containers/net.tampermonkey.*`
and then remove these folders by running
`rm -r ~/Library/Containers/net.tampermonkey.*` 
at terminal. Do you see a difference after re-installing the scripts?

**Comment by stapuft** [comment] 2019-11-14 07:28
@derjanb hey, same issues, windows 10, Firefox, I posted a bug report as well, I have the same symptoms this guy has tho.

**Comment by derjanb** [comment] 2019-11-17 13:03
@pilgrim112 Can you please follow these steps -> https://github.com/Tampermonkey/tampermonkey/issues/806#issuecomment-553239532 ?

**Comment by derjanb** [comment] 2019-11-17 13:19
BTW: everything if working fine here... 🙁

![image](https://user-images.githubusercontent.com/767504/69007958-236d9900-0945-11ea-93ee-9b13397c79e3.png)

**Comment by icpz** [comment] 2019-11-28 09:57
I'm experiencing same issue on Safari 13. This issue could be resolved by 'restart tampermonkey' in settings for a while, but it comes back after some time (maybe 1 hour?). I'm afraid that it's caused by some plugin conflicts?
I've installed adguard, 1password and savepocket in the meanwhile... Hope these info helps

**Comment by derjanb** [comment] 2019-11-28 10:22
If a "Tampermonkey restart" helps, then it looks like this is something internal. Can you please do me a favor and enable ["Anonymous statistics"](https://www.tampermonkey.net/privacy.php#extension) at least for a while. If there are internal crashes, then I can get a error report this way. Thanks.

**Comment by icpz** [comment] 2019-11-28 10:26
I've already enabled it since installed. And logging level is set to debug.

BTW where can I read the log of TM?

**Comment by derjanb** [comment] 2019-11-28 10:28
Simply run this at a terminal:

```bash
tail -f Library/Containers/net.tampermonkey.SafariApp.Extension/Data/Documents/log.txt
```

**Comment by icpz** [comment] 2019-11-28 12:11
I found there is only "App started" in that file, at 20 minutes ago(19:50 18th Nov GMT+8).
But the last time I perform restart TM operation is about 2hours ago. It seems that the previous logs are dropped?

**Comment by Eric-Guo** [comment] 2019-12-01 11:12
I also a Safari user, the same issue, just upload my log files for your check. (debug level verbose)

[log.txt.log](https://github.com/Tampermonkey/tampermonkey/files/3908117/log.txt.log)

**Comment by Eric-Guo** [comment] 2019-12-01 11:28
No use to running below command and restart everything.

```bash
cd ~/Library/Containers/
rm -rf net.tampermonkey.SafariApp
rm -rf net.tampermonkey.SafariApp.Extension/
```

**Comment by icpz** [comment] 2019-12-09 16:54
After 3 days of observation, I think that this issue has been resolved in the latest macOS Catalina (19c56a)? But I have no further evidence.

**Comment by Eric-Guo** [comment] 2019-12-10 01:19
Maybe right, at least, I still running Mojave (18G1012) with all update patch.

**Comment by Eric-Guo** [comment] 2019-12-11 01:29
Just upgrade to Safari 13.0.4, no lucky

**Comment by derjanb** [comment] 2020-01-21 19:13
Closing per https://github.com/Tampermonkey/tampermonkey/issues/806#issuecomment-563330607

If you still see the problem, then please create a new issue with some steps how to reproduce the problem. Thanks.

**Closed by derjanb** 2020-01-21 19:13 UTC
Labels: feedback needed, safari
