### ISSUE TITLE
Simple script doesn't work on some websites

### ISSUE THREAD

**Issue by revolter** [Tampermonkey/tampermonkey#876] opened 2020-02-16 20:40 UTC
(Please fill out the issue template with your details)

## Expected Behavior

Work.

## Actual Behavior

Doesn't work.

## Specifications

- Safari: 13.0.4 (15608.4.9.1.3)
- TM: 4.10.6108
- OS: macOS 10.15.2 (19C57)

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://github.com
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    alert("Da");
})();
```

I tried on github.com and dropbox.com and it doesn't work at all. On wikipedia.org, for example, the same simple `alert` works.

**Comment by erosman** [comment] 2020-02-19 14:54
> `@match        https://github.com`

Invalid match patterns: no path
ref: [Match Patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns)

Try 
```
// only top page
 @match        https://github.com/

// all github pages
 @match        https://github.com/*
```

**Comment by revolter** [comment] 2020-02-19 15:53
That's how Tampermonkey generated it when I opened github.com and then used the "Create a new script...". I tried with `https://github.com/` to no avail. Same with `https://github.com/*`.

The thing is that the add-on icon gets correctly badged:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/5748627/74848739-a6393200-5340-11ea-9874-60109b2e1c8f.png">

But not alert shows up. Did it work for you?

**Comment by erosman** [comment] 2020-02-19 16:38
> Did it work for you?

TBH, I was looking for something and I came across your post and replied with what I noticed.
I am afraid I am not a TM user to test it out.
Sorry

**Comment by derjanb** [comment] 2020-02-21 08:05
@revolter Are there console messages regarding a Content Security Policy violation? 
If so, then this is a duplicate of https://github.com/Tampermonkey/tampermonkey/issues/296#issuecomment-222356524

**Comment by revolter** [comment] 2020-02-24 08:54
I don't think so, as it shows

<img width="874" alt="image" src="https://user-images.githubusercontent.com/5748627/75138830-d9d6dc00-56f3-11ea-9585-1654c74d5aeb.png">

regardless of whether the script is enabled or not.

Could you please try yourself to create a script that does anything on github.com and let me know if it works?

**Comment by derjanb** [comment] 2020-07-15 18:29
Duplicate of #296

**Closed by derjanb** 2020-07-15 18:29 UTC
Labels: feedback needed, safari
