### ISSUE TITLE
document.write() breaks GM.registerMenuCommand behavior

### ISSUE THREAD

**Issue by lortonx** [Tampermonkey/tampermonkey#1768] opened 2023-04-22 14:12 UTC
document.write() breaks GM.registerMenuCommand behavior.
about 2 months ago it stopped working properly.

## Expected Behavior
When you click on the menu, the render function should work (and the subsequent opening of the Google page)

## Actual Behavior
Nothing happens when clicking on the option.

## Specifications

- Chromium: Chrome/112.0.0.0
- TM: 4.18.1
- OS: Windows 10

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://*/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        GM.registerMenuCommand
// ==/UserScript==

function registerMenuCommands(){
    GM.registerMenuCommand('Test label', function() {
        alert('hah')
        window.location.href="https://google.com"
    });
}

registerMenuCommands()

document.write('surprise'); // document write breaks GM.registerMenuCommand, try to comment
document.close();

```

thanks.

**Comment by lortonx** [comment] 2023-04-22 14:21
Maybe related to [https://github.com/Tampermonkey/tampermonkey/issues/1760](https://github.com/Tampermonkey/tampermonkey/issues/1760)

**Comment by derjanb** [comment] 2023-04-24 08:28
Yep, duplicate of #1760

**Closed by derjanb** 2023-04-24 08:28 UTC
