### ISSUE TITLE
Can you provide Alipay payment or WeChat payment?

### ISSUE THREAD

**Issue by wolvezb** [Tampermonkey/tampermonkey#728] opened 2019-06-23 09:11 UTC
Thank you very much, I really like this plugin.
I really want to donate
But I am in China
I can't use those payment methods
Can you provide Alipay payment or WeChat payment?
                                                                    - using machine translation

**Comment by derjanb** [comment] 2019-07-26 07:50
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/674#issuecomment-479386464

**Closed by derjanb** 2019-07-26 07:50 UTC
