### ISSUE TITLE
[Firefox] Export to zip/file/cloud not working and breaking FF

### ISSUE THREAD

**Issue by rayman89** [Tampermonkey/tampermonkey#455] opened 2017-10-06 14:50 UTC
When using the export to zip/file/cloud feature there is a loading counter that gets stuck at either 97% or 100% and nothing happens. If I close the tampermonkey tab then firefox breaks not being able to load urls on any tab or open new tabs which requires restarting the browser to fix.

**Comment by derjanb** [comment] 2017-10-06 15:10
What Firefox version do you use?

**Comment by rayman89** [comment] 2017-10-06 15:17
Firefox 56 release

**Comment by rayman89** [comment] 2017-10-08 21:49
I tested disabling all addons but tampermonkey the same issue occurs here is the browser console probably has to do with the number of scripts installed ( I have 44 scripts installed) because I tested on an other profile with 1 script and it worked. 

Here is the browser console log
https://hastebin.com/xowocuduci.pas

**Comment by Keith94** [comment] 2017-10-10 07:30
File export is also broken for me, Tampermoney hangs on "Please wait..." and following error is logged in browser console.

>Unchecked lastError value: Error: filename must not contain illegal characters  ExtensionCommon.jsm:407

Zip and cloud export seems to work fine. I'm using Nightly 58.0a1 and TM 4.5.5570beta (Oct 6, 2017)

**Comment by derjanb** [comment] 2017-10-10 07:33
> Unchecked lastError value: Error: filename must not contain illegal characters ExtensionCommon.jsm:407

This should be fixed at the dev channel.

**Comment by derjanb** [comment] 2017-10-10 11:50
I've tested this with Ubuntu 16.04, Windows 10, MacOS Sierra and FF 56, 57 and 58. I can not reproduce the problems.

> Unchecked lastError value: Error: filename must not contain illegal characters ExtensionCommon.jsm:407

@Keith94 This really should have been fixed since 4.5.5564. Are you sure, you're using a current version? If so, does a file save dialog appear? What is the proposed file name? Also, can you please check the "Download Mode" setting? Does it say "Browser API" or "Default"? What OS do you use?

@rayman89 Save to disk and cloud are working fine here. Can you please do me a favor and try at a new temporary profile?

**Comment by rayman89** [comment] 2017-10-10 15:51
I can confirm is related to the number of scripts installed I tested different amounts of scripts 44, 39, 29,  19 and 1 and all failed except for the 1 and 19 they worked properly. I also tested 20 and it took very long time but at the end it worked.  On my 3rd post I posted the browser and web consoles log.

The test was done on a new clean profile; only tampermonkey installed. Installed 44 random scripts from greasyfork on windows 7 x64 firefox 56 x64 and trying to export file, zip, or cloud all yielded the same result explained before.

**Comment by Keith94** [comment] 2017-10-11 00:16
@derjanb 

>Are you sure, you're using a current version?

I have 4.5.5564 stable installed

>If so, does a file save dialog appear?

No. It says "operation completed" but no save dialog.

>Does it say "Browser API" or "Default"?

Default.

>What OS do you use?

Windows 8 64-bit.

**Comment by rayman89** [comment] 2017-10-17 19:28
I continued testing and If I press on export zip file and leave it for like 10 mins or so without touching anything on firefox the export zip function completes properly but it shoulndt take hat long and make firefox crash if you try to use it IMO.

**Comment by BubiBalboa** [comment] 2017-11-04 23:51
Just want to confirm this bug. FF56.0.2 TM4.5.5584beta as well as the latest regular release. Every export option breaks Firefox.

**Comment by derjanb** [comment] 2017-11-06 19:02
Fixed at [4.5.5590beta](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/versions/beta).

**Comment by rayman89** [comment] 2017-11-07 01:05
Tested works properly.

**Closed** 2017-11-10 08:09 UTC
Labels: bug, fixed at beta
