### ISSUE TITLE
Opera marks Tampermonkey as a "Malicious" extension (False Positive)

### ISSUE THREAD

**Issue by lolSteeeeve** [Tampermonkey/tampermonkey#1135] opened 2021-02-01 16:22 UTC
## Expected Behavior
I wanted to run TM using a Chrome-to-Opera extension _and opera marks it as a Malicious extension_. It was working fine on Chrome but it doesn't seem to work on opera. I tried to find an override  method but opera really did not let me run TM.

## Actual Behavior
It marks TM as malicious (embedded  #image)
![image](https://user-images.githubusercontent.com/37263820/106485469-92ec8b80-64eb-11eb-923d-adedfdb2c5aa.png)

## Specifications

- Chromium: (86.0.4240.198) (Opera GX)
- TM: (v4.11)
- OS: (Windows 10 Pro 64-bit v20H2)

**Comment by derjanb** [comment] 2021-02-02 19:35
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/635#issuecomment-452057171 🤷

**Closed by derjanb** 2021-02-02 19:35 UTC
