### ISSUE TITLE
Please don't close the editor of a new script on save!

### ISSUE THREAD

**Issue by h-h-h-h** [Tampermonkey/tampermonkey#1643] opened 2022-11-13 13:23 UTC
## Expected Behavior

I create a new script from Tampermonkey's fly-out window and skip among tabs during development (e.g., to read documentation). I may or may not save the script in between (in fact, I have auto-save-on-tab-leave on for a while now). When I save the script or come back to its tab after auto-save, I expect to be able to continue development of the script.

## Actual Behavior

Instead, I'm forced to remember the script's name and look through the list of many scripts to find it again, because, irrationally, it was closed.

## Plea

Please make it at least an option to turn auto-close off. And never auto-close on auto-save.

## Specifications

- Firefox Developer Edition 107.0b9 (64-Bit)
- TM: v4.18.0
- OS: Windows 10

## Script

```js
// (not applicable)
```

**Comment by derjanb** [comment] 2022-11-21 09:05
This is a limitation of the current UI. Sorry.

There is a plan to rewrite something modern from scratch, but there are more important issues to be done first (manifest v3, safari web extension, ...)

**Comment by derjanb** [comment] 2024-07-21 18:46
Duplicate of #1149

**Closed by derjanb** 2024-07-21 18:46 UTC
Labels: enhancement, about:editor
