### ISSUE TITLE
Payment problem for how to pay in china 

### ISSUE THREAD

**Issue by zpf996** [Tampermonkey/tampermonkey#869] opened 2020-02-05 14:07 UTC
In China, it is difficult to apply for credit card and pay Pal, we mostly pay by WeChat and alipay, I want to donate to you, but there are no donated credit card and pay Pal, if these two channels are added, I believe that many Chinese users will be very willing to donate to you.

**Comment by derjanb** [comment] 2020-02-10 13:34
Understood. However, I have not found a way to create a WeChat or Alipay account from outside of China and even if, how do I exchange RMB to USD/EUR?

I'm open to any suggestion. :-)

Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/674#issuecomment-479386464

**Closed by derjanb** 2020-02-10 13:34 UTC
