### ISSUE TITLE
Abnormal display

### ISSUE THREAD

**Issue by horaynia** [Tampermonkey/tampermonkey#1870] opened 2023-10-16 13:55 UTC
(Please fill out the issue template with your details)

## Expected Behavior
The same number of scripts and settings, in the Safari browser, click on the icon, the script is not completely displayed, but in the edge browser or chrome browser can correctly and fully display the script. The specific situation is shown in the figure

## Specifications

- Chromium: 118.0.2088.46
- OS: (i.e. MacOS 14)

## Script
<img width="632" alt="iShot_2023-10-16_21 34 59" src="https://github.com/Tampermonkey/tampermonkey/assets/50537627/96eddeef-c0e8-400d-98a8-b85cd5d51e81">
<img width="532" alt="iShot_2023-10-16_21 35 37" src="https://github.com/Tampermonkey/tampermonkey/assets/50537627/13f8acc0-0f0a-48cd-a397-aeecaf53a583">

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment] 2024-06-06 07:10
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/1872

**Closed by derjanb** 2024-06-06 07:10 UTC
Labels: safari
