### ISSUE TITLE
GM_info.userAgentData is still the old version of information after browser update

### ISSUE THREAD

**Issue by Xia0xia0Xia0** [Tampermonkey/tampermonkey#2198] opened 2024-10-11 06:59 UTC
## Actual Behavior
I found that after the browser was updated, the browser version information obtained by GM_info.userAgentData was still the version information before the update. No matter refreshing the page or clearing the browser cache, it could not obtain the latest browser information. I think, this should be a problem on TM cache, please fix it, thank you.

It should be noted that the issue occurred in the 'UserScripts API Dynamic' mode.

## Specifications

- Chromium: 129.0.6668.101
- TM: 5.3.0
- OS: Win 11

**Comment by derjanb** [comment] 2024-10-20 18:57
Duplicate of #2164

**Closed by derjanb** 2024-10-20 18:57 UTC
