### ISSUE TITLE
Enhancement: Reusable JS libraries/code

### ISSUE THREAD

**Issue by dorkerdev** [Tampermonkey/tampermonkey#1534] opened 2022-06-17 20:27 UTC
I have JS helpers that I use in almost all of my userscript files. It's tedious to maintain them because I have to copy and paste helper code changes into all the other files.

A good feature would be local JS libraries that you can reference in your userscripts. Before the scripts are injected into the page, they also pull in the code from the referenced libraries. This way, you don't need to store your scripts on a CDN and you only need to make the code changes in once place.

**Comment by derjanb** [comment] 2022-06-20 07:08
At Chrome you can `@require` libs from file: URLs...

Duplicate of #853

**Closed by derjanb** 2022-06-20 07:08 UTC

**Comment by dorkerdev** [comment] 2022-06-20 16:26
I don't think this issue should have been closed.

Indeed I was finally able to get this to work in Brave by managing the Tampermonkey extension and then setting it to allow local files. However, I don't think this is guaranteed to work on all browsers, especially Firefox from what I've been reading. Some are reporting CORS issues with certain sites.

My solution is different and more elegant. You would add the libraries to Tampermonkey as userscripts like any other. When Tampermonkey load a userscript that require your library userscripts, it merges them in at runtime. Would be quite seamless and would work on all browsers without having to tinker with permission settings.
