### ISSUE TITLE
Better single-page application support

### ISSUE THREAD

**Issue by tukkek** [Tampermonkey/tampermonkey#1639] opened 2022-11-04 05:07 UTC
Many websites today are [single-page applications](https://en.wikipedia.org/wiki/Single-page_application) that leverage [AJAX](https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX) techniques to overcome some limitations when it comes to the performance of the HTTP protocol, designed in 1996 and updated in 2015. While this year's HTTP v3 is being launched and may (or not) make SPAs obsolete, it doesn't change the fact that many of the biggest websites nowadays are developed with this architecture, in an Internet where people are using less and less sites and thus more likely to end up using SPA-based websites.

Many of the top Javascript frameworks today are intended for or support SPAs, including Angular (by Google), React (by Meta/Facebook) and Vue (used by Netflix and many others).

The issue with SPAs from a user-script's point of view, is that, being a single page it doesn't trigger navigation events in the same way as other websites. A script with the correct `@match` value will not load when going from YouTube's homepage to a video's watch-page or similarly from Twitch's homepage to a channel page - they will only load if you access the matched URL directly or reload your browser tab after you've reached the intended page.

The opposite problem is also possible: if you enter a single-page application website and it starts a script, the script will still be running when you surf away from the intended page - even if the second page doesn't match any declared URL in the user-script.

I imagine the same is true for many if not most of the top 10 or 20 most popular websites out there, as they are very likely to leverage AJAX, in the form of SPAs, to improve performance both client- and server-side, thus reducing costs and improving user experience.

It is not hard to write a timer in a site-wide user-script to check if you're in the right page but it's tedious and error-prone, especially when you have to do it on so many cases. The framework for that can often end up being bigger than the intended code in a script.

A good user-script engine shouldn't be oblivious to a scenario so common in the current-day web.and should provide that functionality and awareness in the engine itself, if at all possible.

Another problem is that if you want to support multiple scripts for a single SPA website, you may be tempted to have a single script handle several pages, so that it's easier to trigger and clean-up while navigating - but in doing so, complexity increases as the number of pages affected increases, while the ideal would be to have one script per page regardless of how the website works under the hood.

My initial suggestion, from a user-script developer point of view would be one of these:

1. Add a `@run-at` value named `monitor` which will listen to navigation events and inject a script when a `@match` tag is matched.
2. Add a `@monitor` tag that works like `@match` but will match a direct visit to a page normally but also be aware of navigation and history events, starting a script on those as well.

Both of these maintain compatibility with all existing user-scripts by introducing either a new header or a new header value. Option 1 seems more correct to me as many of the other `run-at` values are meaningless when dealing with AJAX (such as `document-start`) but I think option 2 is probably easier to write scripts for, perhaps.

Ideally Tampermonkey would also kill any scripts after moving away from a page if it no longer matches the given URL. This could be turned off with a `monitor-entry` value, for example, if only entering (and launching scripts) is wanted but not when leaving pages (and stopping a script). If this is supported, a script should probably not be launched a second time when entering a page if it's already on.

This is not a major issue, as explained above it's easy to work around either by writing some extra code in a script or by manually reloading a page after some navigation within a website - it is however, the only thing I find annoying both as a user-script end-user and developer, so I thought I'd write an issue here about it! I'm a huge fan of Tampermonkey, use it all the time - thank you all for it!

**Comment by derjanb** [comment] 2022-11-10 10:31
Duplicate of #584

> Add a @run-at value named monitor which will listen to navigation events and inject a script when a @match tag is matched.

What should Tampermonkey do if the script was injected before? Inject again or assume the script now handles URL changes?
The best solution is to make the script run at all URLs and allow it to listen for URL changes to decide whether an action is necessary. Tampermonkey provides `window.onurlchange` [support](http://tmnk.net/documentation.php#_grant) for this.

**Closed by derjanb** 2022-11-10 10:31 UTC

**Comment by vastris** [comment] 2023-10-10 10:08
Thanks for the detailed insights! The challenges posed by [single page vs multi page](https://www.cleveroad.com/blog/single-page-app-vs-multi-page-application-what-to-choose/) architectures in the context of user-script development are indeed noteworthy. Your suggestions, especially the idea of a @monitor tag to handle navigation events, seem like valuable additions that could enhance Tampermonkey's compatibility with modern web structures.

**Comment by mqliutie** [comment] 2024-03-25 06:38
@derjanb  
```
@grant window.onurlchange

if (window.onurlchange === null) {
    // feature is supported
    window.addEventListener('urlchange', (info) => {
        console.log('url changed')
    });
}
```
`url changed` never be shown on the devtool
