### ISSUE TITLE
GM_xmlhttpRequest wrong contenttype for parsing HTML

### ISSUE THREAD

**Issue by trumpeta** [Tampermonkey/tampermonkey#1239] opened 2021-05-12 21:58 UTC
(Please fill out the issue template with your details)

## Expected Behavior
see remarks under script

## Actual Behavior
undefined .responseText
undefined .response
(but .responseXML contains nonempty object)

`TypeError: DOMParser.parseFromString: 'text/html; charset=UTF-8' (value of argument 2) is not a valid value for enumeration SupportedType`

## Specifications

- Chrome 90.0.4430.212
- TM: 4.12
- OS: Win8.1/x64

## Script

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match *
// @include *
// @connect www.google.com
// @grant GM_xmlhttpRequest
// ==/UserScript==

GM_xmlhttpRequest({
	method: 'GET',
	url: 'https://www.google.com/',
	responseType: 'document', // <======= wrong
	onload: function(response) {
		console.log('.responseText:', response.responseText);
		console.log('.response:', response.response);
		console.log('.responseXML:', response.responseXML);
	},
});
```

The problem with void response if responseType is set to "document" introduced in TM v4.12 (only in Chrome),, due to unhandled exception skipping all further response handling,,, while in FF Legacy and Opera (TM 4.11) .response returns a valid object of HTMLDocument type. 
Other response types ("html", "text/html") aren't recognized, I expect "document" is the only valid string for HTML pages.

The debug warning
> GET: TypeError: DOMParser.parseFromString: 'text/html; charset=UTF-8' (value of argument 2) is not a valid value for enumeration SupportedType.

indicates that GM_xmlhttpRequest uses DOMParser.parseFromString(responseText, contentType) function, where contentType is not "text/html", but "text/html; charset=UTF-8", I suppose it's the extracted Content-Type value from response headers. As the debug warning says parseFromString() doesn't understand the long form for contenttype. Observed in Chrome latest and FF latest (TM 4.13) too (FF returns valid .responseText at least). 

![screen](https://user-images.githubusercontent.com/4992576/118084884-bfa12080-b3c1-11eb-9730-dfef55e4ed21.png)

What is the proper value of .responseType for HTML content then, or is it persisting bug?

**Comment by derjanb** [comment] 2021-05-13 12:04
Duplicate of #1000 

This issue should be fixed at the latest beta.

**Closed by derjanb** 2021-05-13 12:04 UTC
