### ISSUE TITLE
Please make it no longer necessary to use Developer

### ISSUE THREAD

**Issue by GhostHunter94R** [Tampermonkey/tampermonkey#2122] opened 2024-07-12 03:09 UTC
Alright, I am sick and tired of this unwanted/unasked for changes being forced upon us.
I am calling upon the developer to rollback this stupid reasonless change and make it no longer necessary to use Developer Mode to use apps on Tampermonkey.

Anybody who argues against this will be ignored, Because refusal and LYING is NOT an option.

If i do not see this change reversed within a week, I will start a petition to make it happen.
Or perhaps even have this stupid useless app terminated.

Am i clear on this?
Roll it back ASAP. Thanks.

**Comment by derjanb** [comment] 2024-07-12 04:11
Duplicate of #2018

**Closed by derjanb** 2024-07-12 04:11 UTC
