### ISSUE TITLE
add a delete function

### ISSUE THREAD

**Issue by wadawada** [Tampermonkey/tampermonkey#1014] opened 2020-08-11 04:56 UTC
Feature request to delete a (new) script easily

## Current Behavior for deletion
1. click on TM icon
2. scroll all the way down to Dashboard
3. click on Dashboard
4. click on #
5. click on delete icon on the right
6. click OK to "Do you really want to delete 'script name'?"

## Expected New Behavior with Improvement for deletion
1. click on TM icon
2. click on + on the right of a script (only scripts that matches current website appear in list)
3. click on "delete this script" (new)
6. click OK to "Do you really want to delete 'script name'?"

## Advantages for this change
1. this new feature is very useful to test for new scripts
2. very helpful for debugging with unexpected updated scripts
3. Save a lot of time to delete broken scripts without disabling first and then go to dashboard and repeat

**Comment by WHUT-XGP** [comment] 2020-08-16 02:16
2333，I also think deleting scripts is cumbersome now

**Comment by derjanb** [comment] 2020-09-15 10:17
Duplicate of #547

**Closed by derjanb** 2020-09-15 10:17 UTC

**Comment by derjanb** [comment] 2020-12-30 22:19
FYI: https://github.com/Tampermonkey/tampermonkey/issues/547#issuecomment-752775160 😅
