### ISSUE TITLE
Problem loading scripts on twitter

### ISSUE THREAD

**Issue by zevelorgani** [Tampermonkey/tampermonkey#1638] opened 2022-11-02 19:50 UTC
No scripts seem to get loaded on twitter pages until I hit CTRL-F5 on the page

It is kind of hard to reproduce as the problem seems to come and go.
Sometimes, disabling uBO fixes it, other times cleaning the cache makes it work for some time.

Right now, when I open a page on twitter, no scrips are loaded,
When I refresh the page with F5, nothing changes.
When I refresh the page with CTRL-F5, the scripts load.
When I duplicate the tab, the scripts are not loaded on the new tab (until I hit F5)

## Specifications

- Firefox 107
- TM: 4.19.6171
- OS: Windows 10

## Script

Tried with these scripts:
* http://furyutei.github.io/twMediaDownloader/src/js/main_react.user.js
* https://greasyfork.org/scripts/437359-twitter-hide-content-warning-crap/code/Twitter%20hide%20content%20warning%20crap.user.js
* https://greasyfork.org/scripts/445650-twitter-remove-content-warning/code/Twitter%20Remove%20Content%20Warning.user.js

**Comment by zevelorgani** [comment] 2022-11-02 19:51
May be similar to #1634 since it seems to go away if I disable uBO

**Comment by derjanb** [comment] 2022-11-05 15:55
OK. From the description it looks more like a duplicate of #1632.

**Closed by derjanb** 2022-11-05 15:55 UTC
