### ISSUE TITLE
Userscript Sync no longer works with Safari

### ISSUE THREAD

**Issue by lawrence-m** [Tampermonkey/tampermonkey#1391] opened 2021-12-18 05:33 UTC
I recently set up a new Mac with a fresh install of macOS. When attempting to enable Userscript Sync in Tampermonkey, a new tab will open to log in to a cloud service and approve Tampermonkey, and the page will redirect to `https://auth.tampermonkey.net/oauth.php?access_token=...`. Within the Tampermonkey settings, the "Sync is running" banner will be displayed, but nothing will sync. This occurs with Dropbox and Google Drive, and on multiple Macs.

## Specifications
Safari 15.2
macOS Monterey 12.1

**Comment by patrickrushton** [comment] 2022-01-08 13:50
I'm experiencing this too after a clean install of Monterey. Additionally, every time I start Safari, I'm taken to the Dropbox login page.

I seem to remember that getting sync working first time was always a bit hit and miss (back when using Mojave), but after doing a fresh install I can't get it working at all.

**Comment by llity** [comment] 2022-02-21 02:55
It isn't work for me.

**Comment by derjanb** [comment] 2022-05-25 07:13
Can you please check whether it is working after authenticating via "Utilities > Cloud > Show Backups"? Thanks.

**Comment by patrickrushton** [comment] 2022-05-25 07:42
In my case "Utilities > Cloud > Show Backups" opens a new tab with a blank page

https://auth.tampermonkey.net/oauth.php?access_token=etc...

**Comment by lawrence-m** [comment] 2022-05-25 11:06
> Can you please check whether it is working after authenticating via "Utilities > Cloud > Show Backups"? Thanks.

I see the typical Google account selection form. After selecting an account, I get the same blank auth.tampermonkey.net page.

**Comment by derjanb** [comment] 2022-05-25 13:08
And if you reload the blank page and then the settings page and try again? I've seen the issue yesterday once and reload both pages made it work. I think the problem is somewhere in the tab update handling, which sometimes doesn't seem to work. :-/

**Comment by derjanb** [comment] 2022-05-25 13:33
Safari has Google Drive and Onedrive enabled only...

**Comment by lawrence-m** [comment] 2022-05-25 13:34
Refreshing the auth.tampermonkey.net page and the Tampermonkey settings page does allow Google Drive backups to work. The same method doesn't work for Dropbox sync.

**Comment by llity** [comment] 2022-05-25 13:35
It's work now. but there needs login dropbox many times.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/11771112/170274992-68104320-8f41-4eff-9d1c-f0ed5813f4b3.png">

**Comment by llity** [comment] 2022-05-26 04:49
I have more than 100+ scripts, it cannot display all of these scripts!

**Comment by tshu-w** [comment] 2023-01-28 13:46
> And if you reload the blank page and then the settings page and try again? I've seen the issue yesterday once and reload both pages made it work. I think the problem is somewhere in the tab update handling, which sometimes doesn't seem to work. :-/

I tried all night but still failed.

**Comment by quarkquartet** [comment] 2023-06-22 16:58
Same here. Always guides me to the authentication blank page and stuck at "sync is running". This authentication page jumps out every time I try to open a website.
macOS 13.4 and Safari 16.5.

**Comment by marc-guenther** [comment] 2023-07-31 08:52
So is this a bug/problem with TamperMonkey / Safari, or is there something we can do on our side to make this work? Do you need some more info from us to fix this? Or is it just Apple breaking stuff again, and no chance on getting a fix?

**Comment by derjanb** [comment] 2023-08-01 07:23
Should be fixed at 4.20.6184 which is currently rolled out. Thanks for reporting.

**Closed by derjanb** 2023-08-01 07:23 UTC
Labels: bug, safari
