### ISSUE TITLE
[Chrome] GM_download fails silently if the extension download permission is not granted

### ISSUE THREAD

**Issue by DieterHolvoet** [Tampermonkey/tampermonkey#528] opened 2018-03-24 13:49 UTC
Instead of calling the onerror callback, the function fails silently. Can be fixed by changing the `Download Mode` setting to `Browser API` and granting the permission. At that point, even by switching back to `Native` or `Default`, the download function works.

### Example script
```js
// ==UserScript==
// @name         test script
// @match        https://github.com/
// @grant        GM_download
// ==/UserScript==

var dlObject = GM_download({
    url: "http://ipv4.download.thinkbroadband.com/5MB.zip",
    name: "test.zip",
    onerror: function (error) {
        console.log(error);
    }
});
```

**Comment by tophf** [comment] 2018-03-24 13:59
Might be caused by a recent regression in Chrome, see https://crbug.com/821219 (fixed in Chrome 67).

**Comment by derjanb** [comment] 2018-06-07 14:53
@DieterHolvoet Unfortunately this is not possible if "Download Mode" is set to "Default" or "Native". As you already found out, the workaround is to use "Browser API".

https://github.com/eligrey/FileSaver.js/issues/126

**Closed by derjanb** 2018-06-07 14:53 UTC
