### ISSUE TITLE
Tampermonkey does not recognise async and await and reports syntax error

### ISSUE THREAD

**Issue by TempUserWenly** [Tampermonkey/tampermonkey#542] opened 2018-05-20 05:24 UTC
I am using a version of 4.5. A example of code like this will contain syntax error (but still runnable).
```javascript
// ==UserScript==
// @name         Test
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://*/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    function resolveAfter2Seconds(x) {
        return new Promise(resolve => {
            setTimeout(() => {
                resolve(x);
            }, 2000);
        });
    }

    async function f1() {
        var x = await resolveAfter2Seconds(10);
        console.log(x); // 10
    }
    f1();
    // Your code here...
})();
```
This piece of code can still run though the red dots are annoying and misleading. Did I miss something or some kind of setup? Or is it simply a bug?

**Comment by tophf** [comment] 2018-05-20 07:57
Duplicate of #519.

**Closed** 2018-05-20 08:40 UTC
