### ISSUE TITLE
App icon of macOS version shows red badge on every login

### ISSUE THREAD

**Issue by i0ntempest** [Tampermonkey/tampermonkey#1412] opened 2022-02-09 06:45 UTC
(Please fill out the issue template with your details)

## Expected Behavior
No badge should be shown if there's nothing needs my attention 

## Actual Behavior
On every login, inside launchpad, Tampermonkey app shows a red badge at the corner. Opening the app will make it go away but it will reappear on the next login.

## Specifications

- Safari 15.4
- TM: 4.13.6140
- OS: macOS 12.2

**Comment by derjanb** [comment] 2022-04-22 06:14
Duplicate of #1336

**Comment by i0ntempest** [comment] 2022-04-22 06:21
That issue is about the badge on the toolbar icon inside a browser, I’m talking about the badge of the macOS app inside launchpad. Doesn’t look like a duplicate to me.

**Comment by derjanb** [comment] 2022-04-22 06:25
Got it. Thanks.

**Comment by derjanb** [comment] 2023-08-01 07:22
I already create the notification with the option to not show a badge, but it is shown nonetheless. So this is most likely a MacOS/App extension issue. Sorry.

**Closed by derjanb** 2023-08-01 07:22 UTC
Labels: bug, safari
