### ISSUE TITLE
Can't save Options in Tampermonkey

### ISSUE THREAD

**Issue by Machou** [Tampermonkey/tampermonkey#1470] opened 2022-04-04 23:18 UTC
## Expected Behavior

Hello,

When I want to save configuration options in Tampermonkey, nothing happens and no changes are supported.

No error message.

## Specifications

- Firefox: 98.0.2
- TM: 4.15.6154
- OS: Windows 10 fr_FR

![](https://i.ibb.co/88mrn0N/Sans-titre.png)

**Comment by joeytwiddle** [comment] 2022-04-05 00:52
Similar here

- Changing `General > Auto reload pages` works

- But if I try to change `Appearance > Layout` or `Action Menu > Columns` or `Userscript Sync > Enable Userscript Sync` and hit `Save` then on reload, the settings are back how they were, unchanged

**Comment by cweijan** [comment] 2022-04-05 04:10
I have this problem too, I need to customize the css, but the changes are not getting saved.

**Comment by derjanb** [comment] 2022-04-05 07:20
Duplicate of #1438 
A new stable version will be released soon. Sorry for any inconvenience.

**Closed by derjanb** 2022-04-05 07:20 UTC
