### ISSUE TITLE
userscript not running on iframes

### ISSUE THREAD

**Issue by her34** [Tampermonkey/tampermonkey#1775] opened 2023-05-10 14:13 UTC
Scripts seem to not run on iframes.

For example on this webpage the video is playing inside iframe and userscript doesn't run inside that iframe

[https://ktla.com/news/local-news/video-captures-fatal-south-l-a-hit-and-run-suspect-remains-at-large/](url)

Windows
Google chrome
Tampermonkey Version 4.18.1

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @author       You
// @match        http://*/*
// @include      *
// @include      about:blank
// ==/UserScript==

(function() {
    'use strict';

    console.log(location.href);
})();
```

**Comment by derjanb** [comment] 2023-05-10 18:34
Because this is a blank iframe.
You can access it's content for example this way

```
document.querySelectorAll('iframe#p115')[0].contentWindow.anvatoPlayerJSONLoaded
```

Duplicate of #312

**Closed by derjanb** 2023-05-10 18:34 UTC
