### ISSUE TITLE
[Firefox] I can't change theme (Appearance/Layout) since the latest update

### ISSUE THREAD

**Issue by Epyxoid** [Tampermonkey/tampermonkey#1440] opened 2022-03-11 09:14 UTC
## Expected Behavior
Before the update I could manually change the theme between light (Default) and dark (Default - Dark), by simply picking it from the drop-down list and clicking the save button.

## Actual Behavior
After the update the layout stuck in Default - Dark. If I select any other option then press Save, the page refreshes, but everything remains the same and the option is back on Default - Dark.

## Specifications
- Firefox: latest (i.e. 98.0 (64-bit))
- TM: latest (i.e. 4.15.6154)
- OS: latest (i.e. Windows 10 Pro 21H1 19043.1586)

**Comment by derjanb** [comment] 2022-03-11 09:17
Duplicate of #1438 

Sorry for any inconvenience.

**Closed by derjanb** 2022-03-11 09:17 UTC
