### ISSUE TITLE
Tampermonkey stops working in Kiwi browser

### ISSUE THREAD

**Issue by trmdi** [Tampermonkey/tampermonkey#2200] opened 2024-10-16 00:45 UTC
After the recent update of Tampermonkey to 5.3.1, I enabled Development mode as instructed but it still stops working in Kiwi Browser 124.0.6327.4. Tampermonkey runs but scripts don't.

**Comment by vitoo** [comment] 2024-10-17 21:10
Use the legacy version in Kiwi browser, it works better

**Comment by derjanb** [comment] 2024-10-18 11:40
Duplicate of #2055

Sorry for any inconvenience

**Closed by derjanb** 2024-10-18 11:40 UTC
