### ISSUE TITLE
[Bug?] Scripts Editor Rendered Unusable

### ISSUE THREAD

**Issue by Jack1789** [Tampermonkey/tampermonkey#998] opened 2020-07-14 01:30 UTC
## Expected Behavior

Editing scripts or create new ones normally.

## Actual Behavior

The script editor window gets loaded, but no text can be introduced, as shown here:

![tm](https://user-images.githubusercontent.com/54497604/87369948-1b0f4180-c558-11ea-93ad-8c249457bb37.png)

It used to work a few versions ago.

## Specifications

- Firefox: 52.9.0
- TM: 4.11.614
- OS: Windows 10.

## Script

NA

**Comment by derjanb** [comment] 2020-07-14 15:26
Duplicate of #833 (which includes a workarround)

**Closed by derjanb** 2020-07-14 15:26 UTC
