### ISSUE TITLE
GM_openInTab message channel

### ISSUE THREAD

**Issue by jonnytest1** [Tampermonkey/tampermonkey#1948] opened 2023-12-21 00:18 UTC
(Please fill out the issue template with your details)

## Expected Behavior
when using GM_openInTab there should be a way to exchange messages with the newly opened tab

## Actual Behavior
doesnt seem possible (ive been thinking of using GM_caluechangelistener but tampermonkey doesnt seem to work on data: urls)

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==/UserScript==

function inFrame(){
    //send messages back and forth
    debugger;
}

const html=`<h1>head</h1><script>(${inFrame})()</script>`
const htmlBobl=new Blob([html], {type: "text/html"})


GM_registerMenuCommand('cmd',()=>{
    const devToolsUrl=URL.createObjectURL(htmlBobl);
    
    GM_openInTab(devToolsUrl);
})
```

**Comment by SedapnyaTidur** [comment] 2024-02-03 20:50
Yeah, a feature that I'd like to see in the futures. I'd suggest making a blank html file that can run a userscript for example:
```
moz-extension://05d47d2a-f507-4f77-a5e8-ca14a5b99e05/blank.html
```
That can access `window.opener`, and use `@require`s.
There are userscripts that don't need to inject anything into the current page - showing network statistics, debuggers, calculators, color pickers or even games for that matter.
This way, when a user reloads the page, the userscript can run ASAP.

**Comment by derjanb** [comment] 2024-02-15 10:22
> when using GM_openInTab there should be a way to exchange messages with the newly opened tab

[`GM_tabs`](https://tmnk.net/docs#api:GM_getTabs) and `GM_addValueChangeListener` can be used for this. I don't see a way to inject arbitrary code into the newly created tabs without running the whole userscript.

> tampermonkey doesnt seem to work on data: urls 

Duplicate of #312

**Closed by derjanb** 2024-02-15 10:22 UTC
