### ISSUE TITLE
Feature Request: Script customization by folder

### ISSUE THREAD

**Issue by Cyberavater** [Tampermonkey/tampermonkey#681] opened 2019-04-14 20:41 UTC
It'd be nice if I could customize scripts to different folders according to their usage.

**Comment by Cyberavater** [comment] 2019-05-16 02:47
The dashboard looks really messy when you have a lot of scripts and it's really hard to manage them making the dashboard useless.

**Comment by derjanb** [comment] 2019-05-29 18:26
A workaround for the moment is to add tags like "#myfavoritescript" at each script's comment section and then to search the scripts via Ctrl+F and "#myfavoritescript".

**Comment by Cyberavater** [comment] 2019-05-30 01:08
https://github.com/violentmonkey/violentmonkey/issues/287

**Comment by Cyberavater** [comment] 2019-05-30 01:19
That would do, I guess. My target is grouping them. If I can group them by different 'Tags' (which I can name myself) Tags ill do just fine. It'd look nice to see the 'Tag(s)' on the *group* title rather than having it separately on each script of the same group.

**Comment by derjanb** [comment] 2024-07-21 18:54
Duplicate of #267

**Closed by derjanb** 2024-07-21 18:54 UTC
Labels: enhancement
