### ISSUE TITLE
Scripts fail on FF because of CSP errors

### ISSUE THREAD

**Issue by alexolog** [Tampermonkey/tampermonkey#952] opened 2020-05-29 19:02 UTC
Scripts fail to operate and console shows CSP errors

## Expected Behavior

Scripts work.

## Actual Behavior

Scripts fail.

## Specifications

- Firefox developer edition 77.0b9 (64-bit) [Firefox Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0]
- TM beta v4.10.6112
- OS: Windows 10 1903

## Script

(Please give an example of the script if applicable.)

https://greasyfork.org/en/scripts/401432-google-image-search-show-image-dimensions
https://greasyfork.org/en/scripts/398189-google-image-direct-view

Test on: https://www.google.com/search?tbm=isch&q=cat&tbs=imgo:1

**Comment by alexolog** [comment] 2020-05-29 19:16
Some of the scripts I tested run OK on Greasemonkey or Violentmonkey

**Comment by alexolog** [comment] 2020-06-01 15:40
The same as #700 ?

**Comment by derjanb** [comment] 2020-06-02 17:49
Can you please check whether this works with the experimental options "Add Tampermonkey to the site's content CSP" enabled. Thanks.

![image](https://user-images.githubusercontent.com/767504/83552459-1b083480-a50a-11ea-8587-53303370dac5.png)

**Comment by alexolog** [comment] 2020-06-02 18:07
1) Doesn't help
2) Breaks the page (https://www.google.com/search?tbm=isch&q=cat&tbs=imgo:1)

**Comment by derjanb** [comment] 2020-06-03 18:17
I've published Tampermonkey BETA 4.11.6113 with a new option at the **"Modify existing content security policy (CSP) headers"**  setting which is called **"Remove entirely (possibly unsecure)"** to workaround the issue.
The default value is still "Yes", which should relax the CSP to make Tampermonkey work, but since FF 77 setting a new CSP has no effect anymore, while removing works fine. 
This modification is done only if scripts are supposed to run, so there is no need to disable CSP via `security.csp.enable` in general anymore.

You can get the beta version from here: https://www.tampermonkey.net/index.php?browser=firefox

Note: "Config Mode" needs to be set to "Advanced" first.

![image](https://user-images.githubusercontent.com/767504/83672419-83bce300-a5d6-11ea-8808-ca8da1356506.png)

**Comment by Bl4Cc4t** [comment] 2020-06-03 19:27
This is a neat feature! However, I have trouble setting this option, it does not save the selected option for some reason.

**Comment by derjanb** [comment] 2020-06-03 19:42
Just to be sure, you pressed the save button at the bottom of the section? 🥺

**Comment by Bl4Cc4t** [comment] 2020-06-03 19:47
Oh, I did completely overlook those, sorry about that.
The experimental section does not have that, so I thought the other sections automatically save changes too :V

Although with it actually being set, it does not seem to work on twitter.com for me...

**Comment by derjanb** [comment] 2020-06-03 20:24
Your twitter issue is most likely caused by #773

**Comment by Bl4Cc4t** [comment] 2020-06-03 20:31
Yeah, setting `dom.caches.enabled` fixes it.

I guess I have to stick with disabling `security.csp.enable` for now. 
Thank you nonetheless!

**Comment by alexolog** [comment] 2020-06-03 22:17
Works on google.com for me.

Still, questions remain:

> but since FF 77 setting a new CSP has no effect anymore, while removing works fine.

According to [the blog](https://blog.mozilla.org/addons/2020/05/28/extensions-in-firefox-77/), "we now properly merge the CSP headers when two add-ons modify them via webRequest. This is especially important for content blockers leveraging the CSP to block resources such as scripts and images."

If it is not working correctly, maybe need to let Mozilla know?

**Comment by vaporwave9** [comment] 2020-06-04 07:33
> 
> This modification is done only if scripts are supposed to run, so there is no need to disable CSP via `security.csp.enable` in general anymore.
> 
> ![image](https://user-images.githubusercontent.com/767504/83672419-83bce300-a5d6-11ea-8808-ca8da1356506.png)

Yes this worked well on Twitter for me after hitting "Save" in Advanced > Security.
However, can you implement a whitelist instead? It would be neat to have a simple TextArea field to define otherwise broken sites like *.twitter.com/* and thus preventing the settings from being applied globally.
Disabling CSP entirely or removing it on every site is not a good idea.

Thanks anyway, I have a feeling you'll solve the problem eventually! (How does Violentmonkey handle this anyways?)

**Comment by alexolog** [comment] 2020-06-04 13:06
Some of the scripts I tested seem to work with GreaseMonkey without issues:

https://greasyfork.org/en/scripts/401432-google-image-search-show-image-dimensions
https://greasyfork.org/en/scripts/398802-google-images-direct-links-2
https://greasyfork.org/en/scripts/398189-google-image-direct-view

Since GM's latest release was a year ago, whatever it is doing did was not affected by the CSP change.  Maybe @derjanb can snoop in [the code](https://github.com/greasemonkey/greasemonkey) (MIT license) to see what it does differently.

**Comment by alexolog** [comment] 2020-06-04 16:59
Also, please comment in the following:
https://bugzilla.mozilla.org/show_bug.cgi?id=1177968
https://bugzilla.mozilla.org/show_bug.cgi?id=1643405

**Comment by derjanb** [comment] 2020-06-05 18:34
> Also, please comment in the following:
> https://bugzilla.mozilla.org/show_bug.cgi?id=1643405

Done.

> Maybe @derjanb can snoop in the code (MIT license) to compare.

They execute userscripts within the extension's content script. This has the downside that the userscripts do have the same powers like the extension itself.  I decided against this 8 or 9 years ago.

**Comment by alexolog** [comment] 2020-06-05 18:47
Thanks!

Out of curiosity, what's wrong with having the userscripts have the same powers as TM?  We are assuming the user knows what they are doing, no?

I just want scripts to work seamlessly with minimal side effects, and I really prefer to use TM over GM or VM on FF.

**Comment by Owyn** [comment] 2020-06-05 19:25
> "Remove entirely (possibly unsecure)"

I wish you could reach out to FF devs to say they're just making it worse for end users (if it's working as intended)...

> This modification is done only if scripts are supposed to run, so there is no need to disable CSP via security.csp.enable in general anymore.

Many scripts I use run on all pages and disable themselves when not needed, so it'd just disable CSP on 100% of sites and pages entirely :-(

**Comment by alexolog** [comment] 2020-06-05 19:29
> I wish you could reach out to FF devs to say they're just making it worse for end users (if it's working as intended)...

My suspicion is that the FF devs will just point to GM and claim that TM is just doing it wrong.

**Comment by derjanb** [comment] 2020-06-06 00:10
Should be fixed at 4.11.6114

**Comment by Bl4Cc4t** [comment] 2020-06-06 09:34
Thank you so much, this is very appreciated!

**Comment by ran-sama** [comment] 2020-06-06 21:38
Thanks and donated for this as bug bounty.
Have some dark drink of choice on me!

**Comment by jerone** [comment] 2020-06-07 17:48
Beta 4.11.6114 fixed the similar issue for me with userscripts run on GitHub.

**Comment by LurkerHub** [comment] 2020-06-08 05:58
Still having the issue with 6114:

```
Security Error: Content at https://elliquiy.com/forums/index.php?action=profile;area=showposts;sa=topics;u=41454 may not load data from blob:moz-extension://eb61ac3e-ed19-4b96-93b1-d906591e63a5/a40e6b10-48d2-4b30-81c4-4bc3f2ee2c84.
```

**Comment by LurkerHub** [comment] 2020-06-08 06:14
Also scripts break on Github because of CSP

**Comment by derjanb** [comment] 2020-06-08 06:53
> Still having the issue with 6114:
> 
> ```
> Security Error: Content at https://elliquiy.com/forums/index.php?action=profile;area=showposts;sa=topics;u=41454 may not load data from blob:moz-extension://eb61ac3e-ed19-4b96-93b1-d906591e63a5/a40e6b10-48d2-4b30-81c4-4bc3f2ee2c84.
> ```

This is handled in #963 

> Also scripts break on Github because of CSP

Also in "normal" injection mode?

**Comment by LurkerHub** [comment] 2020-06-08 14:32
"Default" seems to work

**Comment by derjanb** [comment] 2020-06-08 17:48
> Out of curiosity, what's wrong with having the userscripts have the same powers as TM? We are assuming the user knows what they are doing, no?

@alexolog 
https://bugzilla.mozilla.org/show_bug.cgi?id=1594234 -> "Developers can no longer use CSP directives that enable remotely hosted code (code that is not bundled with the extension). Manifests that include such directives will error at parse time."
https://blog.mozilla.org/addons/2019/12/12/test-the-new-csp-for-content-scripts/ -> "Please do not loosen the CSP to allow remote code, as we are working on upcoming changes to disallow remote scripts."

**Comment by alexolog** [comment] 2020-06-08 17:59
Aren't we talking about locally hosted user scripts?

**Comment by alexolog** [comment] 2020-06-12 22:59
FF dev updated itself to 78.0b6 and now the problem is back with a vengeance.  None of my scripts run on Google unless I disable CSP globally.

I am running the 4.11.6114 beta

Example page:
https://www.google.com/search?tbm=isch&q=cat&tbs=imgo:1

Sample scripts that fail to run:
* https://greasyfork.org/scripts/401432-google-image-search-show-image-dimensions/code/Google%20Image%20Search%20-%20Show%20Image%20Dimensions.user.js
* https://greasyfork.org/scripts/19210-google-direct-links-for-pages-and-images/code/Google:%20Direct%20Links%20for%20Pages%20and%20Images.user.js
* https://greasyfork.org/scripts/404103-google-image-search-show-image-dimensions/code/%11Google%20Image%20Search%20%7C%20Show%20image%20dimensions%11.user.js
* https://greasyfork.org/scripts/398802-google-images-direct-links-2/code/Google%20Images%20direct%20links%202.user.js
* https://greasyfork.org/scripts/398189-google-image-direct-view/code/Google%20Image%20Direct%20View.user.js

Errors in the log:
```
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
```

GreaseMonkey works.

**Comment by alexolog** [comment] 2020-06-25 02:56
Any ideas?

**Comment by derjanb** [comment] 2020-06-26 20:47
> FF dev updated itself to 78.0b6 and now the problem is back with a vengeance. None of my scripts run on Google unless I disable CSP globally.

Hmm, this works fine here with both FF beta 78.0b6 and FF beta 78.0. Tested with an own script and "Google Image Search - Show Image Dimensions" at your example page. I've also created a new profile to make sure no FF setting was modified. 🤔 Do you have other extensions installed? I've tested with uBlock Origin and uMatrix and in both cases it still worked.

Note: I've also created a issue at Mozilla's bug tracker about the issue, but it was set to duplicate of another issue. Nevertheless, feel free to star or comment.
https://bugzilla.mozilla.org/show_bug.cgi?id=1645614

**Comment by alexolog** [comment] 2020-06-27 00:08
I think I found the culprit, and it was another extension: https://github.com/Sainan/Universal-Bypass/issues/1342
I disabled it for now.  Too bad though, since it is a useful one.

Your bug report was marked as a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1591983
Regardless, I voted for both (although it seems I can only give a single vote to each so it does not amount to much)

With that extension disabled, scripts appear to work on Google.com without the need to globally disable CSP.

Interestingly, setting "Modify existing content security policy (CSP) headers" to "yes" still works.  Is it only used for "instant" mode?

**Comment by alexolog** [comment] 2020-06-27 13:21
Could you please comment on https://github.com/Sainan/Universal-Bypass/issues/1342 ?
It looks like an incompatibility between the extensions

**Closed** 2020-11-10 13:07 UTC
Labels: bug, external, firefox, fixed at beta

**Comment by benyaminl** [comment] 2021-07-30 09:08
Hello I got this problem on FF 90.0.2, Is that suppose to happen? I already remove the CSP Header option and add tampermonkey to HTML CSP. Is this problem come back or It's only me. Before on 89.0 there're no problem

**Comment by alexolog** [comment] 2021-07-30 17:04
Running 91.0b9, everything seems to be in order here.
Try using a new profile with no other add-ons.  If it works, it is most likely an add-on conflict.

**Comment by benyaminl** [comment] 2021-07-30 18:34
> 
> 
> Running 91.0b9, everything seems to be in order here.
> Try using a new profile with no other add-ons. If it works, it is most likely an add-on conflict.

Sadly it's not working on new profile, but I tried to add another script, it works, so it should be the userscript(my script, not the extension) problem, that it stop working because google change their layout HTML. 

Thank you for coming back

**Comment by bobpaul** [comment] 2023-11-10 21:38
On Firefox `119.0.1 (64-bit)` on Windows I'm unable to load any scripts on `web.snapchat.com`. I'm using a [user agent switcher](https://gitlab.com/ntninja/user-agent-switcher) along with tampermonkey. I've tried setting "Experimental -> Add Tampermonkey to CSP" as well as "Security -> Modify CSP -> Remove entirely".
