### ISSUE TITLE
【No work】Unable to open 

### ISSUE THREAD

**Issue by Noah1995** [Tampermonkey/tampermonkey#1888] opened 2023-11-09 04:46 UTC
![image](https://github.com/Tampermonkey/tampermonkey/assets/25548230/f2827753-34e1-45b2-91e4-88f636de613a)

**Comment by Noah1995** [comment] 2023-11-09 04:49
Restart is also invalid...
Keep going in circles...

**Comment by Sewiahho** [comment] 2023-11-09 16:19
The same thing happened to me.I try some way to solve it,doesn't useful,such as back to olded Version,change olded firefox Version,try to use local files cover it.but no one useful

**Comment by krystian3w** [comment] 2023-11-10 10:01
https://github.com/Tampermonkey/tampermonkey/issues/1885

**Comment by derjanb** [comment] 2023-11-16 15:08
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/1885?

**Closed by derjanb** 2023-11-16 15:08 UTC
