### ISSUE TITLE
Scripts do not run on chrome error pages

### ISSUE THREAD

**Issue by mjda1366** [Tampermonkey/tampermonkey#1591] opened 2022-09-11 21:54 UTC
(Please fill out the issue template with your details)

## Expected Behavior
running of a script on the chrome error pages. for example when the DNS_PROBE_FINISHED_NXDOMAIN error occurs.

## Actual Behavior
No script run on error pages.

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (Windows 11)

## Script

// ==UserScript==
// @name         Auto-Reload
// @namespace    
// @version      0.1
// @description  try to take over the world!
// @author       Me
// @match        *
// @icon         
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

const submit = document.querySelector('#reload-button');
setTimeout(() => {
    submit.click();
}, 3000);

})();

**Comment by 7nik** [comment] 2022-09-11 22:10
I'm 99% sure it is because extensions just cannot have any access to the system page, and the error page is one of them.

The Stylus clearly says it:
![image](https://user-images.githubusercontent.com/29704098/189550687-1c2b529d-3cd4-4383-9176-3083b17f463a.png)

The DevTools also shows there are no content scripts of any extensions:
![image](https://user-images.githubusercontent.com/29704098/189550772-153ac30d-f67e-408a-9362-1a12abab8275.png)
And the DevTools even shows the real address of the page: `chrome-error://chomewebdata/` - extensions simply cannot access pages with this protocol.

**Comment by kodsu** [comment] 2022-09-12 08:13
> // ==UserScript== // @name Auto-Reload // @namespace // @Version 0.1 // @description try to take over the world! // @author Me // @match * // @ICON // @grant none // ==/UserScript==
> 
> (function() { 'use strict';
> 
> const submit = document.querySelector('#reload-button'); setTimeout(() => { submit.click(); }, 3000);
> 
> })();

You are right, and by the way if you look at the TamperMonkey icon, you won't see any red notification saying that a script has been found for the page.
This is because the script starts to run at least after reaching the web page.

Please see the following answer [source](https://stackoverflow.com/questions/23724668/chrome-extension-to-reload-page-on-load-error)  and #174:
![image](https://user-images.githubusercontent.com/17864005/189604477-764fa407-6b12-41a4-bd56-2e251897f23f.png)

You can create an extension and use these APIs, but it can't be done with a content script.

**Comment by derjanb** [comment] 2022-09-19 06:36
@kodsu :+1: 

Duplicate of #174

**Closed by derjanb** 2022-09-19 06:36 UTC
