### ISSUE TITLE
Add config option to disable update notification

### ISSUE THREAD

**Issue by alandsidel** [Tampermonkey/tampermonkey#1184] opened 2021-03-18 15:56 UTC
## Expected Behavior
No notifications pop up in windows when an update is ready, or at any other time.

## Actual Behavior
Notifications do pop up in windows when updates are ready.

## Specifications
Windows 10, Firefox 86.

**Comment by derjanb** [comment] 2021-03-18 18:12
Duplicate of #427

**Closed by derjanb** 2021-03-18 18:12 UTC
