### ISSUE TITLE
"No script running" on latest Chrome Beta on Linux

### ISSUE THREAD

**Issue by bekoeppel** [Tampermonkey/tampermonkey#2023] opened 2024-04-02 09:54 UTC
## Expected Behavior

  * Tampermonkey script runs

## Actual Behavior

  * No Tampermonkey scripts run (on any website)
  * Extension always shows "No script running"

## Specifications

- Tampermonkey: 5.1.0
- Ubuntu 20.04.6 LTS

Browser:
- good: Chrome 123.0.6312.46
- bad: Chrome 124.0.6367.18

## Script

Any script

## Further details

I don't know if this is a Tampermonkey or a Chrome bug. I used Chrome Bisect to narrow down the range of Chromium changes where the breaking change must have been introduced:

```
python3 ./bisect-builds.py -a linux64 -g 123.0.6312.46 -b 124.0.6367.18 --use-local-cache --verify-range -- --no-first-run --user-data-dir=/tmp/data-dir https://app.slack.com/
```

Result:
```
Revision 1263408 is [(g)ood/(b)ad/(r)etry/(u)nknown/(s)tdout/(q)uit]: g
You are probably looking for a change made after 1263408 (known good), but no later than 1263433 (first known bad).
CHANGELOG URL:
  https://chromium.googlesource.com/chromium/src/+log/7ed452a62e58234657d7e27b44690a9b4ca2e7b4..e331b8c8333039ed7a7c1a2199339c8629d803c7
```

**Comment by derjanb** [comment] 2024-04-02 10:37
Duplicate of #2011 

Please try the workaround mentioned here: https://github.com/Tampermonkey/tampermonkey/issues/2011#issuecomment-2016887028

**Closed by derjanb** 2024-04-02 10:37 UTC

**Comment by bekoeppel** [comment] 2024-04-02 12:37
Thank you!
