### ISSUE TITLE
layout acting weird

### ISSUE THREAD

**Issue by Pancakes0** [Tampermonkey/tampermonkey#1191] opened 2021-03-23 01:26 UTC
(Please fill out the issue template with your details)

## Expected Behavior
full box that fit 

## Actual Behavior
i can scroll now and its annoying over time

https://user-images.githubusercontent.com/73923883/112078614-b5c92100-8bb9-11eb-976e-a0185b82b14c.mp4
 i tried quitting firefox and shutting down the laptop.

## Specifications

- Firefox: (68.0.1)
- TM: (i.e. 4.5.5648)
- MacOS: (10.14.6)

**Comment by Rekulous** [comment] 2021-03-24 13:03
> (Please fill out the issue template with your details)
> 
> ## Expected Behavior
> full box that fit
> 
> ## Actual Behavior
> i can scroll now and its annoying over time
> 
> https://user-images.githubusercontent.com/73923883/112078614-b5c92100-8bb9-11eb-976e-a0185b82b14c.mp4
> i tried quitting firefox and shutting down the laptop.
> 
> ## Specifications
> * Firefox: (68.0.1)
> * TM: (i.e. 4.5.5648)
> * MacOS: (10.14.6)

This Repo is abandoned. Switch to ViolentMonkey because Tampermonkey is no longer open-source

**Comment by derjanb** [comment] 2021-03-24 19:22
Duplicate of #1181

**Closed by derjanb** 2021-03-24 19:22 UTC

**Comment by derjanb** [comment] 2021-03-24 19:24
... and please see https://github.com/Tampermonkey/tampermonkey/issues/1181#issuecomment-801691889 for a workaround.
