### ISSUE TITLE
Slow and abnormally lagging GM.xmlHttpRequest

### ISSUE THREAD

**Issue by AlttiRi** [Tampermonkey/tampermonkey#1107] opened 2020-12-27 03:27 UTC
I have noted about this in [this comment](https://github.com/Tampermonkey/tampermonkey/issues/1106#issuecomment-751414042), but I think it's better to create a separate issue.
Also the similar behaviour _was_ in VM, but it was fixed recently.

## Expected Behavior
Downloading with `GM.xmlHttpRequest` of "big" files works fast, without any lag or freezing. 
ViolentMonkey (the latest version) downloads a 100 MB almost instantly (as soon as all data were received from a server).

## Actual Behavior

Downloading of a 100 MB file leads to a lags for 6 second + for 10 the page is totally frozen. (16 seconds of total)

## Specifications

- Chromium: 85
- TM: 4.12.6123 (Beta)
- OS: Win10

## Script

```js
// ==UserScript==
// @name        Issue 1107 (GM.xmlHttpRequest, 104 MB, gfycat.com)
// @namespace   Issues
// @match       https://github.com/Tampermonkey/tampermonkey/issues/1107
// @match       https://example.com/
// @grant       GM.xmlHttpRequest
// @connect     giant.gfycat.com
// ==/UserScript==

!async function() {
    console.log("downloading (104 MB)...");
    const response = await new Promise((resolve, reject) => {
        GM.xmlHttpRequest({
            method: "get",
            url: "https://giant.gfycat.com/ConfusedRecentGuppy.mp4", // 104 MB
            responseType: "blob",
            onload: resolve,
            onerror: reject,
        });
    });
    console.log("response:", response);

    const {response: blob} = response;
    downloadBlob(blob, "ConfusedRecentGuppy.mp4");
}();

function downloadBlob(blob, name) {
    const anchor = document.createElement("a");
    anchor.setAttribute("download", name || "");
    anchor.href = URL.createObjectURL(blob);
    anchor.click();
}
```

**Comment by AlttiRi** [comment] 2020-12-27 03:36
Install this script, reload this page, and try to select a different text parts, you will see the lags (~1 fps) and the page freezing for some time until the file is downloaded (saved).
You can also try this with less sized file (32 MB): https://giant.gfycat.com/ShockedSecondaryFiddlercrab.mp4

**Comment by derjanb** [comment] 2020-12-30 22:12
Duplicate of #279

Please see https://github.com/Tampermonkey/tampermonkey/issues/279#issuecomment-752773811 for more information.

**Closed by derjanb** 2020-12-30 22:12 UTC
Labels: bug

**Comment by AlttiRi** [comment] 2020-12-31 04:20
The script does not work at all with 4.12.6124. File is not saved.
