### ISSUE TITLE
[Firefox]: Access local files with @require & @resource directives

### ISSUE THREAD

**Issue by DerekZiemba** [Tampermonkey/tampermonkey#2150] opened 2024-08-09 03:53 UTC
Attempted to migrate to Firefox from Chrome due to manifest v3 & the final straw, my Youtube script no longer works.  
I moved everything over to firefox & imported/exported for every single extension. But none of my scripts are working in Firefox that work fine in Chrome!

Both Google & Bing are giving me nothing for the error below. I feel this should be a simple setting or something, but I can't find it,  or _ANYTHING_ about it that's more recent than 3-5 years ago / still applies. I've grown accustomed to modern search engines being crap, & these days AI needing to fill the gap, but even ChatGPT/BingAI doesn't have the answer.

Below is an example that works fine in Chrome. I can't figure out how to allow local file access in Firefox. 

## Expected Behavior

For `@require` & `@resource` directives to work with local files

## Actual Behavior

* `injected: @resource: can't load @resource 'STYLE' from URL 'file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/reddit.css': Access to this or all local files is forbidden! content.js:8:1206`

* `@require: couldn't load @require from URL 'file:///C:/Dropbox/Scripts/.js/TM/core/GM.js': Access to this or all local files is forbidden! GM.user.js:2:9`

* `@require: couldn't load @require from URL 'file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/.index.js': Access to this or all local files is forbidden! RESEnhancementScript-2.user.js:2:9`

## Specifications

- Firefox: 129.0
- TM: 5.1.1
- OS: Win 11 Education 22H2 (OS Build 22621.3880)

## Script

(Please give an example of the script if applicable.)

* Inject Style early as possible to avoid white flash / or style change while loading
  ```
  // ==UserScript==
  // @name         RESEnhancementScript-Style
  // @description	 Style for RESEnhancementScript
  // @author       Derek Ziemba
  // @match          *://*.reddit.com/*
  // @icon         https://www.google.com/s2/favicons?sz=64&domain=reddit.com
  // @run-at		      document-start
  // @sandbox					DOM
  // @grant           GM_getResourceText
  // @grant           GM_addStyle
  // @resource        STYLE   file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/reddit.css
  // ==/UserScript==
  
  GM_addStyle(GM_getResourceText('STYLE'));
  ```

* The script
  ```js
  // ==UserScript==
  // @name         RESEnhancementScript-2
  // @version      2.21.0
  // @description	 Enhances RedditEnhancementSuite
  // @match          *://*.reddit.com/*
  // @icon         https://www.google.com/s2/favicons?sz=64&domain=reddit.com
  // @noframes
  // @nocompat
  // @run-at		      document-start
  // @grant           unsafeWindow
  // @grant           GM_getResourceText
  // @grant           GM_addStyle
  // @grant           GM_addElement
  // @grant           GM_getValue
  // @grant           GM_setValue
  // @grant           GM_deleteValue
  // @grant           GM_listValues
  // @grant           GM_addValueChangeListener
  // @grant           GM_registerMenuCommand
  // @grant           GM_unregisterMenuCommand
  // @require         file:///C:/Dropbox/Scripts/.js/TM/core/type-extensions.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/core/str-literal.regex.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/core/str-literal.html.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/core/str-literal.css.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/core/GM.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/core/binder.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/core/event-lite.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/core/deferred-task.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/core/debounce.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/reddit.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/TopSublinksBar.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/SideBar.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/ContinueThisThread.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/links.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/listings-manager.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/FilterRule.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/filters.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/Thing.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/mainMenu.js
  // @require         file:///C:/Dropbox/Scripts/.js/TM/websites/reddit/.index.js
  // ==/UserScript==
  ```

**Comment by derjanb** [comment] 2024-08-09 09:01
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/347#issuecomment-269039234

Sorry.

**Closed by derjanb** 2024-08-09 09:01 UTC

**Comment by DerekZiemba** [comment] 2024-08-09 13:48
I believe this issue is different because I've used FF off and on & these scripts did work for several years. This is some recent change.

**Comment by derjanb** [comment] 2024-08-11 16:55
Local file support was possible by using a hack that has been fixed by Firefox (Windows first, and Linux much later). 
The official issue is the only way to ask for support if this.

**Comment by DerekZiemba** [comment] 2024-08-13 02:23
That's disappointing.  I was able to fix my chrome issues with the following, so guess I stick with chrome for now. 

```js
window.trustedTypes.createPolicy('default', {
    createHTML: (string, sink) => string
});
someElement.innerHTML = window.trustedTypes.defaultPolicy.createHTML(text);
```

**Comment by yavuzbehic** [comment] 2024-08-27 22:29
workaround: use xampp apache web server, start the server, then put your "script.js" in the htdocs folder. now you can use require. found this on my own because i was trying to get https://blog.exupero.org/live-reloading-tampermonkey-scripts/ to work on firefox. shoutout to my mobile dev instructor from uni.
