### ISSUE TITLE
GM_setValue is not saving RegExp properly, converts it to an empty object {}

### ISSUE THREAD

**Issue by emp2687** [Tampermonkey/tampermonkey#1993] opened 2024-02-22 18:42 UTC
(Please fill out the issue template with your details)
GM_setValue is not saving RegExp properly, converts it to an empty object {}
Sample code:
let re = new RegExp("^John.*left", "i");
GM_setValue("john_re", re);

## Expected Behavior
GM_setValue will store the value provided by RegExp.toString():
/^John.*left/i

## Actual Behavior
GM_setValue treats it as an empty object and stores:
{}

## Specifications
Chrome 121.0.6167.160 

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==

let re = new RegExp("^John.*left", "i");
GM_setValue("john_re", re);

let read = GM_getValue("john_re");
console.log(JSON.stringify(read));

```

**Comment by 7nik** [comment] 2024-02-22 18:49
duplicate of #1216

**Closed** 2024-03-13 13:36 UTC
