### ISSUE TITLE
Manually reordering scripts in the dashboard causes TM to lock up

### ISSUE THREAD

**Issue by tjanke42** [Tampermonkey/tampermonkey#745] opened 2019-07-25 10:50 UTC
#102 Expected Behavior
I can drag and drop scripts in the dashboard to order them, moving them as many places at a time as I wish (i.e. move a script from #16 to #3, in one move).

## Actual Behavior
Moving a script up in the dashboard (even one row) intermittently causes the script to lock up during the move and become completely unresponsive.  Examining the script in Chrome's task manager shows TM using 98%-99% of the cpu.

The only way to recover is to use Chrome's task manager to end the process, then chrome pops up a notification saying the extension has crashed, 'click here to restart'.

## Specifications

- Chrome: 75.0.3770.142
- TM: 4.8.41
- OS: Windows 7 Ultimate with SP1

## Script
All scripts.

**Comment by derjanb** [comment] 2019-07-26 13:33
Duplicate of #543

**Closed by derjanb** 2019-07-26 13:33 UTC
