### ISSUE TITLE
[Microsoft Edge] When clicking on a link to a .user.js file Tampermonkey does not show installation page

### ISSUE THREAD

**Issue by rcmero** [Tampermonkey/tampermonkey#394] opened 2017-05-04 10:52 UTC
When I click on a link to a userscript Tampermonkey should show a page to allow installation of the script. This does not happen in Edge, instead it displays the script as if it were a normal text file. I then have to copy the URL to the script and access the Tampermonkey dashboard to install it manually from there.

I tested this in Firefox and the installation page is displayed as normally, so this bug seems to only exist in Mcirosoft Edge.

**Comment by derjanb** [comment] 2017-05-04 11:36
What Windows 10/MS Edge version do you use?
Please disable all other extensions and retry. Thanks. 

https://github.com/Tampermonkey/tampermonkey/issues/350 https://github.com/Tampermonkey/tampermonkey/issues/358 https://github.com/Tampermonkey/tampermonkey/issues/329

**Comment by rcmero** [comment] 2017-05-04 14:45
I tested it on the Anniversary Update and can confirm that it occurs. Not sure if this occurs on the version of Edge on the Creators Update yet, though.

The only other extension I have installed is uBlock Origin too.

**Comment by derjanb** [comment] 2017-05-04 14:52
Ok, then it's a MS Edge bug duplicate of #329. Updating to the Creators Update will fix the issue.

**Closed by derjanb** 2017-05-04 14:52 UTC
