### ISSUE TITLE
Tampermonkey shows wrong number of running scripts

### ISSUE THREAD

**Issue by mavis-risetti** [Tampermonkey/tampermonkey#1194] opened 2021-03-26 12:40 UTC
## Expected Behavior
I only have one user-script. So TamperMonkey is supposed to show 1 (under the icon, in red, as a subscript), when running.

## Actual Behavior
But that number is like 2 or sometimes even 40.

In this image, it's 63, even though I only have one script running.
![Screenshot_2021-03-26_18-09-48](https://user-images.githubusercontent.com/78014157/112632702-7a02b580-8e5e-11eb-8678-9216486315b4.png)

## Specifications

- Chromium: 89.0.4389.90
- TM: 4.12
- OS: Ubuntu

**Comment by derjanb** [comment] 2021-03-26 12:47
By default the number of script __instances__ are shown. 
If you want to change this, you can easily do so by switching "Config mode" to "Advanced" and the altering the "Icon badge info" setting.

Duplicate of #163

**Closed by derjanb** 2021-03-26 12:47 UTC

**Comment by mavis-risetti** [comment] 2021-03-26 12:49
Shouldn't there be only one instance running per site?

**Comment by derjanb** [comment] 2021-03-26 13:17
It depends. ;-) It can be one per frame (which includes iframes). If you're sure that the site doesn't use frames, then can you please tell me the page URL and the script source?
