### ISSUE TITLE
The toolbar icon menu becomes weird on Firefox if the script list is long.

### ISSUE THREAD

**Issue by YandLiu** [Tampermonkey/tampermonkey#1212] opened 2021-04-08 09:23 UTC
![1](https://user-images.githubusercontent.com/26127104/114001944-c22ec880-989f-11eb-897e-aefe56b3f2b3.gif)

## Expected Behavior
It should display as normal as on Edge or Chrome.

## Actual Behavior
If the script list is long, the toolbar icon menu becomes weird.

## Specifications

- Firefox: 87.0
- TM: 4.12.6132
- OS: Windows 10

**Comment by derjanb** [comment] 2021-04-08 09:25
Duplicate of #1181 and please see https://github.com/Tampermonkey/tampermonkey/issues/1181#issuecomment-801691889 for a workaround. It is also fixed at the [latest BETA version](https://www.tampermonkey.net/?browser=firefox).

**Closed by derjanb** 2021-04-08 09:25 UTC
