### ISSUE TITLE
 Can't connect to the Internet when using Google to search for news input

### ISSUE THREAD

**Issue by NDS7EN** [Tampermonkey/tampermonkey#939] opened 2020-05-18 01:09 UTC
CHROME   81.0.4044.138
tampermonkey：4.10
error： Can't connect to the Internet when using Google to search for news input

recurrent：
1.Use Google search Any character 
2.Click to news Options
3.Back to the input box again Enter text
4.Click to search
NOW.Browser network connection has crashed

try：Disable any extension Not included tampermonkey ：NOT WORKING
try:Run tampermonkey extension only ：same errors
TRY:Run tampermonkey extension only and Disable any script ： same errors
TRY:Disable tampermonkey extension ：No errors

Now found 4.10 tampermonkey 
Causes the browser cannot connect to the network

**Comment by derjanb** [comment] 2020-05-18 18:02
Can you please add some screenshots or a screencast?

**Comment by NDS7EN** [comment] 2020-05-19 10:21
[VID_20200519_181437.zip](https://github.com/Tampermonkey/tampermonkey/files/4649748/VID_20200519_181437.zip)
video

> 您能否添加一些屏幕截图或截屏视频？

**Comment by derjanb** [comment] 2020-07-15 18:26
Thanks for your feedback.

Duplicate of #661

**Closed by derjanb** 2020-07-15 18:26 UTC
Labels: feedback needed
