### ISSUE TITLE
Can't load external JS frameworks using @require

### ISSUE THREAD

**Issue by aagorbachev** [Tampermonkey/tampermonkey#1176] opened 2021-03-13 16:34 UTC
I'm trying to load Popper.JS and Tippy.JS to add tiny tooltips to the ability list of virtual table top game roll20.net

If I add raw code from their CDN's into body of premade function, everything is working fine.

CND's which I declare at @require:
https://unpkg.com/@popperjs/core@2
https://unpkg.com/tippy.js@6

Example: 
Here is styled UI of roll20.net

![image](https://user-images.githubusercontent.com/69871856/111036568-d8786e80-8430-11eb-87d7-9392723df170.png)

## Expected Behavior
Appearance of tooltip after hovering on the skill button.

## Actual Behavior
I'm getting the following error at Console:

ERROR: Execution of script 'New Userscript' failed! Cannot read property 'applyStyles' of undefined
TypeError: Cannot read property 'applyStyles' of undefined

I think that the problem is probably caused by a scope of view of the tippy's function. I've just want to know how could i properly add necessary CDN's to @require sections to avoid such copy-paste moves. Probably i should register somehow all the globals from required external scripts. But I didn't find proper syntax-instructions for that. 
In my opinion, if i'm right about the cause, it make a functionality of "@require" declaration little bit senseless.

## Specifications

- Chrome: (89.0.4389.82 )
- TM: (4.11)
- OS: (Windows 10)

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        http://*/*
// @grant        none
// @run-at       context-menu
// @require https://unpkg.com/@popperjs/core@2.9.1/dist/umd/popper.min.js
// @require https://unpkg.com/tippy.js@6.3.1/dist/tippy-bundle.umd.min.js
// ==/UserScript==

(function() {
    'use strict';
    <...number of objects with defined description for abilities tooltip including "magicMissile" object.>

magicMissile.renderTooltip()

const button = document.querySelectorAll('.macrobox button');

button.forEach(element => {
let macroID = element.parentNode.getAttribute("data-macroid")
let tipTarget = document.querySelector(`div[macroid="${macroID}"`)
    if (tipTarget) {
      tipTarget.style.display = "block"
      tippy(element, {
        zIndex: 10000001,
        interactive: true,
        appendTo: document.body,
        content: tipTarget,
        allowHTML: true,
     })}});
})();
```

**Comment by derjanb** [comment] 2021-03-14 21:43
It's caused by Tampermonkey's sandbox.

As a workaround adding this `@require` in front of the two others should fix your issue:

```JS
// @require data:text/javascript;base64,dGhpcy5nbG9iYWxUaGlzID0gdGhpczs=
```

**Comment by aagorbachev** [comment] 2021-03-15 05:50
> It's caused by Tampermonkey's sandbox.
> 
> As a workaround adding this `@require` in front of the two others should fix your issue:
> 
> ```js
> // @require data:text/javascript;base64,dGhpcy5nbG9iYWxUaGlzID0gdGhpczs=
> ```

It helped. Thank you!

**Comment by derjanb** [comment] 2021-04-01 19:25
Should be fixed at the latest [BETA version](https://www.tampermonkey.net/crx/tampermonkey_beta_4_13_6133.crx) which will be published at the Chrome Web Store after review.

**Closed** 2021-05-20 18:49 UTC
Labels: enhancement, fixed at beta
