### ISSUE TITLE
The cookie value is invaild with GM_xmlhttpRequest after upgrade to v5.2.0

### ISSUE THREAD

**Issue by Tinyfatboy** [Tampermonkey/tampermonkey#2112] opened 2024-07-01 02:52 UTC
## Actual Behavior

Hello, after upgrading to Tampermonkey 5.2.0, the original script failed when sending requests using GM_xmlhttpRequest. We compared all the API information of version 5.1.1 and found that after the upgrade, if the cookie value contains quotation marks `"`, the GM_xmlhttpRequest method will encode the quotation marks to `%22`, causing the original script to fail.

eg.
original cookie (v5.1.1)
`idtt.certInfo="W7I356...`

with v5.2.0
`idtt.certInfo=22%W7I356...`

This affect our script and makes GM_xmlhttpRequest failed. Cloud you help to check.

## Specifications

- Chrome: (125.0.6422.176)
- TM: (5.2.0)
- OS: (win 10 22H2)

## Script

```js
// ==UserScript==
// @name         myScript
// @namespace    http://tampermonkey.net/
// @author       myName
// @match        https://example.com
// @run-at       document-start
// @grant        GM_xmlhttpRequest
// @connect      target.example.com
// ==/UserScript==

(function() {
    GM_xmlhttpRequest({
        url: 'https://target.example.com,
    });
})();
```

**Comment by derjanb** [comment] 2024-07-01 18:44
Duplicate of #2094.

Should be at 5.3.6202 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx))

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode'). For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by derjanb** [comment] 2024-07-01 18:47
Can you please test [Tampermonkey BETA](https://chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf). Thanks.

**Comment by Tinyfatboy** [comment] 2024-07-02 00:52
> Can you please test [Tampermonkey BETA](https://chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf). Thanks.

Hello, thanks for your advice. I tested with Tampermonkey BETA, but the error still occurs.

**Comment by derjanb** [comment] 2024-07-02 08:38
Thanks a lot. Please use [Tampermonkey Legacy](https://chromewebstore.google.com/detail/tampermonkey-legacy/lcmhijbkigalmkeommnijlpobloojgfn) as long as I'm working on a fix...

**Comment by derjanb** [comment] 2024-07-07 19:19
Should be at 5.3.6203 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx))

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

**Closed** 2024-08-16 09:59 UTC
Labels: bug, fixed at beta
