### ISSUE TITLE
externals cached

### ISSUE THREAD

**Issue by jonnytest1** [Tampermonkey/tampermonkey#1465] opened 2022-03-29 20:36 UTC
(Please fill out the issue template with your details)

## Expected Behavior
when an external is set to refresh "always" there should not be a cached version used

## Actual Behavior
 external doesnt update anymore
 (i manually called the url to check and yes the url content is up to date)
even manually deleting the external doesnt get me the up to date version

## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require <someurl>
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment] 2022-04-03 17:55
Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/228#issuecomment-122233695

**Closed by derjanb** 2022-04-03 17:55 UTC
