### ISSUE TITLE
为什么我的Tampermonkey下载了无法打开？

### ISSUE THREAD

**Issue by asjdnbajskdn** [Tampermonkey/tampermonkey#1492] opened 2022-04-22 10:09 UTC
一直在转圈圈无法打开，还显示内部出现了错误

**Comment by derjanb** [comment] 2022-04-22 13:47
Can you please attach a screensot?

**Comment by dotabillie** [comment] 2022-05-30 14:46
![屏幕截图 2022-05-30 224004](https://user-images.githubusercontent.com/86512760/171015714-f1be7fc6-84b7-4b96-aa4a-aefbdb3c0628.png)
same question, keep loading when click the extention icon, here's the image

**Comment by derjanb** [comment] 2022-06-09 18:06
What is your browser and Tampermonkey version?

**Comment by derjanb** [comment] 2022-06-09 18:16
Duplicate of #1469

**Closed by derjanb** 2022-06-09 18:16 UTC
Labels: feedback needed
