### ISSUE TITLE
Tampermonkey v5.2 does not work in the Kiwi Browser

### ISSUE THREAD

**Issue by KeepssMe** [Tampermonkey/tampermonkey#2109] opened 2024-06-26 20:23 UTC
Tampermonkey does not work in the Kiwi Browser when developer mode is enabled.

## Specifications

- Kiwi Browser 124.0.6327.4
- TM v5.2 (beta including)
- OS: Android 14

(Sorry for my poor knowledge of English)

**Comment by derjanb** [comment] 2024-06-28 20:41
Duplicate of #2055 

Please see https://github.com/Tampermonkey/tampermonkey/issues/2055#issuecomment-2197629497

**Closed by derjanb** 2024-06-28 20:41 UTC
