### ISSUE TITLE
TM v4 with Firefox 77 doesn't work on Twitter.com

### ISSUE THREAD

**Issue by yamabukidesign** [Tampermonkey/tampermonkey#964] opened 2020-06-05 18:57 UTC
with other browsers TM work.
TM with Firefox on facebook.com, they work.

## Expected Behavior

alert('why?');

## Actual Behavior

no alert only on twitter.com.

## Specifications

- Firefox:77.0.1 (64 bit)
- TM: v4.10.6112
- OS: MacOS 10.14.6

## Script

```js
// ==UserScript==
// @name         New Userscript
// @match        https://twitter.com/*
// @match        https://www.facebook.com/*
// ==/UserScript==

alert('why?');
```

**Comment by derjanb** [comment] 2020-06-05 19:14
Duplicate of #952

Please see this comment for a workaround: https://github.com/Tampermonkey/tampermonkey/issues/952#issuecomment-638373937

**Closed by derjanb** 2020-06-05 19:14 UTC
