### ISSUE TITLE
Firefox toolbar script list disappears with specific Youtube script installed

### ISSUE THREAD

**Issue by MoneyAllDay** [Tampermonkey/tampermonkey#1616] opened 2022-10-12 19:13 UTC
## Issue example

![12-10-2022](https://user-images.githubusercontent.com/19583547/195427890-41bb6e83-d305-430b-9d84-91e2758c5753.gif)

## Expected Behavior

Firefox toolbar script list should not disappear with specific Youtube script installed.

## Actual Behavior

Firefox toolbar script list disappears with specific Youtube script installed.

## Specifications

- Firefox 105.0.3 (64-bit)
- TM: v4.18.0
- OS: Win 11 22H2 x64

## Script that causes the issue

[Youtube - Fix channel links in sidebar recommendations](https://greasyfork.org/en/scripts/376510-youtube-fix-channel-links-in-sidebar-recommendations)

**Comment by derjanb** [comment] 2022-10-12 19:14
Duplicate of #1607

**Closed by derjanb** 2022-10-12 19:14 UTC
