### ISSUE TITLE
"Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!"

### ISSUE THREAD

**Issue by BaronKrause** [Tampermonkey/tampermonkey#640] opened 2019-01-25 05:20 UTC
On chrome 73 Canary/Dev on both Linux and windows using the latest dev version of Tampermonkey  im getting this yellow banner at the top of the tampermonkey settings:

"Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!"

Initial setup and sync enabling worked after 2 fresh browser installs and it grabbed the scripts I had on the cloud, but right after that message popped up.

Anyone know what this error is about and how to fix it?

**Comment by BaronKrause** [comment] 2019-01-25 06:21
Ended up being the fault of an old script (I assume). After updating manually to a newer version of it that error no longer pops up.

**Comment by derjanb** [comment] 2019-01-30 13:48
Please see https://developer.chrome.com/extensions/runtime_host_permissions for more information. This message should only be shown if Chrome doesn't grant the "all hosts" permission to Tampermonkey.

**Comment by ayanamist** [comment] 2019-02-08 03:35
However, i have granted "all hosts" to Tampermonkey, but this still exist, screenshot below:
![image](https://user-images.githubusercontent.com/406779/52457594-9ca9b580-2b95-11e9-90a0-f36116a16036.png)

**Comment by nivinj** [comment] 2019-02-08 04:00
Seconding @ayanamist but on the Brave browser:
Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit)
Version 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)

And userscripts don't appear to be working, although Tampermonkey reports that they ran.

Strangely, works for me on Chrome Version 72.0.3626.96 (Official Build) (64-bit) where I don't get the warning.

Have also logged this there https://community.brave.com/t/limited-runtime-host-permissions-for-extensions-tampermonkey/44413?u=niv

**Comment by shinmai** [comment] 2019-02-11 07:32
Can also confirm @ayanamist's findings. After updating to Chrome Version 72.0.3626.96 (Official Build) (64-bit) I'm experiencing similar issues. Have granted "On all hosts" for Tampermonkey, but get the limited runtime host permission warnings and userscript and Tampermonkey functionality seems hampered (can't update userscripts from TM menu, for instance).

**Comment by derjanb** [comment] 2019-02-11 07:38
What Tampermonkey are you using?

**Comment by joelunder** [comment] 2019-02-11 21:47
I can confirm as well that the permission pop-up is happening on all pages, not only those that have limited permissions.

![image](https://user-images.githubusercontent.com/5238345/52595792-b27cdc00-2e1c-11e9-9237-80de3c7be3cb.png)

**Comment by goodjack** [comment] 2019-02-12 03:24
**Same here in the beginning**
Tampermonkey 4.7.54
Chrome 72.0.3626.81 (Official Build) beta
MacOS 10.14.2

![image](https://user-images.githubusercontent.com/1116129/52609237-88c4c300-2eb7-11e9-9f80-e97c79f806da.png)

---

**But it disappeared after I updated Chrome Beta to 73.0.3683.27.**

![image](https://user-images.githubusercontent.com/1116129/52609434-451e8900-2eb8-11e9-9ce2-8eac5e855484.png)

**Comment by vikaspotluri123** [comment] 2019-02-12 04:55
I ran into the same issue and was able to fix it by disallowing access (right click on extension, hover over `this can read and change site data`, select `when you click the extension`) and then reallowing access (same steps as earlier, this time select `on all sites`). I might have done something else, so YMMV

**Comment by joelunder** [comment] 2019-02-12 05:03
Thanks @vikaspotluri123 

That suggestion caused the scripts to actually start running on the pages where they are supposed to, but I am still getting the warning text, so there is clearly something still up.

**Comment by erasedff** [comment] 2019-02-13 12:55
Getting the same warning here, although scripts appear to be working fine.
Been getting this warning for about a month I think, currently running this and still see limited permissions warning:
Chrome 74.0.3702.0 x64, Tampermonkey BETA 4.8.5898

**Comment by trlkly** [comment] 2019-02-13 15:00
I get this box, too, but only with a fresh install on a second profile I was going to use for testing. I tested the Amazon Smile Redirect script, and it worked just fine. I also manually modified it and then did a manual update, and that worked just fine, too. 

If anyone has a script that can test if anything is actually broken, I'd try it. It could be a false alarm. 

(I do note that my Tampermonkey menu is in only one row, and the button on the right side of every script is a + that works like an expander, rather than three dots that make a hover menu. But, still, it's the same Tampermonkey version. I don't know if there's an option that gives me back the two rows or not: two rows is a better use of space, IMO.)

**Comment by trlkly** [comment] 2019-02-13 15:49
I may have figured something out.

I right clicked on Tampermonkey and chose "Manage Extensions." There I enabled everything I normally enable: allowing Tampermonkey access to file:// URLs and access in Incognito mode. I also, for good measure, moved it from "On all sites" to "On click" and back. 

Upon refreshing a website in another tab, the error was gone, and did not recur even after closing the profile and then launching it again.

**Comment by derjanb** [comment] 2019-02-13 16:02
@trlkly Yes, this seems to work (also found by @vikaspotluri123 https://github.com/Tampermonkey/tampermonkey/issues/640#issuecomment-462615761).

Can someone that is seeing the warning please execute the following at Tampermonkey's background page console:

```JavaScript
chrome.permissions.getAll(function(e) { console.log('getAll', e.origins.join(' | ')) });
chrome.permissions.contains({ origins: ['<all_urls>'] }, function(r) { console.log('contains', r); });
```

Thanks.

**Comment by trlkly** [comment] 2019-02-13 16:45
@derjanb 

getAll <all_urls> | chrome://favicon/* | file:///* | http://*/* | https://*/*

contains false

**Comment by trlkly** [comment] 2019-02-13 16:48
Additional information, if relevant:

when I enable file URLs and Incognito mode, that last line changes to `contains true`, and the problem goes away.

If I then disable file URLs and Incognito mode, it changes back to `contains false`. However, the error remains gone. 

The first line never changes.

**Comment by derjanb** [comment] 2019-02-13 18:58
```contains false``` OK, so this is the culprit. :-( Even though the permission is granted (getAll returned it), contains returns false.

**Comment by trlkly** [comment] 2019-02-13 19:03
As I said in my previous post, I think using contains on *://*/* is the better check. It returns false if Tampermonkey does not have all_site permissions. But it returns true when it does.

**Comment by derjanb** [comment] 2019-02-13 20:28
The good news is that this is kind of a cosmetic issue. If Tampermonkey believes the <all_urls> permission is not granted, then it is going to check the permission for every origin it wants to access. This check works as expected and therefore there should be no negative effect besides the warning.

Chromium bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=931816

**Comment by trlkly** [comment] 2019-02-14 07:03
@derjanb As a cosmetic issue, is there any way to hide it without enabling the file:\/\/\/ permissions?

**Comment by derjanb** [comment] 2019-02-14 07:29
Sure, but this will hide all warnings and not only this one!

Set "Config Mode" to Advanced and add this to the "Custom CSS" option:

```CSS
.action.status .global_hint_warning {
    display: none;
}
```

then press "Save".

**Comment by mikolajek** [comment] 2019-02-14 09:13
It looks the issue is gone with TM 4.8.

**Comment by derjanb** [comment] 2019-02-14 12:58
@mikolajek No, it just shows the message if the first request needs to be done.

BTW: the latest TM beta version contains a workaround.

**Comment by heronils** [comment] 2019-02-18 15:18
Sorry to say that but my HATE for these security masturbators which constantly step in my flow with nag messages is deep and pure. Its worse than ad spam, because for ads there is uBlock. Where is the uBlock for this type of spam? WHY CANT THEY TELL ME JUST ONCE? Whats wrong with these browser devs? This must be very evil people. PAIN.

**Comment by dBsooner** [comment] 2019-02-26 15:07
@derjanb I am running the latest TM beta as well as the latest Chrome production (not beta) and I am having issues with updating scripts. I have the settings set to "all sites", but 50% of the time, updating the scripts just gives a spinning wheel. If I kill all chrome windows, then open Chrome and immediately run an "update", I can get them to update. But after some time, updates stop working.

**Comment by chainofhonor** [comment] 2019-03-01 07:53
[https://github.com/chainofhonor/-/blob/master/%E6%B2%B9%E7%8C%B4%E5%85%81%E8%AE%B8%E8%AE%BF%E9%97%AE%E6%96%87%E4%BB%B6%E7%BD%91%E5%9D%80.png](url)

把这个选项勾上就行了

**Comment by nathgit** [comment] 2019-03-02 09:09
I have the same message as @ayanamist running Chrome OS 72 & GM 4.8 but scripts still appear to be working. Read and change site data is enabled on all sites.

**Comment by heronils** [comment] 2019-03-02 16:21
I use Iridium now. No orange nag message. Ungoogled Chromium may also be a solution, did not test.

**Comment by trlkly** [comment] 2019-03-02 17:01
@nathgit As stated above, you can work around the issue by right clicking on the button, and choosing Manage Extensions, and then enabling file:// URL access.

**Comment by heronils** [comment] 2019-03-06 01:40
@trlkly I had access to file urls enabled in chrome, but then also, when using @grant GM.xmlHttpRequest in a script and making Ajax requests to loacalhost, then i got the orange nag messages.

Iridium will not show these.

**Comment by yangshuairocks** [comment] 2019-03-12 09:19
> @nathgit As stated above, you can work around the issue by right clicking on the button, and choosing Manage Extensions, and then enabling file:// URL access.

Thank you. This works!

**Comment by Codes-of-Louis** [comment] 2019-03-13 00:48
> @nathgit As stated above, you can work around the issue by right clicking on the button, and choosing Manage Extensions, and then enabling file:// URL access.

Works

**Comment by dBsooner** [comment] 2019-03-13 00:50
I found out my issue was because of Google Sync. When I had that enabled, it was actually what caused TamperMonkey to stop updating. Google Sync was getting hung. Like I said, it worked fine if you did it right upon opening Chrome, but stopped working sometime there after. Disabling Google Sync completely fixes the issue.

**Comment by DevDavido** [comment] 2019-03-19 11:16
🔥If anyone running into this warning on Chrome:
It appears due to the [changed user restricted access](https://developer.chrome.com/extensions/runtime_host_permissions) and can be dismissed by navigating to menu -> More tools -> [Extensions](chrome://extensions/) -> Tampermonkey -> Details -> Enable Allow access to file URLs.
Reload Tampermonkey and you're good to go!

**Comment by wy-luke** [comment] 2019-03-21 08:02
![批注 2019-03-21 160107](https://user-images.githubusercontent.com/25719685/54739307-91b15e80-4bf2-11e9-9f01-45765ed1b894.png)

in chrome extension setting, after i grant this permission, the message disappear..

**Comment by N1N74** [comment] 2019-03-21 13:57
In chrome Extension settings, enabling "Allow access to file URLs" got rid of it for me

**Comment by bruiseviolet** [comment] 2019-03-26 22:36
> I may have figured something out.
> 
> I right clicked on Tampermonkey and chose "Manage Extensions." There I enabled everything I normally enable: allowing Tampermonkey access to file:// URLs and access in Incognito mode. I also, for good measure, moved it from "On all sites" to "On click" and back.
> 
> (I note that doing what was described in vikaspotluri123's post did not work.)
> 
> Upon refreshing a website in another tab, the error was gone, and did not recur even after closing the profile and then launching it again.

This worked for me!  Thanks

**Comment by hackdapp** [comment] 2019-03-27 03:49
1. visit the extension 
    [chrome://extensions/?id=dhdgffkkebhmkfjojejmpbldmpobfkfo](chrome://extensions/?id=dhdgffkkebhmkfjojejmpbldmpobfkfo)

2. turn on the button ***"Allow access to file URLs"***
    ![](http://cdn.hackdapp.com/2019-03-27-034825.jpg)

**Comment by trlkly** [comment] 2019-03-27 03:52
Is there any way to close this so we don't keep getting the same workaround
posted over and over again?

**Comment by wodim** [comment] 2019-04-11 23:08
Even though I understand (after reading this conversation) what the problem is and what the solution might be, I think the warning that is shown should be improved. As it is, it doesn't say what the problem is or how it could be solved. Even a link back to this issue might be of help.

**Comment by danielsamuels** [comment] 2019-04-24 09:00
Chrome 74 (which fixes [the linked Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=931816)) is now generally available.

**Closed** 2019-04-24 09:01 UTC
Labels: external, fixed at beta

**Comment by ThatRAZOR11** [comment] 2021-03-10 11:20
> On chrome 73 Canary/Dev on both Linux and windows using the latest dev version of Tampermonkey im getting this yellow banner at the top of the tampermonkey settings:
> 
> "Limited runtime host permissions might break some Tampermonkey features like script update, GM_xmlhttpRequest and others!"
> 
> Initial setup and sync enabling worked after 2 fresh browser installs and it grabbed the scripts I had on the cloud, but right after that message popped up.
> 
> Anyone know what this error is about and how to fix it?

Go to extensions<three dots at Tampermonkey icon<This can read ad change site data<Click "On all websites" 
It worked for me. :)
