### ISSUE TITLE
Malfunctional Interface of Tampermonkey on Safari

### ISSUE THREAD

**Issue by stars-island** [Tampermonkey/tampermonkey#1662] opened 2022-11-30 08:12 UTC
(Please fill out the issue template with your details)

## Expected Behavior
It should be smoothly displaying all elements and functions. 

## Actual Behavior
Some functional pages like asking permissions of script are unable to display. And it cannot be scrolled the extension page. Screenshots show as below. 

![photo_2022-11-30_08-01-27](https://user-images.githubusercontent.com/66160777/204741585-6d2f604d-0cf3-48d8-8e85-9dc5d4c3d419.jpg)

![Screen Recording 2022-11-30 at 08 00 21 00_00_00-00_00_30](https://user-images.githubusercontent.com/66160777/204741558-2ed056bd-7c12-4aa8-b8cc-e182ba4fa1f7.gif)

## Specifications

- Safari: 16.1 (18614.2.9.1.12)
- TM: 4.17.6162
- OS: MacOS Ventura 13.0.1

## Script NOT APPLICABLE

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment] 2024-06-06 07:12
Duplicate of #1872

**Closed by derjanb** 2024-06-06 07:12 UTC
Labels: safari
