### ISSUE TITLE
[Browser Sync] Deleted userscripts keep coming back

### ISSUE THREAD

**Issue by jangxx** [Tampermonkey/tampermonkey#1501] opened 2022-05-03 10:20 UTC
## Expected Behavior

I delete a userscript and the change is synced to all devices via the settings sync.

## Actual Behavior

I've deleted some userscripts dozens of times but they keep getting reinstalled, so there seems to be some issue with the settings sync.

## Specifications

- Chromium: Since forever, probably like v70 or something
- TM: 4.16 (but also loads of older versions)
- OS: Linux, Windows, macOS

**Comment by derjanb** [comment] 2022-05-30 08:39
Duplicate of #879

**Comment by jangxx** [comment] 2022-05-30 10:58
How is this a duplicate if you explicitly say in the liked issue that the browser sync is not related? My issue is specifically about browser sync, so this seems to be a different problem then and not a duplicate.

**Comment by derjanb** [comment] 2022-05-30 11:42
I see. Sorry. Could you please check the sync internals as suggested at this post: https://github.com/Tampermonkey/tampermonkey/issues/879#issuecomment-662512731

**Comment by devnull69** [comment] 2023-12-07 08:27
Can you please shed some updated light on this? I still also have this issue ... and it is annoying. Is there anything I can do about it?

**Comment by derjanb** [comment] 2023-12-07 08:39
Please try to find the script at "chrome://sync-internals/" at the "Sync Node Browser" tab and attach its value. 

* First find the right UUID at the script's settings page:

![image](https://github.com/Tampermonkey/tampermonkey/assets/767504/5498779b-0ba0-4caf-9f0c-7b9d61a9a40e)

* Then search this UUID at the "Sync Node Browser" > "Extension Settings". Thanks.

![image](https://user-images.githubusercontent.com/767504/88193995-9484ef00-cc3e-11ea-8abd-d2dc9b00b9b6.png)

**Comment by devnull69** [comment] 2023-12-07 09:12
I don't have any of those GUID entries under Extension settings ...

All of the entires are clear text names

**Comment by derjanb** [comment] 2024-01-31 19:20
> So should Google Drive sync also sync the deletion of scripts? 

Yes, it should.

**Comment by derjanb** [comment] 2024-02-05 19:05
Duplicate of #879

**Closed by derjanb** 2024-02-05 19:05 UTC
Labels: feedback needed
