### ISSUE TITLE
Feature request: Please add @external to load local .js files from external editor

### ISSUE THREAD

**Issue by yerb** [Tampermonkey/tampermonkey#858] opened 2020-01-21 09:19 UTC
I would like to propose a feature that loads external .js files for the purpose of using external editor.
Either trough @require and additional script option to disable caching or @external that would have its own rules.

For security measure @external would only allow file://, http://localhost or http://128.0.0.1 to be accepted.

Is it possible? Or is it there a solution that I don't know about.

**Comment by derjanb** [comment] 2020-01-21 10:04
Duplicate of #475 or #723

**Closed by derjanb** 2020-01-21 10:04 UTC

**Comment by derjanb** [comment] 2026-04-10 14:05
You can now [make the editor track a local file](https://github.com/Tampermonkey/tampermonkey/issues/2722#issuecomment-4177792617) (File > Track from disk; Chrome+MS Edge Only)
