### ISSUE TITLE
Popup ads are bad mkay

### ISSUE THREAD

**Issue by MrStonedOne** [Tampermonkey/tampermonkey#821] opened 2019-11-26 19:08 UTC
(Please fill out the issue template with your details)

## Expected Behavior
I open chrome and only the newtab page shows.

## Actual Behavior
I open chrome and TM opens a popup tab to `https://www.tampermonkey.net/changelog.php?version=4.9&ext=dhdg&updated=true&old=4.8.41&intr=true`

## Specifications

- Chromium: (i.e. 77.0.3865.120)
- TM: (i.e. 4.9)
- OS: Windows 7

Please make your popup tabs opt-in and not opt-out.

**Comment by derjanb** [comment] 2019-11-26 19:10
Duplicate of #820

**Closed by derjanb** 2019-11-26 19:10 UTC
