### ISSUE TITLE
`@grant GM_webRequest` false positive error message

### ISSUE THREAD

**Issue by Malix-Off** [Tampermonkey/tampermonkey#1746] opened 2023-03-21 08:49 UTC
## Proof

![image](https://user-images.githubusercontent.com/76160668/226483327-12620435-954a-4ef7-9f39-1b181cef6c82.png)

## Links

- ### Discovery
  https://github.com/lisonge/vite-plugin-monkey/issues/64

- ### Related Issue
  #397

**Comment by derjanb** [comment] 2023-03-21 10:30
@7nik Tampermonkey uses [a forked more Tampermonkey-centric version](https://github.com/derjanb/eslint-plugin-userscripts)

**Comment by Malix-Off** [comment] 2023-03-21 11:00
I couldn't create an issue on [derjanb/eslint-plugin-userscripts](https://github.com/derjanb/eslint-plugin-userscripts) so I created it here instead

**Comment by derjanb** [comment] 2023-03-21 19:47
Closing as duplicate of https://github.com/Tampermonkey/tampermonkey/issues/1694

**Closed by derjanb** 2023-03-21 19:47 UTC
Labels: bug

**Comment by Malix-Off** [comment] 2023-03-21 20:21
_i know this is not relevant there and you can delete that right away, but can someone answer #1745 pls?_
