### ISSUE TITLE
No script is running on Chrome Webstore

### ISSUE THREAD

**Issue by nicoleahmed** [Tampermonkey/tampermonkey#1835] opened 2023-08-14 21:38 UTC
## Expected Behavior
Navigate to Chrome Webstore and script is run

## Actual Behavior
Navigate to Chrome Webstore and script is not run
test page: https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
Similar script for different site works fine on tampermonkey.
Have tried using match and include
Have disabled/enable and removed/reinstalled extension
Tampermonkey shows "no script is running"

## Specifications
- Chrome Version 115.0.5790.171 (Official Build) (64-bit)
- TM: 4.19.0
- OS: Windows 10 64 bit

## Script

```js
// ==UserScript==
// @name         chromestore hello world
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include      *chrome.google.com/webstore/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=google.com
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    alert('Hello, World!');
})();
```

**Comment by 7nik** [comment] 2023-08-15 07:16
Duplicate of #1226

For security reasons, no one extension can be run on Chrome Webstore pages, as well as browser settings and other internal pages.

I think I told it, though I don't remember where, but TM probably should say something like "scripts cannot be run on this page" for the protected pages.

**Closed** 2023-08-15 12:41 UTC
