### ISSUE TITLE
Editor box height too small in Android Kiwi Browser

### ISSUE THREAD

**Issue by ScamCast** [Tampermonkey/tampermonkey#1571] opened 2022-08-08 14:08 UTC
The height of the editor box is not correct on the Android Kiwi Mobile Browser.

<img src="https://user-images.githubusercontent.com/56202326/183433725-55060ffd-5238-4617-9dca-bd01993ed5fc.png" width="40%" height="40%">

It appears to be something to do with the meta viewport tag inside the body.
<img src="https://user-images.githubusercontent.com/56202326/183435703-486c50c1-b5d7-47b2-9a37-85a634d5974c.png" width="40%" height="40%">

When I add "initial-scale=0", it makes the page more usable.
<img src="https://user-images.githubusercontent.com/56202326/183435853-28fe1b91-687f-4c89-b35b-253c740ec11f.png" width="40%" height="40%">
<img src="https://user-images.githubusercontent.com/56202326/183435892-f7bb5f03-32fb-4807-b203-52d240b86fd4.png" width="40%" height="40%">

Otherwise, I don't know what the real issue could be.

**Samsung Galaxy S10+**
**Kiwi Browser 101.0.4951.40**
**Tampermonkey 4.16.1**

**Comment by and3rson** [comment] 2023-08-25 23:12
Any updates? Unfortunately, the extension is still unusable in Kiwi browser because of this issue.

**Comment by Spork-Schivago** [comment] 2023-11-25 00:42
I can confirm that this is a bug that I too am experiencing with Kiwi and could not find a solution that resolved this issue.   Thanks.

**Comment by derjanb** [comment] 2024-10-05 17:53
Closing in favor of #2048

**Closed by derjanb** 2024-10-05 17:53 UTC
Labels: bug, external
