### ISSUE TITLE
[Firefox] side toolbar menu has too much white space

### ISSUE THREAD

**Issue by SakhJack** [Tampermonkey/tampermonkey#1204] opened 2021-04-03 18:01 UTC
## Expected Behavior
menu has just enough space to fit UI, as usual

## Actual Behavior
menu contains white space below and above UI, forcing user to scroll for access

## Screenshots
<details><summary>regular menu on main toolbar</summary>

![image](https://user-images.githubusercontent.com/10335530/113487103-98436380-94a5-11eb-8b04-75f224b03afd.png)
</details>
<details><summary>bugged menu on side toolbar</summary>
  
![image](https://user-images.githubusercontent.com/10335530/113487067-6d590f80-94a5-11eb-9df2-68c93cbd0939.png)
</details>

## Specifications

- Browser: Firefox 87.0 x64 (fresh profile, no other add-ons)
- TM: 4.12.6132
- OS: Windows 10 x64

**Comment by derjanb** [comment] 2021-04-03 18:45
Duplicate of #1181 and please see https://github.com/Tampermonkey/tampermonkey/issues/1181#issuecomment-801691889 for a workaround. It is also fixed at the [latest BETA version](https://www.tampermonkey.net/?browser=firefox).

**Closed by derjanb** 2021-04-03 18:45 UTC
