### ISSUE TITLE
@match and @include don't march 「#」 mark and any text after the mark

### ISSUE THREAD

**Issue by ballban** [Tampermonkey/tampermonkey#1274] opened 2021-06-24 16:15 UTC
## Actual Behavior
Both [match] and [include] can't match # mark and any text after this mark.
test url: https://blank.page/1?a=1#test
match pattern: *://*/*test*
include pattern: /^.*test.*$/
Change [test] to [a=1], it works.

I don't remember the specific date, but it works fine before.(before 1 or 2 months)

## Specifications

- Chromium: 91.0.4472.114
- TM: 4.13
- OS: Windows 10 Pro 20H2

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         test
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://*/*test*
// @include      /^.*test.*$/
// @grant        none
// ==/UserScript==
(function() {
    alert('matched');
})();
```

**Comment by derjanb** [comment] 2021-06-24 18:06
Duplicate of #584 

Make `@match` contain the URL without the hash and check it when the script is executed. In case you want to listen for changes use [`window.onurlchange`](https://www.tampermonkey.net/documentation.php#_grant)

**Closed by derjanb** 2021-06-24 18:06 UTC
