### ISSUE TITLE
[bug] Breaks page rendering in Safari 18 in Sequioa Beta 3 (and 4)

### ISSUE THREAD

**Issue by MysticalOS** [Tampermonkey/tampermonkey#2120] opened 2024-07-10 23:03 UTC
(Please fill out the issue template with your details)

## Specifications

- Safari 18.0 (20619.1.20.11.1)
- TM: 5.2.6199
- OS: macOS 15.0 Beta 3

Simply load up reddit.com or google.com and notice following bugs
Reddit: Site bars completely missing
Google: search bar is oversized and toolbar is missing on search pages.
WarcraftLogs: It breaks sytlesheets on WCL causing rendering alignment and color issues such as on this page https://www.warcraftlogs.com/reports/gTr3Lx7Zkn9XFqjv#fight=25&pins=2%24Off%24%23244F4B%24expression%24ability.name%20%3D%20%22Berserk%22&view=events

Other sites possibly broken too unsure.

Of note, Issues did not occur on Safari 18 included in beta 2, so beta 3 changed something that TM is interfering with.

Work Around:
Simply deny TM access on specific sites it breaks.

**Comment by Jagerx** [comment] 2024-07-16 06:45
Yes, the same bugs here on Google
![2024-07-16_14-38-15](https://github.com/user-attachments/assets/55062d8f-98e5-434d-b371-f48e254e2f46)

**Comment by syouSui** [comment] 2024-07-24 02:17
Not only the problem google search bar oversized(scrennshoot1), but only font color display incorrectly like white font be displayed black on  reddit.com/hdtime.org (scrennshoot2). And web layout confusion(screenshoot2).

scrennshoot1:
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/7b8e0561-81b5-4816-9a44-ba82df57e083">


scrennshoot2:
<img width="938" alt="image" src="https://github.com/user-attachments/assets/eed7ae3f-a49f-425d-8f0d-f61ef04db8df">
<img width="885" alt="image" src="https://github.com/user-attachments/assets/dcad9e57-67f6-4780-8d85-d2b154ea638d">



scrennshoot3:
<img width="1062" alt="image" src="https://github.com/user-attachments/assets/09d85423-ba54-4291-84ef-099a3e342b7d">
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/970e45fd-15d9-4864-b458-061d38601647">

**Comment by syouSui** [comment] 2024-07-24 02:18
Including but not limited to the above issues

**Comment by foxhatleo** [comment] 2024-07-28 02:03
It seems that the "style.css" and "editor.css" of Tampermonkey is being picked up by Safari and leaked into the main environment. "style.css" has a bunch of really common class names such as ".hide" that interferes with layout if the website happens to use the same class name.

**Comment by JCDC85** [comment] 2024-07-28 17:18
I'm having the same issue. It took me forever to find out it Tampermonkey itself, as I assumed disabling all my scripts would be sufficient to test for that, but it was not. Ivermectin erased all scripts, uninstalled, reinstalled, and reset to factory default, but it still does it. I had issues well before ever upgrading to MacOS 15 Beta, though. I switched to the "Userscripts" safari extension for a few weeks, but it wasn't loading about 10% of my scripts correctly. I wanted to switch back to Tamper.
<img width="1272" alt="Screenshot 2024-07-28 at 1 17 19 PM" src="https://github.com/user-attachments/assets/f430bfe7-fda3-4542-b61a-c6f421c885ca">
<img width="1424" alt="Screenshot 2024-07-28 at 1 17 48 PM" src="https://github.com/user-attachments/assets/f7df0812-277f-4eac-a542-209a6fa5ceee">
<img width="1174" alt="Screenshot 2024-07-28 at 1 18 03 PM" src="https://github.com/user-attachments/assets/149f2824-8aba-4729-9152-a515f2ee13e2">
<img width="1469" alt="Screenshot 2024-07-28 at 1 18 09 PM" src="https://github.com/user-attachments/assets/93068fe9-0615-4829-8b5f-c08056b35305">

**Comment by derjanb** [comment] 2024-07-28 18:56
I can reproduce this as Safari 18. Unfortunately this is a Safari bug. The only workaround for now is to modify Tampermonkey's website permissions. Please set "For other websites" to "Ask" (as seen at the bottom right at the screenshot) and the issue should be fixed.

![image](https://github.com/user-attachments/assets/3474ab15-affb-430d-8d90-13efeab4e2c5)

**Comment by derjanb** [comment] 2024-07-28 19:09
https://bugs.webkit.org/show_bug.cgi?id=277232

**Comment by JCDC85** [comment] 2024-07-28 21:08
> I can reproduce this at Safari Technology Preview 18.
> 
> Unfortunately this is a Safari bug.
> 
> The only workaround for now is to modify Tampermonkey's website permissions. Please set "For other websites" to "Ask" (as seen at the bottom right at the screenshot) and the issue should be fixed.
> 
> ![image](https://private-user-images.githubusercontent.com/767504/352861118-3474ab15-affb-430d-8d90-13efeab4e2c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMDExMTYsIm5iZiI6MTcyMjIwMDgxNiwicGF0aCI6Ii83Njc1MDQvMzUyODYxMTE4LTM0NzRhYjE1LWFmZmItNDMwZC04ZDkwLTEzZWZlYWI0ZTJjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQyMTA2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTE4ZmVmNGU0NTU0MzY4YzJiZWNlZTQwZDMxZmFkNTc3NmQ2OGFmZWViZmVlNzkwYWRmMGRlMDM3MmFkYmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R414mgg3nouAWmyO4mO1IuzCp1avipcmsXjeSlmJhYk)

Thank you for the workaround; very much appreciated.  My Google search bar and text coloring are back to normal.

**Comment by foxhatleo** [comment] 2024-07-28 21:17
> I can reproduce this at Safari Technology Preview 18.
> 
> Unfortunately this is a Safari bug.
> 
> The only workaround for now is to modify Tampermonkey's website permissions. Please set "For other websites" to "Ask" (as seen at the bottom right at the screenshot) and the issue should be fixed.

The workaround unfortunately wouldn't work if it breaks a website that I also want to inject a script into. Nice to hear that the bug is reported to Webkit. I hope they fix it soon, otherwise the only thing I can think of is to rename all the class names to uncommon names or add a prefix (so ".hide" becomes ".tampermonkey_hide" or something)

Let's hope that WebKit fixes this soon.

**Comment by MysticalOS** [comment] 2024-07-28 21:20
Actually it does work for sites you are injecting into. I tested it on all sites that broke before and the bleed of the css style sheet ONLY Happens when it's set to allow on all sites. once I set it to ask, and set it to allow only on specific urls, the bug went away, including on sites it's modifying. i actually didn't set mine to ask at all i set it to deny then manually set to allow on ui.tampermonkey.net and then the sites I was using (authorizing on ui site is important or dashboard won't work)

**Comment by foxhatleo** [comment] 2024-07-28 21:29
> Actually it does work for sites you are injecting into. I tested it on all sites that broke before and the bleed of the css style sheet ONLY Happens when it's set to allow on all sites. once I set it to ask, and set it to allow only on specific urls, the bug went away, including on sites it's modifying. i actually didn't set mine to ask at all i set it to deny then manually set to allow on ui.tampermonkey.net and then the sites I was using (authorizing on ui site is important or dashboard won't work)

Oh I see, you have to explicitly allow it on the websites you want to inject/modify, and keep everything else "Ask". Thanks for the clarification.

**Comment by MuaiyadTSB** [comment] 2024-07-30 11:20
```diff
- [bug] Breaks page rendering in Safari 18 in Sequioa Beta 3 (and 4)
+ [bug] Breaks page rendering in Safari 18 on Sequioa 15 Beta (3,4) & 15.1
```

**Comment by MuaiyadTSB** [comment] 2024-08-01 09:08
> ```diff
> - [bug] Breaks page rendering in Safari 18 in Sequioa Beta 3 (and 4)
> + [bug] Breaks page rendering in Safari 18 on Sequioa 15 Beta (3,4) & 15.1
> ```

The issue seems to be resolved in latest safari technology preview (release 200).

**Closed as completed** 2024-09-11 14:17 UTC
Labels: bug, safariapp
