### ISSUE TITLE
not working with new firefox

### ISSUE THREAD

**Issue by swathigrate** [Tampermonkey/tampermonkey#1021] opened 2020-08-25 03:18 UTC
(Please fill out the issue template with your details)

## Expected Behavior
Actually not showing in addon list in firefox

## Actual Behavior
![Screenshot_2020-08-25-08-47-05-167_org mozilla firefox](https://user-images.githubusercontent.com/14991260/91118923-8f71f000-e681-11ea-8d76-e53fa387f7b3.jpg)

## Specifications

- firefox 79.0.5
- TM: (i.e. 4.5.5648)
- OS: android 7

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by fdellwing** [comment] 2020-08-26 04:58
I'm not sure if the developer has anything to say in this. But if he has some more information on when it will work again that would be helpful. TM is the only reason I even use FF on Android.

**Comment by derjanb** [comment] 2020-08-26 07:25
Duplicate of #940

**Closed by derjanb** 2020-08-26 07:25 UTC
