### ISSUE TITLE
GM_deleteValue function is not working as design

### ISSUE THREAD

**Issue by max-tian** [Tampermonkey/tampermonkey#624] opened 2018-12-12 09:10 UTC
## Expected Behavior
GM_deleteValue should work as design.

## Actual Behavior
GM_deleteValue is not working.

## Specifications
Use it in any web-site and any UserScripts.

- Chromium: 70.0.3538.110 
- TM: 4.7.44
- OS: 10.13.6

## Script
```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant GM_setValue
// @grant GM_deleteValue
// ==/UserScript==
GM_setValue('test', true);
GM_deleteValue('test');
```

## Screenshots
![screen shot 2018-12-12 at 16 53 53](https://user-images.githubusercontent.com/4463267/49858774-d3cb4700-fe30-11e8-8eb9-abda6dbf95b5.png)

**Comment by derjanb** [comment] 2018-12-12 09:19
Duplicate of #623 

This https://github.com/Tampermonkey/tampermonkey/issues/623#issuecomment-446512421 is the fix for you problem!

**Closed by derjanb** 2018-12-12 09:19 UTC
