### ISSUE TITLE
Strange UI behavior: huge empty space in the Tampermonkey menu with Firefox

### ISSUE THREAD

**Issue by roger21** [Tampermonkey/tampermonkey#1219] opened 2021-04-16 18:50 UTC
## What I did

I added some scripts to Tampermonkey for the same website and the Tampermonkey menu became weird with a huge empty space at the top (see gif below).

When I removed the scripts the menu became normal again.

It could be linked to the amount of scripts for the same website (since I have a bunch for this one) but the adding/removing is not consistent with a specific number of script, sometime only one script is enough to see the bug appear/disappear sometimes more are needed (maybe related to the script position/number too but i couldn't find out a consistent pattern either).

![tampermonkey](https://user-images.githubusercontent.com/892186/115066207-7a3b2180-9eef-11eb-99a9-2cfbddafb2f6.gif)

## Expected Behavior

open the Tampermonkey menu
see the global enable/disable option
see the list of scripts for the current website
see the rest of the menu

## Actual Behavior

open the Tampermonkey menu
**see a huge empty space**
see the global enable/disable option
see the list of scripts for the current website
see the rest of the menu

## Specifications

- Firefox: (87.0)
- TM: (4.12.6132)
- OS: (Windows 10)

**Comment by derjanb** [comment] 2021-04-16 19:02
Duplicate of #1181 and please see https://github.com/Tampermonkey/tampermonkey/issues/1181#issuecomment-801691889 for a workaround. It is also fixed at the [latest BETA version](https://www.tampermonkey.net/?browser=firefox).

**Closed by derjanb** 2021-04-16 19:02 UTC
