### ISSUE TITLE
setInterval Not Working

### ISSUE THREAD

**Issue by natesreich** [Tampermonkey/tampermonkey#356] opened 2017-02-13 00:34 UTC
### **What's the issue?**

- I am trying to simulate a mobile device's sensors on desktop
- On mobile, these values are constantly refreshing: http://sendvid.com/vo18o2kg
- On desktop, TamperMonkey sets the value on only the first page load or if I switch back tabs to it: https://sendvid.com/z6sjb6f8

### **How can I recreate the issue?**

- Please create the following Userscript:
```
// ==UserScript==
// @name        Mobile
// @namespace   Mobile
// @description Mobile
// @version     1
// @run-at      document-start
// @match      *://*/*
// ==/UserScript==

var timerVar    = setInterval (function() {Timeout (); }, 5);

function Timeout ()
{
    Object.defineProperty(DeviceMotionEvent.prototype, 'accelerationIncludingGravity', { value : {x: (Math.random() * 1), y: (Math.random() * 1), z: -(Math.random() * 10)} });
    Object.defineProperty(DeviceMotionEvent.prototype, 'rotationRate', { value : {alpha: (Math.random() * 1), beta: (Math.random() * 1), gamma: -(Math.random() * 10)} });
    Object.defineProperty(DeviceOrientationEvent.prototype, 'alpha', { value : (Math.random() * 361)});
    Object.defineProperty(DeviceOrientationEvent.prototype, 'beta', { value : (Math.random() * 361)-180});
    Object.defineProperty(DeviceOrientationEvent.prototype, 'gamma', { value : (Math.random() * 181)-90});
}

Timeout();
```
- Then visit this URL: http://albertosarullo.com/demos/accelerometer/
- The values will only update if you switch tabs and go back to it

###  **How do I know JS is not the issue?**
- Please test it here: https://jsfiddle.net/natesreich/rng1xqvd/
- You will notice that the Console Log is updating every few seconds with a new value

**Comment by tophf** [comment] 2017-02-13 01:43
Chrome [throttles background timers](https://www.google.com/search?q=Chrome%2056%20Will%20Aggressively%20Throttle%20Background%20Tabs) as of v56.

**Comment by natesreich** [comment] 2017-02-13 22:55
Thank you for the quick response.

I have rooted out the Chrome v56 update as the cause: http://sendvid.com/v0284n8q

**Comment by derjanb** [comment] 2017-02-15 20:29
OK, then I'll close this.

**Closed by derjanb** 2017-02-15 20:29 UTC

**Comment by natesreich** [comment] 2017-02-15 23:35
Since I rooted out the Chrome v56 update as the cause, TamperMonkey definitely has an issue. :)

Sorry if my last message caused any confusion.

**Comment by derjanb** [comment] 2017-02-16 15:15
The "problem" is that the DeviceMotion event at a desktop Chrome only fires when the page is loaded or the tab is selected. Since device motion of a desktop PC is rather unusual, I guess this is intended behavior.

It looks like you're trying to generate DeviceMotion events by modifying DeviceMotionEvent.prototype, right? This will not work. I haven't checked if it's possible, but you need to do something that is closer to this approach: http://stackoverflow.com/questions/596481/is-it-possible-to-simulate-key-press-events-programatically#answer-839635

**Comment by natesreich** [comment] 2017-02-21 04:24
Thank you. Looks like the issue is indeed on my end.
