### ISSUE TITLE
 @match works only if page is reloaded or opened in new tab/window 

### ISSUE THREAD

**Issue by kyxap** [Tampermonkey/tampermonkey#1897] opened 2023-11-15 21:58 UTC
## Steps to reproduce
0) Pit `Tampermonkey` plugin to your browser Tool Bar for visibility 
1) Open `https://www.linkedin.com/jobs/`
2) Click on Show All (you will be redirected to `https://www.linkedin.com/jobs/collections/recommended/*`)
3) Observe Plugin Icon on Tool Bar, very script is working

## Expected Behavior
`Tampermonkey` plugin shows Icon and `1` on it which indicates there 1 active script 
![image](https://github.com/Tampermonkey/tampermonkey/assets/3080529/72d70d96-8a3d-4998-bd3f-5d2d75ae1d2f)
This is working

## Actual Behavior
`Tampermonkey` plugin does not show that there any active scripts 
![image](https://github.com/Tampermonkey/tampermonkey/assets/3080529/18f1f46e-b555-4a7a-9298-9ab5fd77981e)
This does not work

## Specifications

- FF 119.0.1 (64-bit)
- OS: win 11

## Script
Full script: 
[(Please give an example of the script if applicable.)
](https://github.com/kyxap/tampermonkey-userscripts/blob/main/linkedin/Easy%20Apply%20--%20make%20it%20even%20easier.user.js)

But you can do something like this without actual js in it

```javascript
// ==UserScript==
// @name         Easy Apply -> make it even easier
// @version      0.0.6
// @description  Makes "Easy Apply" actually easy: 1) auto uncheck company to follow 2) closes pop after submit
// @author       kyxap | https://github.com/kyxap
// @match        https://www.linkedin.com/jobs/search/*
// @match        https://www.linkedin.com/jobs/collections/recommended/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=linkedin.com
// @grant        none
// ==/UserScript==

(function () {
    'use strict';
})();
```

**Comment by 7nik** [comment] 2023-11-15 22:23
`@math`? Did you mean `@match`?

`https://www.linkedin.com/jobs/` doesn't match any `@match` from the script, and if happens soft navigation to any page, the script won't be loaded either. Userscripts get loaded only at hard navigation.

You can try to match `https://www.linkedin.com/*` and use [onurlchange](https://www.tampermonkey.net/documentation.php?ext=fire&version=4.19.0#api:window.onurlchange) event to run your code on the target pages. 

However, in such cases, I check the presence of the target element and ignore url.

**Comment by kyxap** [comment] 2023-11-15 22:32
> `@math`? Did you mean `@match`?
yeah, fixed

> `https://www.linkedin.com/jobs/` doesn't match any `@match` from the script, and if happens soft navigation to any page, the script won't be loaded either. Userscripts get loaded only at hard navigation.
yeah it does not, the idea is to navigate to one those:
```bash
// @match        https://www.linkedin.com/jobs/search/*
// @match        https://www.linkedin.com/jobs/collections/recommended/*
```
without opening page directly 
> You can try to match `https://www.linkedin.com/*` and use [onurlchange](https://www.tampermonkey.net/documentation.php?ext=fire&version=4.19.0#api:window.onurlchange) event to run your code on the target pages.
hm seems very tricky, how this will be different from using `document.URL` and do custom match and if match just execute the script?

**Comment by 7nik** [comment] 2023-11-15 22:46
But you cannot listen for changes of `document.URL`.

```js
// @grant        window.onurlchange

function matchScript ({ url }) {
  if (url.startsWith("https://www.linkedin.com/jobs/search/") || url.startsWith("https://www.linkedin.com/jobs/collections/recommended/") {
    runScript();
  }
}

window.addEventListener("urlchange", matchScript);

matchScript({ url: location.href }); // check the initial location

function runScript () {
  // main code
}

**Comment by derjanb** [comment] 2023-11-16 15:03
Thanks @7nik 

Duplicate of https://github.com/Tampermonkey/tampermonkey/issues/1639#issuecomment-1310077826

**Closed** 2023-11-16 15:04 UTC

**Comment by kyxap** [comment] 2023-11-17 02:24
it does not work for me, `addEventListener` calls `matchScript` only 1 time, when I go for next time never triggers

**Comment by aliraza948** [comment] 2025-01-20 18:13
// ==UserScript==
// @name         LinkdIn
// @namespace    http://tampermonkey.net/
// @version      2025-01-18
// @description  try to take over the world!
// @author       You
// @match        https://www.linkedin.com/mynetwork/grow/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        window.onurlchange
// ==/UserScript==


function matchScript ({ url }) {
  if (url.startsWith("https://www.linkedin.com/mynetwork/grow/")) {
    runScript();
    }
}

window.addEventListener("urlchange", matchScript);

matchScript({ url: location.href }); // check the initial location

function runScript () {
  // main code
    alert(`good`)
}



that's my code and it doesn't work

**Comment by aliraza948** [comment] 2025-01-20 18:18
> Please use
> 
> ```
> // @match https://www.linkedin.com/*
> ```

Thanks for refine
