### ISSUE TITLE
Tampermonkey Extension Prompts Unexpected Overwrite Message on Saving Scripts

### ISSUE THREAD

**Issue by hmjz100** [Tampermonkey/tampermonkey#1932] opened 2023-12-10 07:57 UTC
## Expected Behavior

Utilize the Tampermonkey Editors extension to modify and save Tampermonkey scripts on the vscode.dev website. Tampermonkey should refrain from displaying any prompts and should automatically save the modifications.

## Actual Behavior

Upon using the Tampermonkey Editors extension to modify and save Tampermonkey scripts on the vscode.dev website, a window pops up each time, asking, "The script was locally modified at (time). Updating it will overwrite your changes!"

## Specifications

-Chromium: 102.0.5005.167
-TM: 5.0.0
-OS: Windows 11 22H2

## Script

Every script.

**Comment by jb222** [comment] 2023-12-14 11:49
When saving an unchanged script, this happens in the Tampermonkey editor as well.

**Comment by derjanb** [comment] 2023-12-14 22:09
Should be fixed at 5.0.6191 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx))

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by jb222** [comment] 2023-12-15 11:14
Can't speak for @hmjz100 but my problem in the editor is still there.
![Schermafbeelding 2023-12-15 om 12 12 38](https://github.com/Tampermonkey/tampermonkey/assets/61352184/6f906f7a-ee65-4c1b-93ca-e5b5530d4fd5)

**Comment by derjanb** [comment] 2023-12-15 11:48
Right, I fixed the message about script updates being disabled by local modifications... 

Can you please create a screencast? I don't get warnings when editing the code in VSCode.dev only in the local editor, where it is expected behavior.

VSCode updates the source on modifications by TM's own editor, but not the other way around. Therefore TM's editor warns that there was another modification that would be overwritten.

**Comment by hmjz100** [comment] 2023-12-15 12:12
Well, TM really won't prompt again, but repeatedly saving an unmodified script will still prompt

**Comment by jb222** [comment] 2023-12-15 12:13
I just noticed the warning is not displayed with every script save, apparently it depends on the script. 
Let me be clear: I disabled the Editors extension, I only use the TM editor.

**Comment by hmjz100** [comment] 2023-12-15 12:34
This situation will occur in both the TM editor and vscode.dev too
![1](https://github.com/Tampermonkey/tampermonkey/assets/98228280/5ccf8170-59bf-4f60-8e2d-ab2cadf77b40)

**Comment by jb222** [comment] 2023-12-15 12:43
> only in the local editor, where it is expected behavior.
Has this recently been changed? I only remember this warning displayed when saving a script in the TM editor while it was opened in a different window/tab at the same time.

**Comment by derjanb** [comment] 2023-12-15 19:43
> This situation will occur in both the TM editor and vscode.dev too

Indeed, this is the anticipated behavior. If you're editing a script across two different tabs, Tampermonkey provides a warning. It alerts you that if you attempt to save your changes from the other tab, the content may have been modified in the meantime.

If I use vscode.dev, then it updates the script code to the new value that was saved at the other tab and a following save does not trigger the warning. Not sure why this isn't happening for you.

> Has this recently been changed?

If so this was not intended, but I rewrote a lot of code for the upcoming extension API changes. 

> I only remember this warning displayed when saving a script in the TM editor while it was opened in a different window/tab at the same time.

Yes, so this happens to you when you open a script and modify it, without any other action in between?
Does this happen on Firefox?

**Comment by mandel99** [comment] 2023-12-16 03:42
I have same issue, this happening both in Chrome and Firefox when saving script edited or unedited (but not every time, i dont have opened another tab with TM editor and not using sync)

**Comment by jb222** [comment] 2023-12-16 13:35
> > I only remember this warning displayed when saving a script in the TM editor while it was opened in a different window/tab at the same time.
> 
> Yes, so this happens to you when you open a script and modify it, without any other action in between? Does this happen on Firefox? Do you have sync enabled?

As mentioned before (also by @mandel99) it happens with unmodified scripts. 

But.....  I just noticed: when clicking "save", a _new tab_ opens with the warning! Upon "cancel" or "modify", the second tab closes again. Hey, with 2 TM windows open, maybe the warning is no surprise?

BTW. See the screenshot: the new tab opens with a TM Install tab. Clicking "modify" solves the problem with that particular script. I don't know why it only happens with some scripts. 

![Schermafbeelding 2023-12-16 om 14 27 02](https://github.com/Tampermonkey/tampermonkey/assets/61352184/1453dc83-6848-40ed-81f7-b15c3fb19835)

**Comment by hmjz100** [comment] 2023-12-16 14:41
Sorry, there was an error in my previous screen recording operation. Now I have changed to the correct. It can be seen that this phenomenon occurs in both editors.
![1](https://github.com/Tampermonkey/tampermonkey/assets/98228280/bc371927-d48b-4cc1-8411-b0a9c2ef2c42)
![2](https://github.com/Tampermonkey/tampermonkey/assets/98228280/b7e94c44-f61c-4fd3-b1ca-683769d22367)

**Comment by mandel99** [comment] 2023-12-16 16:15
I found some odd behaviour, i edited and saved my script in TM editor in morning, then shut down computer. When i start working later on the script and **few times saved it without issue** then new tab appeared if i want modify the script that was saved in morning.

**Comment by 06000208** [comment] 2023-12-18 03:22
I've started getting the "The script was modified locally on ... Updating it will overwrite your changes!" popup excessively in the past few days.

- I am on firefox v120.0.1 and Tampermonkey v5.0.0
- I am not editing the script with multiple tabs.
- I am only using the built in editor and attempting to save my edits with ctrl+s
- My script does not have an update url
- Attempting to save without making any edits does cause the popup: The first save after an edit appears to save normally, and all saves afterwards start prompting that I will overwrite my changes, which is nonsense, because there haven't been any changes.
- I feel like I've gotten it on the first save after making an edit, but I could be mistaken, e.g. my script somehow getting saved twice in a row. I'll update this post if I experience it again.

**Comment by derjanb** [comment] 2023-12-18 08:42
Found the issue. Thanks for your help!

**Comment by derjanb** [comment] 2023-12-22 23:16
Should be fixed at 5.0.6192 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Closed** 2023-12-25 05:09 UTC
Labels: bug, fixed at beta
