### ISSUE TITLE
How to add/update an user script by drag & drop onto Chrome?

### ISSUE THREAD

**Issue by pstein** [Tampermonkey/tampermonkey#1549] opened 2022-07-12 05:19 UTC
I installed TM v4.16.1 in newest Chrome on Windows 10.

Then I opened TM extension with tab "Installed Userscripts"
Lets say a script "myfoobar" is currently NOT listed

Now I drag & drop a *myfoobar.user.js file from Windows File Explorer onto this tab.

What happens?

First of all the "myfoobar" page opens with the Tab "Changes".
Yes the changes to the previous version are correct. But this previous versions has been removed in the past.
There is currently no old version which can be compared with the just dragged.
So why does TM still remember this old version?
According to the tab "Installed Userscripts" there is none.

Next question:
Do I have to apply/install additionally this new version ?
How?

If I switch back to the Chrome tab with "Installed Userscripts" a popup is visible showing "Please wait".......forever

Wait for what?

**Comment by derjanb** [comment] 2022-07-25 07:12
Duplicate of #1284

Please disable trash to instantly delete scripts.

> Wait for what?

It should settle after some time after the script installation tab was closed...

**Closed by derjanb** 2022-07-25 07:12 UTC
