### ISSUE TITLE
Scripts Don't Execute Without Devtools Open

### ISSUE THREAD

**Issue by limitedAtonement** [Tampermonkey/tampermonkey#2193] opened 2024-09-18 13:09 UTC
I'm using Chromium on Arch Linux. I am new to TamperMonkey, so it's likely I'm just doing something wrong. Here is my script:

```
// ==UserScript==
// @name         Fix Walmart
// @namespace    http://tampermonkey.net/
// @version      2024-09-05
// @description  fix walmart
// @author       You
// @match        https://www.walmart.com/orders*
// @icon         https://i5.walmartimages.com/dfw/63fd9f59-fd82/d9c2b350-71fe-4bc2-be43-23fd97630434/v1/Walmart+_Logo_mweb.svg
// @grant        none
// ==/UserScript==

function hideSidebar() {
    const element = document.querySelector('.flex>.dn.br.b--black-10');
    console.log("tampermonkey; hiding sidebar. got element", element);
    element.style.display = 'none';
}

async function viewDetailsLink() {
    const buttons = document.querySelectorAll('main>section section>div>div>div>div>span>div>button');
    console.log("tampermonkey: view details link, got", buttons.length, "buttons");
    for (let i = 0; i < buttons.length; ++i) {
        // The default listener appears to be mousedown. By overriding mousedown, we eliminate the default
        //action and replace with our own
        const orderNumber =buttons[i].ariaLabel.split(' ').at(-1);
        buttons[i].onmousedown = ()=>window.open('https://walmart.com/orders/' + orderNumber, '_blank').focus();
    }
}

// The site is a SPA, so it changes dynamically without us knowing about it
setInterval(hideSidebar, 1000);
setInterval(viewDetailsLink, 1000);
```

When I go to walmart.com/orders, the page is not affected (I expect `hideSidebar()` to hide the sidebar). When I open devtools then reload the page, the sidebar is hidden as expected.

I looked for a discord server or IRC channel to discuss this as it's likely PEBKAC, but didn't find anything.

Can I get the script to run when I visit the site without devtools open?

**Comment by derjanb** [comment] 2024-10-31 18:54
> // The site is a SPA, so it changes dynamically without us knowing about it

Please change `@match` to `https://www.walmart.com/*` and check the URL within your script. You can use  `window.onurlchange` [support](http://tmnk.net/documentation.php#_grant) to detect URL changes.

Duplicate of #584

**Closed by derjanb** 2024-10-31 18:54 UTC

**Comment by limitedAtonement** [comment] 2024-10-31 20:48
> Please change @match to https://www.walmart.com/* and check the URL within your script.

That's not what I want...I don't want to change anything except https://www.walmart.com/orders and URLs like https://www.walmart.com/orders/200012593984575 for specific orders. That said, changing to `https://www.walmart.com/*` works, but I'm not sure why. #584 seems unrelated as I don't have any `#` in the URL.

**Comment by derjanb** [comment] 2024-10-31 22:25
> I only want to change content on https://www.walmart.com/orders

Yes, but the URL is changed by JavaScript and the HTML then modified accordingly. That's why you need to match all paths and filter on what new HTML of the page to run by your own.

```
// ==UserScript==
...
// ==/UserScript==

const checkAndDoIt = () => {
  if (!location.pathname.startWith('/orders') return;

  // your code here!
};
window.onurlchange(checkAndDoIt);
checkAndDoIt();
```
