### ISSUE TITLE
Script not Running in Safari

### ISSUE THREAD

**Issue by CodexJeff** [Tampermonkey/tampermonkey#1248] opened 2021-05-24 22:47 UTC
## Expected Behavior

The script below is to not be working and it seems to be how Tampermonkey handles notifications in Safari. I tried running the script in Firefox using Tampermonkey however, and everything seems to work fine. Spoke to a Tampermonkey dev a few months ago regarding this, but was just wondering if a solution was found.

## Actual Behavior
In the developer console in Safari, it throws an error and the script does not run.

## Specifications

- Safari Version 14.1 (16611.1.21.161.6)
- TM: 4.11.6117
- MacOS 10.13.4

## Script

https://github.com/MALSync/MALSync 

(Latest Release 0.8.9)

Script is used for users to keep track of anime episodes on various websites and have it updated on an anime tracking website.

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment] 2021-07-01 12:52
Duplicate of #1028

**Closed by derjanb** 2021-07-01 12:52 UTC
Labels: safari
