### ISSUE TITLE
GM_setValue stops working (Firefox Nightly for Android)

### ISSUE THREAD

**Issue by ttsilva90** [Tampermonkey/tampermonkey#1924] opened 2023-12-08 16:02 UTC
Using Firefox Nightly on Android. The issue started happening yesterday with the 5.0.0 update, although it could be a coincidence and be caused by a Firefox nightly update...

## Expected Behavior
GM_setValue works

## Actual Behavior
Randomly, GM_setValue will stop working (new values don't get saved). I haven't been able to figure out a pattern yet. Remote debugging shows the following warning when this happens:
`ports: unkown id lpwwpk95.gj6`

<img width="1536" alt="screenshot" src="https://github.com/Tampermonkey/tampermonkey/assets/14822854/eab3b479-a5d0-4e70-8804-035c5beadb6a">

## Specifications

- Firefox Nightly: 122.0a1
- TM: 5.0.0
- OS: Android 13

**Comment by Karlston2** [comment] 2023-12-08 18:28
After the 5.0.0 update, seeing the same behaviour on Firefox 117.0.1/Windows 10.

Clicking the button I add to the page, which triggers the GM_setValue part of the script, a **second** time works always.

**Comment by derjanb** [comment] 2023-12-08 19:30
Does this happen only after some time passed since the page was loaded?

Tampermonkey switched to an event page that can be stopped and started as needed for future Android compatibility. 
So my first guess is that this happens when the background page was unloaded when `GM_setValue` is called.

**Comment by Karlston2** [comment] 2023-12-09 02:07
Not sure if you're asking me, in case you are...

The script adds a set of buttons in a sort of navigation toolbar to certain pages,

When I click one of the buttons, the script (1) sets 3 storage values then (2) opens a new tab to its right.

The newly opened tab also runs this same script, its role here is to **retrieve** the 3 storage values and populate 3 screen elements from them. Simply, designed to move data from one page to another newly opened one.

The first time the button is clicked the new tab opens as expected, but loads the **previous** set of values, what they were before the first script should have updated them. If I click the button on the first tab again (within a few seconds of the first click), the resulting new tab shows the correct values.

The first pages may have been open for several minutes before their button was clicked.

It worked fine before the upgrade, never experienced this behaviour.

**Comment by Karlston2** [comment] 2023-12-09 08:55
Sorry, I take it back. It worked flawlessly for me.

But I know what I saw. GM_getValue() returned old values after GM_setValue() had changed them moments earlier.

**Comment by derjanb** [comment] 2023-12-09 19:39
> But I know what I saw. GM_getValue() returned old values after GM_setValue() had changed them moments earlier.

I think this can happen when the background page was shut down by the browser and then GM_setValue is called. It's a race condition then whether the new value is stored or not.

**Comment by Karlston2** [comment] 2023-12-10 03:08
I love TM and not doubting what you're saying, but...

In 10,000+ uses of this script with older versions of TM (and Firefox) over the last nearly 3 years, I've not seen this behaviour a single time, and it would stand out so much I couldn't possibly have missed it.

Since v5.0.0 update the behaviour is quite common. It works or fails in bursts. In a session of doing 5-25 tabs, once one shows the old values in the newly opened tab, the rest will too.

That said, I have an easy quick workaround of closing the newly opened tab (showing the old values) and clicking the button on the 'calling' tab once again. That has always worked. Maybe because the second time, 'old' is 'new'? :)

**Comment by ErskaConti** [comment] 2023-12-10 10:52
I have a similar problem after updating;

I have script that sorts Threadmark-links (and thread-links) into new/read/notInterested, this info is stored through GM_setValue() and after the update any changes I've made aren't stored.

***
Tampermonkey 5.0.0
Librewolf 120.0.1-1
EndeavourOS

**Comment by derjanb** [comment] 2023-12-14 22:53
> In 10,000+ uses of this script with older versions of TM (and Firefox) over the last nearly 3 years, I've not seen this behaviour a single time

The last Tampermonkey version switched to an event page, which can be shut down by the browser if not needed anymore.
When this happens, there is a race condition when the page sent a message to the background page, but it was too late to prolong its lifetime, and the background page is closed. The page doesn't know that the message wasn't received and this was happening with some `GM_setValue` calls.

**Comment by Karlston2** [comment] 2023-12-15 22:11
Thanks, I (sort of) see.

So, all scripts' GM_getValue() calls may or may not return the most recent GM_setValue() value? If so, aren't these two functions now essentially broken because their expected behaviour is unreliable?

I'm guessing this change was to make TM compatible with Manifest V3? I read the Mozilla developer document https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts

Can you test the browser for Manifest V2 compatibility and use a persistent background page if it's V2 compatible, otherwise use non-persistent as you are now?

Or force the non-persistent to reload if it's unloaded? Or can we do that in scripts somehow?

**Comment by derjanb** [comment] 2023-12-18 09:06
> So, all scripts' GM_getValue() calls may or may not return the most recent GM_setValue() value?

`GM_getValue` will always return the latest `GM_setValue` that was set at that very same tab. But changes from one tab are synced asynchronously to the background and other tabs.  So some raciness was there all the time.

What's different now is that calls right before the background is unloaded and (what I recently investigated) the very first call the wakes the background up again are not processed by the background page. A second save request fixes the issue. It depends on the script how severe the impact is.

For now you can downgrade to 4.19.0 if you encounter issues.

I also have a new fixed BETA version uploaded, but it is still in review since 2023-12-14.

Sorry for any inconvenience.

**Comment by derjanb** [comment] 2023-12-19 20:01
Should be fixed at 5.0.6191 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

If possible, please also enable anonymous statistics because the sent crash reports help to detect issues earlier...

**Comment by derjanb** [comment] 2024-01-08 13:42
5.0.1 which includes the fix is available here: https://addons.mozilla.org/de/firefox/addon/tampermonkey/

Sorry for any inconvenience!

**Closed by derjanb** 2024-01-08 13:42 UTC
Labels: bug, fixed at beta, firefox
