### ISSUE TITLE
Small Request filter in the Dashboard

### ISSUE THREAD

**Issue by mikhoul** [Tampermonkey/tampermonkey#566] opened 2018-06-15 17:07 UTC
Hi,

Since I ha a lot of Userscripts I found myself to enable the Filter "bar" each time I goes in the dashboard to search for a userscript. 

I'd like to have an option  to leave the search field enabled by default, so I will have no longer to click each time I access the dashboard.

![image](https://user-images.githubusercontent.com/5678673/41480616-02aab460-709d-11e8-8261-093b3667723e.png)

Thanks for this extension :octocat:

**Comment by derjanb** [comment] 2018-06-18 07:35
You can also open it by pressing Ctrl+F. However, the **next beta version** will make the following "Custom CSS" work:

Please open Tampermonkey's options page, and set "Config Mode" to "Advanced" to see the option "Custom CSS" and set it to this value:

```CSS
.multiselectrow {
     display: table-row !important;
}
```

**Comment by rayman89** [comment] 2018-06-19 13:11
Sorry to hijack this thread but why does the search bar not function unless the "apply to all selected scripts" is on? is that expected behavior?

**Comment by derjanb** [comment] 2018-06-19 13:30
@rayman89 You mean after using the "Custom CSS" from above? This will be fixed at the beta version. If it is opened via CTRL+F or the small filter icon, then it should function as intended.

**Comment by rayman89** [comment] 2018-06-19 15:11
Yes I meant when using the css ( I did not know that search bar existed before this so my frist try of it was after using the css). Thank you. BTW do you mind checking this? #547

**Comment by mikhoul** [comment] 2018-06-19 22:32
:+1:

**Closed** 2018-10-12 17:40 UTC
Labels: enhancement, fixed at beta
