### ISSUE TITLE
"Check for userscript updates" doesn't work on Chromium Edge

### ISSUE THREAD

**Issue by double-beep** [Tampermonkey/tampermonkey#1123] opened 2021-01-17 18:54 UTC
## Steps to reproduce

- Install a script from an external location - e.g. GitHub.
- Change the version (downgrade it).
- Go to Utilities &rarr; Check for userscipt updates.
- At first, it shows "Check for userscript updates...", then it disappears, without a "No updates found, sry!" message.
- Also tried the changelog and notification options of "Show TM update notification", but the same happened.
- Settings &rarr; Check for updates is checked. The update URL is correct (`https://github.com/owner/repo/raw/branch/path/to/userscript.user.js`)

## Specifications

- Chromium Edge version 87.0.664.75
- TM Beta v4.12.6126
- OS: Windows 10

**Comment by derjanb** [comment] 2021-01-21 11:47
Duplicate of #527

**Closed by derjanb** 2021-01-21 11:47 UTC
Labels: enhancement

**Comment by double-beep** [comment] 2021-01-21 19:16
@derjanb how long should I wait? More than a day passed and the userscript(s) doesn't/don't update.

**Comment by derjanb** [comment] 2021-01-21 19:20
Can you check the [background page's](https://www.tampermonkey.net/faq.php#Q600) network tab? What request headers are sent at the update request?

**Comment by double-beep** [comment] 2021-01-21 19:29
@derjanb First one to `https://github.com/owner/repo/raw/master/path/to/userscript.user.js` which 302s to `https://raw.githubusercontent.com/owner/repo/master/path/to/userscript.user.js`. The second request's response contains the updated version (`// @version     1.0.4`) while mine is `// @version     1.0.2`.

**Comment by derjanb** [comment] 2021-01-22 07:16
Not sure what happens to you, but my testing with https://github.com/derjanb/test/raw/master/test.user.js indeed resolved to 0.1 for some time, but this morning the update check found 0.2.

![image](https://user-images.githubusercontent.com/767504/105459090-f2e06800-5c89-11eb-9e4c-288d0c8c4e06.png)

**Comment by double-beep** [comment] 2021-01-22 11:18
For me, it fails to open a new tab with the changes for some reason. If I tick "Don't ask me for simple script updates" it automatically updates it, and if not, it shows "Check for userscript updates..." but no "No update found, sry".

**Comment by derjanb** [comment] 2021-01-22 12:15
This also works as expected here. If "Don't ask me for simple script updates" is unchecked, then another notification should be shown mentioning that there is an update available.

**Comment by double-beep** [comment] 2021-01-22 13:22
@derjanb will I also get a notification if "Show TM update notification:" is set to "Open changelog"?

No, there aren't any errors in the console.

**Comment by derjanb** [comment] 2021-01-22 16:05
> will I also get a notification if "Show TM update notification:" is set to "Open changelog"?

A script update notification? Yes, this options does not interfere with the update mechanism.

> If "Don't ask me for simple script updates" is unchecked, then another notification should be shown mentioning that there is an update available.

Hmm, I can do what I want. I always get the update notification:

![image](https://user-images.githubusercontent.com/767504/105514200-84c09300-5cd3-11eb-97f4-33cb2a7bed73.png)

Can you please set "Log Level" to debug? After triggering the update the console should log something like this:

![image](https://user-images.githubusercontent.com/767504/105514541-e123b280-5cd3-11eb-8013-0f86a4a80477.png)

**Comment by double-beep** [comment] 2021-01-22 17:30
In the stable version of Tampermonkey (I think that) when an update was available instead of a notification. What happened to this?
