### ISSUE TITLE
Cannot download blobs on Firefox

### ISSUE THREAD

**Issue by martixy** [Tampermonkey/tampermonkey#1738] opened 2023-03-16 14:02 UTC
Try this:
```js
const blob = new Blob(['with syrup'], { type: 'text/plain' })
GM_download({
    url: URL.createObjectURL(blob),
    name: 'waffles.txt',
})
```

It works quite well in chromium based browsers, and fails silently in Firefox.

Might well be a browser bug, but I have no way to make that determination, hence submitting here first.

(Unrelated, but it's fascinating how both browsers render the same font ever so slightly differently. I think webkit has better rendering. It's like cleartype isn't really working on firefox.)

## Specifications

- Firefox v111
- TM: v4.18.1
- OS: w10

**Comment by derjanb** [comment] 2023-03-16 14:22
Duplicate of #1223 ;-)

**Closed by derjanb** 2023-03-16 14:22 UTC

**Comment by martixy** [comment] 2023-03-16 14:56
Uncanny timing. 😮
