### ISSUE TITLE
TM 5.0 stops browsing if Firefox is in "Never Remember History" mode

### ISSUE THREAD

**Issue by jgoggan** [Tampermonkey/tampermonkey#1923] opened 2023-12-08 14:33 UTC
## Expected Behavior
Browsing should work.  :)

## Actual Behavior
Pages simply don't load at all.

## Specifications
- Firefox: 120.0.1 (64-bit)
- TM: v5.0.0 (also same behavior with current Beta)
- OS: Windows 10 64-bit

I have my Firefox in "Never Remember History" mode -- a.k.a. "Permanent Private Browsing" mode.  It has worked this way with TamperMonkey for years.  On two different PCs set this way, when TM upgraded to b5.0.0, all browsing stopped.  Going into settings and changing History back to "Remember History" (or even "Custom" and then setting everything to not remember manually) fixes the problem.  Changing History to "Never remember history" breaks everything again.

**Comment by jgoggan** [comment] 2023-12-08 14:40
I turned on debugging and check the Console and when in "Never Remember History" mode, this error is immediately given:

Uncaught (in promise) Error: Error opening database.
    onerror moz-extension://8b62588d-dc95-436e-8b22-6a29e513040f/background.js:385

**Comment by derjanb** [comment] 2023-12-08 15:01
Duplicate of #1921

Please see https://github.com/Tampermonkey/tampermonkey/issues/1921#issuecomment-1846906251

**Closed by derjanb** 2023-12-08 15:01 UTC
