### ISSUE TITLE
Tampermonkes stopped working

### ISSUE THREAD

**Issue by Skeeve** [Tampermonkey/tampermonkey#1527] opened 2022-06-13 18:30 UTC
## Expected Behavior

See an alert

## Actual Behavior

do not see an alert

## Specifications

- Vivaldi: 5.3.2679.38 (Stable channel) (x86_64)
- TM: 4.18.6163 (Works in 4.17.6161)
- OS: MacOS 10.15.7

## Script

```js
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://s.to/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=s.to
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    alert("OKAY")
})();
```

**Comment by derjanb** [comment] 2022-06-13 18:35
Are you using Instant inject mode?

**Comment by Skeeve** [comment] 2022-06-13 18:41
> Are you using Instant inject mode?

If you can tell me what that is or how I can check, I'll try to answer that question.

**Comment by Skeeve** [comment] 2022-06-13 18:44
BTW: The Tampermonkey menu on the page doesn't even see that the script should run. So it's not the script that's not running it seems to be tampermonkey not finding the script.

**Comment by derjanb** [comment] 2022-06-13 18:44
If you don't know, then the answer probably is "no". :-)

Can you please do me a favor and disable 4.16.1 and enable 4.18.6163 again and check the background console for errors (http://tmnk.net/faq#Q600 -> Q600). Also there is a browser bug that makes TM not work after the recent update until the browser was restarted.

**Comment by Skeeve** [comment] 2022-06-13 18:49
Browser was restarted. No change.

Develeper tools show:

```
VM109 content.js:60 Uncaught (in promise) pagejs missing
(anonymous) @ VM109 content.js:60
(anonymous) @ VM109 content.js:60
(anonymous) @ VM109 content.js:60
(anonymous) @ VM109 content.js:60
DevTools failed to load source map: Could not load content for https://zrt5351b7er9.static-webarchive.org/css/main.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
(index):3169          GET https://mc.yandex.ru/metrika/tag.js net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ (index):3169
(anonymous) @ (index):3169```

**Comment by derjanb** [comment] 2022-06-13 18:51
> Uncaught (in promise) pagejs missing

OK. Thanks. Duplicate of #1505
Please restart your browser. :man_shrugging:

Note: after closing it might take some seconds until all processed are closed.

**Closed by derjanb** 2022-06-13 18:51 UTC
